import * as rdsdata from "@distilled.cloud/aws/rds-data";
import * as Effect from "effect/Effect";
import * as Schedule from "effect/Schedule";
import { isResolved } from "../../Diff.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  hashImports,
  hashMigrations,
  listSqlFiles,
  readSqlFile,
} from "../../Sql/SqlFile.ts";
import { recordsEqual } from "../../Util/equal.ts";
import type { Providers } from "../Providers.ts";

const DEFAULT_MIGRATIONS_TABLE = "__drizzle_migrations";
const DEFAULT_DATABASE = "app";

const rootDir = Effect.sync(() => process.cwd());

/**
 * Split a `.sql` file into individual statements. The RDS Data API runs exactly
 * one statement per `ExecuteStatement` call (unlike node-postgres, which runs a
 * whole multi-statement file), so migration files must be split.
 *
 * Files generated by `Drizzle.Schema` separate statements with drizzle's
 * `--> statement-breakpoint` marker — one statement per chunk, so the split is
 * exact. Hand-authored `importFiles` without that marker fall back to splitting
 * on `;`, which is unsafe for dollar-quoted bodies (`DO $$ ... $$`,
 * `CREATE FUNCTION ... $$ ... $$`) — author those with `--> statement-breakpoint`.
 */
export const splitStatements = (sql: string): string[] => {
  const parts = sql.includes("statement-breakpoint")
    ? sql.split(/^\s*-->\s*statement-breakpoint\s*$/m)
    : sql.split(/;\s*$/m);
  return parts
    .map((s) => s.trim().replace(/;\s*$/, "").trim())
    .filter((s) => s.length > 0);
};

export interface SchemaProps {
  /**
   * The Aurora cluster ARN to apply migrations to — pass `cluster.dbClusterArn`
   * from an `AWS.RDS.Aurora` / `AWS.RDS.DBCluster`. The cluster must have the
   * Data API (HTTP endpoint) enabled, which `AWS.RDS.Aurora` does by default.
   */
  resourceArn: string;
  /**
   * The Secrets Manager secret ARN holding the cluster's master credentials —
   * pass `secret.secretArn` from `AWS.RDS.Aurora`. The Data API reads it
   * server-side; no `secretsmanager:GetSecretValue` grant is needed on the
   * deployer beyond the ambient `rds-data:*` permissions.
   */
  secretArn: string;
  /**
   * Database name to apply migrations against.
   * @default "app"
   */
  database?: string;
  /**
   * Directory containing `.sql` migration files. Files are sorted by their
   * numeric prefix (e.g. `0001_init.sql`) and applied in order. Wire this to
   * `Drizzle.Schema`'s `out` so pending migrations regenerate and apply in a
   * single deploy.
   */
  migrationsDir?: string;
  /**
   * Name of the table tracking applied migrations.
   * @default "__drizzle_migrations"
   */
  migrationsTable?: string;
  /**
   * Paths to additional `.sql` files applied (once each, hash-gated) after the
   * directory migrations — e.g. seed data.
   */
  importFiles?: string[];
}

export interface Schema extends Resource<
  "AWS.RDS.Schema",
  SchemaProps,
  {
    resourceArn: string;
    secretArn: string;
    database: string;
    migrationsDir: string | undefined;
    migrationsTable: string;
    migrationsHashes: Record<string, string>;
    importHashes: Record<string, string>;
  },
  never,
  Providers
> {}

/**
 * Applies Drizzle (or hand-authored) SQL migrations to an Aurora cluster
 * through the **RDS Data API** at deploy time.
 *
 * Unlike Neon/Planetscale — where migrations run over a node-postgres
 * connection — `AWS.RDS.Schema` speaks the Data API over HTTPS+IAM, so the
 * deploy machine never needs network reachability to a VPC-private cluster.
 * Each migration file runs inside a Data API transaction (one statement per
 * call) and is recorded in a tracking table so re-deploys are idempotent.
 *
 * Pair it with `Drizzle.Schema` for the same deploy-driven flow as the
 * Neon/Planetscale examples: `Drizzle.Schema` regenerates pending migration
 * SQL, then `AWS.RDS.Schema` applies it.
 *
 * @section Applying migrations
 * @example Drizzle migrations via the Data API
 * ```typescript
 * const schema = yield* Drizzle.Schema("AppSchema", {
 *   schema: "./src/schema.ts",
 * });
 * const db = yield* AWS.RDS.Aurora("AppDb", { subnetIds, securityGroupIds });
 * yield* AWS.RDS.Schema("AppDbSchema", {
 *   resourceArn: db.cluster.dbClusterArn,
 *   secretArn: db.secret.secretArn,
 *   migrationsDir: schema.out,
 * });
 * ```
 *
 * @example With seed data
 * ```typescript
 * yield* AWS.RDS.Schema("AppDbSchema", {
 *   resourceArn: db.cluster.dbClusterArn,
 *   secretArn: db.secret.secretArn,
 *   migrationsDir: schema.out,
 *   importFiles: ["./seed/users.sql"],
 * });
 * ```
 */
export const Schema = Resource<Schema>("AWS.RDS.Schema");

export const SchemaProvider = () =>
  Provider.effect(
    Schema,
    Effect.gen(function* () {
      return {
        // Local artifact driven by `migrationsDir` props — nothing to
        // enumerate out-of-band.
        list: () => Effect.succeed([]),

        diff: Effect.fn(function* ({ news, output }) {
          if (!isResolved(news)) return undefined;
          // Target identity changed (e.g. the cluster was replaced) — the new
          // database needs the full migration set.
          if (
            output &&
            (news.resourceArn !== output.resourceArn ||
              (news.database ?? DEFAULT_DATABASE) !== output.database)
          ) {
            return { action: "update" } as const;
          }
          if (news.migrationsDir) {
            const newHashes = yield* hashMigrations(news.migrationsDir);
            if (!recordsEqual(newHashes, output?.migrationsHashes ?? {})) {
              return { action: "update" } as const;
            }
            if (
              (news.migrationsTable ?? DEFAULT_MIGRATIONS_TABLE) !==
              (output?.migrationsTable ?? DEFAULT_MIGRATIONS_TABLE)
            ) {
              return { action: "update" } as const;
            }
          }
          if (news.importFiles?.length) {
            const newHashes = yield* hashImports(
              news.importFiles,
              yield* rootDir,
            );
            if (!recordsEqual(newHashes, output?.importHashes ?? {})) {
              return { action: "update" } as const;
            }
          }
          return undefined;
        }),

        // The "remote" state is the migrations table; there is no cheap
        // out-of-band drift source, so refresh is a no-op.
        read: Effect.fn(function* ({ output }) {
          return output;
        }),

        reconcile: Effect.fn(function* ({ news, output, session }) {
          const resourceArn = news.resourceArn;
          const secretArn = news.secretArn;
          const database = news.database ?? DEFAULT_DATABASE;
          const migrationsTable =
            news.migrationsTable ?? DEFAULT_MIGRATIONS_TABLE;

          const exec = (
            sql: string,
            opts?: {
              transactionId?: string;
              parameters?: rdsdata.SqlParameter[];
            },
          ) =>
            rdsdata.executeStatement({
              resourceArn,
              secretArn,
              // `database` is bound by the transaction; passing it alongside a
              // `transactionId` is rejected by the Data API.
              database: opts?.transactionId ? undefined : database,
              sql,
              transactionId: opts?.transactionId,
              parameters: opts?.parameters,
            });

          const runInTransaction = (
            statements: ReadonlyArray<
              string | { sql: string; parameters?: rdsdata.SqlParameter[] }
            >,
          ) =>
            Effect.gen(function* () {
              const begun = yield* rdsdata.beginTransaction({
                resourceArn,
                secretArn,
                database,
              });
              const transactionId = begun.transactionId;
              if (!transactionId) {
                return yield* Effect.die(
                  "RDS Data API beginTransaction returned no transactionId",
                );
              }
              yield* Effect.gen(function* () {
                for (const stmt of statements) {
                  if (typeof stmt === "string") {
                    yield* exec(stmt, { transactionId });
                  } else {
                    yield* exec(stmt.sql, {
                      transactionId,
                      parameters: stmt.parameters,
                    });
                  }
                }
                yield* rdsdata.commitTransaction({
                  resourceArn,
                  secretArn,
                  transactionId,
                });
              }).pipe(
                Effect.tapError(() =>
                  rdsdata
                    .rollbackTransaction({
                      resourceArn,
                      secretArn,
                      transactionId,
                    })
                    .pipe(Effect.ignore),
                ),
              );
            });

          // ── Wait for the Data API to be query-ready ────────────────────
          // On a fresh `AWS.RDS.Aurora` deploy this resource depends only on
          // the cluster ARN, so it can run while the writer instance is still
          // provisioning — the Data API then rejects with
          // `DatabaseNotFoundException: Cannot find DBInstance in DBCluster`
          // (or a resuming/unavailable error for a paused serverless cluster).
          // Probe `SELECT 1` and wait out those transient states before
          // touching the schema; a genuinely wrong database name surfaces as a
          // `DatabaseNotFoundException` with a different message and fails fast.
          const isWarmingUp = (e: rdsdata.ExecuteStatementError) =>
            e._tag === "DatabaseResumingException" ||
            e._tag === "DatabaseUnavailableException" ||
            ((e._tag === "DatabaseNotFoundException" ||
              e._tag === "BadRequestException") &&
              /cannot find dbinstance|not currently available|resuming|not available/i.test(
                e.message ?? "",
              ));

          const hasWork =
            !!news.migrationsDir || (news.importFiles?.length ?? 0) > 0;
          if (hasWork) {
            yield* session.note(
              "Waiting for the Aurora Data API to become available",
            );
            yield* exec("SELECT 1;").pipe(
              Effect.retry({
                while: isWarmingUp,
                // Aurora writer-instance provisioning can take well over five
                // minutes; wait up to ~15m (deploy-time, one-shot) so a slow
                // instance launch doesn't abort the migration.
                schedule: Schedule.spaced("10 seconds"),
                times: 90,
              }),
            );
          }

          // ── Directory migrations ───────────────────────────────────────
          let migrationsHashes = output?.migrationsHashes ?? {};
          if (news.migrationsDir) {
            const files = yield* listSqlFiles(news.migrationsDir);
            if (files.length > 0) {
              yield* session.note(
                `Applying ${files.length} RDS Data API migration(s) to "${database}"`,
              );
              yield* exec(
                `CREATE TABLE IF NOT EXISTS "${migrationsTable}" (` +
                  `id TEXT PRIMARY KEY, name TEXT NOT NULL, ` +
                  `applied_at TIMESTAMPTZ NOT NULL DEFAULT now());`,
              );
              const appliedRes = yield* exec(
                `SELECT name FROM "${migrationsTable}";`,
              );
              const applied = new Set(
                (appliedRes.records ?? [])
                  .map((row) => row[0]?.stringValue)
                  .filter((v): v is string => v !== undefined),
              );
              let nextSeq = 1;
              const idRes = yield* exec(`SELECT id FROM "${migrationsTable}";`);
              for (const row of idRes.records ?? []) {
                const id = row[0]?.stringValue;
                if (id && /^\d+$/.test(id)) {
                  nextSeq = Math.max(nextSeq, Number.parseInt(id, 10) + 1);
                }
              }

              const hashes: Record<string, string> = {};
              for (const file of files) {
                if (!applied.has(file.id)) {
                  const id = nextSeq.toString().padStart(5, "0");
                  nextSeq += 1;
                  yield* runInTransaction([
                    ...splitStatements(file.sql),
                    {
                      sql:
                        `INSERT INTO "${migrationsTable}" (id, name) ` +
                        `VALUES (:id, :name);`,
                      parameters: [
                        { name: "id", value: { stringValue: id } },
                        { name: "name", value: { stringValue: file.id } },
                      ],
                    },
                  ]);
                }
                hashes[file.id] = file.hash;
              }
              migrationsHashes = hashes;
            } else {
              migrationsHashes = {};
            }
          }

          // ── Import files (seed data) ───────────────────────────────────
          let importHashes = output?.importHashes ?? {};
          if (news.importFiles?.length) {
            const root = yield* rootDir;
            const previous = output?.importHashes ?? {};
            const next: Record<string, string> = { ...previous };
            for (const filePath of news.importFiles) {
              const file = yield* readSqlFile(root, filePath);
              if (previous[filePath] !== file.hash) {
                yield* runInTransaction(splitStatements(file.sql));
              }
              next[filePath] = file.hash;
            }
            const tracked = new Set(news.importFiles);
            for (const key of Object.keys(next)) {
              if (!tracked.has(key)) delete next[key];
            }
            importHashes = next;
          }

          return {
            resourceArn,
            secretArn,
            database,
            migrationsDir: news.migrationsDir,
            migrationsTable,
            migrationsHashes,
            importHashes,
          };
        }),

        delete: Effect.fn(function* () {
          // Migrations are checked in and shared across environments; tearing
          // down this resource does not drop tables.
        }),
      };
    }),
  );
