// Auto-generated by generate-awsquery-metadata.ts. DO NOT EDIT BY HAND.

export type ShapeKind =
  | "structure"
  | "list"
  | "map"
  | "string"
  | "integer"
  | "boolean"
  | "timestamp"
  | "blob"
  | "enum"
  | "double"
  | "long"
  | "float"
  | "union";

export interface MemberMeta {
  target: string;
  locationName?: string;
  queryName?: string;
  flattened?: boolean;
  timestampFormat?: "iso8601" | "epoch-seconds" | "http-date";
}

export interface ShapeMeta {
  type: ShapeKind;
  xmlName?: string;
  members?: Record<string, MemberMeta>;
  member?: MemberMeta;
  key?: MemberMeta;
  value?: MemberMeta;
  enum?: string[];
  flattened?: boolean;
}

export interface OperationMeta {
  name: string;
  input?: string;
  output?: string;
  responseWrapper?: string;
}

export interface AwsQueryServiceMeta {
  serviceId: string;
  serviceName: string;
  version: string;
  endpointPrefix?: string;
  operations: Record<string, OperationMeta>;
  shapes: Record<string, ShapeMeta>;
}

export const metadata: AwsQueryServiceMeta = {
  serviceId: "CloudSearch",
  serviceName: "CloudSearch",
  version: "2013-01-01",
  endpointPrefix: "cloudsearch",
  operations: {
    BuildSuggesters: {
      name: "BuildSuggesters",
      input: "com.amazonaws.cloudsearch#BuildSuggestersRequest",
      output: "com.amazonaws.cloudsearch#BuildSuggestersResponse",
      responseWrapper: "BuildSuggestersResponse",
    },
    CreateDomain: {
      name: "CreateDomain",
      input: "com.amazonaws.cloudsearch#CreateDomainRequest",
      output: "com.amazonaws.cloudsearch#CreateDomainResponse",
      responseWrapper: "CreateDomainResponse",
    },
    DefineAnalysisScheme: {
      name: "DefineAnalysisScheme",
      input: "com.amazonaws.cloudsearch#DefineAnalysisSchemeRequest",
      output: "com.amazonaws.cloudsearch#DefineAnalysisSchemeResponse",
      responseWrapper: "DefineAnalysisSchemeResponse",
    },
    DefineExpression: {
      name: "DefineExpression",
      input: "com.amazonaws.cloudsearch#DefineExpressionRequest",
      output: "com.amazonaws.cloudsearch#DefineExpressionResponse",
      responseWrapper: "DefineExpressionResponse",
    },
    DefineIndexField: {
      name: "DefineIndexField",
      input: "com.amazonaws.cloudsearch#DefineIndexFieldRequest",
      output: "com.amazonaws.cloudsearch#DefineIndexFieldResponse",
      responseWrapper: "DefineIndexFieldResponse",
    },
    DefineSuggester: {
      name: "DefineSuggester",
      input: "com.amazonaws.cloudsearch#DefineSuggesterRequest",
      output: "com.amazonaws.cloudsearch#DefineSuggesterResponse",
      responseWrapper: "DefineSuggesterResponse",
    },
    DeleteAnalysisScheme: {
      name: "DeleteAnalysisScheme",
      input: "com.amazonaws.cloudsearch#DeleteAnalysisSchemeRequest",
      output: "com.amazonaws.cloudsearch#DeleteAnalysisSchemeResponse",
      responseWrapper: "DeleteAnalysisSchemeResponse",
    },
    DeleteDomain: {
      name: "DeleteDomain",
      input: "com.amazonaws.cloudsearch#DeleteDomainRequest",
      output: "com.amazonaws.cloudsearch#DeleteDomainResponse",
      responseWrapper: "DeleteDomainResponse",
    },
    DeleteExpression: {
      name: "DeleteExpression",
      input: "com.amazonaws.cloudsearch#DeleteExpressionRequest",
      output: "com.amazonaws.cloudsearch#DeleteExpressionResponse",
      responseWrapper: "DeleteExpressionResponse",
    },
    DeleteIndexField: {
      name: "DeleteIndexField",
      input: "com.amazonaws.cloudsearch#DeleteIndexFieldRequest",
      output: "com.amazonaws.cloudsearch#DeleteIndexFieldResponse",
      responseWrapper: "DeleteIndexFieldResponse",
    },
    DeleteSuggester: {
      name: "DeleteSuggester",
      input: "com.amazonaws.cloudsearch#DeleteSuggesterRequest",
      output: "com.amazonaws.cloudsearch#DeleteSuggesterResponse",
      responseWrapper: "DeleteSuggesterResponse",
    },
    DescribeAnalysisSchemes: {
      name: "DescribeAnalysisSchemes",
      input: "com.amazonaws.cloudsearch#DescribeAnalysisSchemesRequest",
      output: "com.amazonaws.cloudsearch#DescribeAnalysisSchemesResponse",
      responseWrapper: "DescribeAnalysisSchemesResponse",
    },
    DescribeAvailabilityOptions: {
      name: "DescribeAvailabilityOptions",
      input: "com.amazonaws.cloudsearch#DescribeAvailabilityOptionsRequest",
      output: "com.amazonaws.cloudsearch#DescribeAvailabilityOptionsResponse",
      responseWrapper: "DescribeAvailabilityOptionsResponse",
    },
    DescribeDomainEndpointOptions: {
      name: "DescribeDomainEndpointOptions",
      input: "com.amazonaws.cloudsearch#DescribeDomainEndpointOptionsRequest",
      output: "com.amazonaws.cloudsearch#DescribeDomainEndpointOptionsResponse",
      responseWrapper: "DescribeDomainEndpointOptionsResponse",
    },
    DescribeDomains: {
      name: "DescribeDomains",
      input: "com.amazonaws.cloudsearch#DescribeDomainsRequest",
      output: "com.amazonaws.cloudsearch#DescribeDomainsResponse",
      responseWrapper: "DescribeDomainsResponse",
    },
    DescribeExpressions: {
      name: "DescribeExpressions",
      input: "com.amazonaws.cloudsearch#DescribeExpressionsRequest",
      output: "com.amazonaws.cloudsearch#DescribeExpressionsResponse",
      responseWrapper: "DescribeExpressionsResponse",
    },
    DescribeIndexFields: {
      name: "DescribeIndexFields",
      input: "com.amazonaws.cloudsearch#DescribeIndexFieldsRequest",
      output: "com.amazonaws.cloudsearch#DescribeIndexFieldsResponse",
      responseWrapper: "DescribeIndexFieldsResponse",
    },
    DescribeScalingParameters: {
      name: "DescribeScalingParameters",
      input: "com.amazonaws.cloudsearch#DescribeScalingParametersRequest",
      output: "com.amazonaws.cloudsearch#DescribeScalingParametersResponse",
      responseWrapper: "DescribeScalingParametersResponse",
    },
    DescribeServiceAccessPolicies: {
      name: "DescribeServiceAccessPolicies",
      input: "com.amazonaws.cloudsearch#DescribeServiceAccessPoliciesRequest",
      output: "com.amazonaws.cloudsearch#DescribeServiceAccessPoliciesResponse",
      responseWrapper: "DescribeServiceAccessPoliciesResponse",
    },
    DescribeSuggesters: {
      name: "DescribeSuggesters",
      input: "com.amazonaws.cloudsearch#DescribeSuggestersRequest",
      output: "com.amazonaws.cloudsearch#DescribeSuggestersResponse",
      responseWrapper: "DescribeSuggestersResponse",
    },
    IndexDocuments: {
      name: "IndexDocuments",
      input: "com.amazonaws.cloudsearch#IndexDocumentsRequest",
      output: "com.amazonaws.cloudsearch#IndexDocumentsResponse",
      responseWrapper: "IndexDocumentsResponse",
    },
    ListDomainNames: {
      name: "ListDomainNames",
      input: "smithy.api#Unit",
      output: "com.amazonaws.cloudsearch#ListDomainNamesResponse",
      responseWrapper: "ListDomainNamesResponse",
    },
    UpdateAvailabilityOptions: {
      name: "UpdateAvailabilityOptions",
      input: "com.amazonaws.cloudsearch#UpdateAvailabilityOptionsRequest",
      output: "com.amazonaws.cloudsearch#UpdateAvailabilityOptionsResponse",
      responseWrapper: "UpdateAvailabilityOptionsResponse",
    },
    UpdateDomainEndpointOptions: {
      name: "UpdateDomainEndpointOptions",
      input: "com.amazonaws.cloudsearch#UpdateDomainEndpointOptionsRequest",
      output: "com.amazonaws.cloudsearch#UpdateDomainEndpointOptionsResponse",
      responseWrapper: "UpdateDomainEndpointOptionsResponse",
    },
    UpdateScalingParameters: {
      name: "UpdateScalingParameters",
      input: "com.amazonaws.cloudsearch#UpdateScalingParametersRequest",
      output: "com.amazonaws.cloudsearch#UpdateScalingParametersResponse",
      responseWrapper: "UpdateScalingParametersResponse",
    },
    UpdateServiceAccessPolicies: {
      name: "UpdateServiceAccessPolicies",
      input: "com.amazonaws.cloudsearch#UpdateServiceAccessPoliciesRequest",
      output: "com.amazonaws.cloudsearch#UpdateServiceAccessPoliciesResponse",
      responseWrapper: "UpdateServiceAccessPoliciesResponse",
    },
  },
  shapes: {
    "com.amazonaws.cloudsearch#BuildSuggestersRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
      },
    },
    "com.amazonaws.cloudsearch#BuildSuggestersResponse": {
      type: "structure",
      members: {
        FieldNames: {
          target: "com.amazonaws.cloudsearch#FieldNameList",
        },
      },
    },
    "com.amazonaws.cloudsearch#CreateDomainRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
      },
    },
    "com.amazonaws.cloudsearch#CreateDomainResponse": {
      type: "structure",
      members: {
        DomainStatus: {
          target: "com.amazonaws.cloudsearch#DomainStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DefineAnalysisSchemeRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        AnalysisScheme: {
          target: "com.amazonaws.cloudsearch#AnalysisScheme",
        },
      },
    },
    "com.amazonaws.cloudsearch#DefineAnalysisSchemeResponse": {
      type: "structure",
      members: {
        AnalysisScheme: {
          target: "com.amazonaws.cloudsearch#AnalysisSchemeStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DefineExpressionRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        Expression: {
          target: "com.amazonaws.cloudsearch#Expression",
        },
      },
    },
    "com.amazonaws.cloudsearch#DefineExpressionResponse": {
      type: "structure",
      members: {
        Expression: {
          target: "com.amazonaws.cloudsearch#ExpressionStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DefineIndexFieldRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        IndexField: {
          target: "com.amazonaws.cloudsearch#IndexField",
        },
      },
    },
    "com.amazonaws.cloudsearch#DefineIndexFieldResponse": {
      type: "structure",
      members: {
        IndexField: {
          target: "com.amazonaws.cloudsearch#IndexFieldStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DefineSuggesterRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        Suggester: {
          target: "com.amazonaws.cloudsearch#Suggester",
        },
      },
    },
    "com.amazonaws.cloudsearch#DefineSuggesterResponse": {
      type: "structure",
      members: {
        Suggester: {
          target: "com.amazonaws.cloudsearch#SuggesterStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DeleteAnalysisSchemeRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        AnalysisSchemeName: {
          target: "com.amazonaws.cloudsearch#StandardName",
        },
      },
    },
    "com.amazonaws.cloudsearch#DeleteAnalysisSchemeResponse": {
      type: "structure",
      members: {
        AnalysisScheme: {
          target: "com.amazonaws.cloudsearch#AnalysisSchemeStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DeleteDomainRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
      },
    },
    "com.amazonaws.cloudsearch#DeleteDomainResponse": {
      type: "structure",
      members: {
        DomainStatus: {
          target: "com.amazonaws.cloudsearch#DomainStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DeleteExpressionRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        ExpressionName: {
          target: "com.amazonaws.cloudsearch#StandardName",
        },
      },
    },
    "com.amazonaws.cloudsearch#DeleteExpressionResponse": {
      type: "structure",
      members: {
        Expression: {
          target: "com.amazonaws.cloudsearch#ExpressionStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DeleteIndexFieldRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        IndexFieldName: {
          target: "com.amazonaws.cloudsearch#DynamicFieldName",
        },
      },
    },
    "com.amazonaws.cloudsearch#DeleteIndexFieldResponse": {
      type: "structure",
      members: {
        IndexField: {
          target: "com.amazonaws.cloudsearch#IndexFieldStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DeleteSuggesterRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        SuggesterName: {
          target: "com.amazonaws.cloudsearch#StandardName",
        },
      },
    },
    "com.amazonaws.cloudsearch#DeleteSuggesterResponse": {
      type: "structure",
      members: {
        Suggester: {
          target: "com.amazonaws.cloudsearch#SuggesterStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeAnalysisSchemesRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        AnalysisSchemeNames: {
          target: "com.amazonaws.cloudsearch#StandardNameList",
        },
        Deployed: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeAnalysisSchemesResponse": {
      type: "structure",
      members: {
        AnalysisSchemes: {
          target: "com.amazonaws.cloudsearch#AnalysisSchemeStatusList",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeAvailabilityOptionsRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        Deployed: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeAvailabilityOptionsResponse": {
      type: "structure",
      members: {
        AvailabilityOptions: {
          target: "com.amazonaws.cloudsearch#AvailabilityOptionsStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeDomainEndpointOptionsRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        Deployed: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeDomainEndpointOptionsResponse": {
      type: "structure",
      members: {
        DomainEndpointOptions: {
          target: "com.amazonaws.cloudsearch#DomainEndpointOptionsStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeDomainsRequest": {
      type: "structure",
      members: {
        DomainNames: {
          target: "com.amazonaws.cloudsearch#DomainNameList",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeDomainsResponse": {
      type: "structure",
      members: {
        DomainStatusList: {
          target: "com.amazonaws.cloudsearch#DomainStatusList",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeExpressionsRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        ExpressionNames: {
          target: "com.amazonaws.cloudsearch#StandardNameList",
        },
        Deployed: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeExpressionsResponse": {
      type: "structure",
      members: {
        Expressions: {
          target: "com.amazonaws.cloudsearch#ExpressionStatusList",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeIndexFieldsRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        FieldNames: {
          target: "com.amazonaws.cloudsearch#DynamicFieldNameList",
        },
        Deployed: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeIndexFieldsResponse": {
      type: "structure",
      members: {
        IndexFields: {
          target: "com.amazonaws.cloudsearch#IndexFieldStatusList",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeScalingParametersRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeScalingParametersResponse": {
      type: "structure",
      members: {
        ScalingParameters: {
          target: "com.amazonaws.cloudsearch#ScalingParametersStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeServiceAccessPoliciesRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        Deployed: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeServiceAccessPoliciesResponse": {
      type: "structure",
      members: {
        AccessPolicies: {
          target: "com.amazonaws.cloudsearch#AccessPoliciesStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeSuggestersRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        SuggesterNames: {
          target: "com.amazonaws.cloudsearch#StandardNameList",
        },
        Deployed: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#DescribeSuggestersResponse": {
      type: "structure",
      members: {
        Suggesters: {
          target: "com.amazonaws.cloudsearch#SuggesterStatusList",
        },
      },
    },
    "com.amazonaws.cloudsearch#IndexDocumentsRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
      },
    },
    "com.amazonaws.cloudsearch#IndexDocumentsResponse": {
      type: "structure",
      members: {
        FieldNames: {
          target: "com.amazonaws.cloudsearch#FieldNameList",
        },
      },
    },
    "com.amazonaws.cloudsearch#ListDomainNamesResponse": {
      type: "structure",
      members: {
        DomainNames: {
          target: "com.amazonaws.cloudsearch#DomainNameMap",
        },
      },
    },
    "com.amazonaws.cloudsearch#UpdateAvailabilityOptionsRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        MultiAZ: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#UpdateAvailabilityOptionsResponse": {
      type: "structure",
      members: {
        AvailabilityOptions: {
          target: "com.amazonaws.cloudsearch#AvailabilityOptionsStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#UpdateDomainEndpointOptionsRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        DomainEndpointOptions: {
          target: "com.amazonaws.cloudsearch#DomainEndpointOptions",
        },
      },
    },
    "com.amazonaws.cloudsearch#UpdateDomainEndpointOptionsResponse": {
      type: "structure",
      members: {
        DomainEndpointOptions: {
          target: "com.amazonaws.cloudsearch#DomainEndpointOptionsStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#UpdateScalingParametersRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        ScalingParameters: {
          target: "com.amazonaws.cloudsearch#ScalingParameters",
        },
      },
    },
    "com.amazonaws.cloudsearch#UpdateScalingParametersResponse": {
      type: "structure",
      members: {
        ScalingParameters: {
          target: "com.amazonaws.cloudsearch#ScalingParametersStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#UpdateServiceAccessPoliciesRequest": {
      type: "structure",
      members: {
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        AccessPolicies: {
          target: "com.amazonaws.cloudsearch#PolicyDocument",
        },
      },
    },
    "com.amazonaws.cloudsearch#UpdateServiceAccessPoliciesResponse": {
      type: "structure",
      members: {
        AccessPolicies: {
          target: "com.amazonaws.cloudsearch#AccessPoliciesStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DomainName": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#FieldNameList": {
      type: "list",
      member: {
        target: "com.amazonaws.cloudsearch#FieldName",
      },
    },
    "com.amazonaws.cloudsearch#FieldName": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#DomainStatus": {
      type: "structure",
      members: {
        DomainId: {
          target: "com.amazonaws.cloudsearch#DomainId",
        },
        DomainName: {
          target: "com.amazonaws.cloudsearch#DomainName",
        },
        ARN: {
          target: "com.amazonaws.cloudsearch#ARN",
        },
        Created: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        Deleted: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        DocService: {
          target: "com.amazonaws.cloudsearch#ServiceEndpoint",
        },
        SearchService: {
          target: "com.amazonaws.cloudsearch#ServiceEndpoint",
        },
        RequiresIndexDocuments: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        Processing: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SearchInstanceType: {
          target: "com.amazonaws.cloudsearch#SearchInstanceType",
        },
        SearchPartitionCount: {
          target: "com.amazonaws.cloudsearch#PartitionCount",
        },
        SearchInstanceCount: {
          target: "com.amazonaws.cloudsearch#InstanceCount",
        },
        Limits: {
          target: "com.amazonaws.cloudsearch#Limits",
        },
      },
    },
    "com.amazonaws.cloudsearch#DomainId": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#ARN": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#Boolean": {
      type: "boolean",
    },
    "com.amazonaws.cloudsearch#ServiceEndpoint": {
      type: "structure",
      members: {
        Endpoint: {
          target: "com.amazonaws.cloudsearch#ServiceUrl",
        },
      },
    },
    "com.amazonaws.cloudsearch#ServiceUrl": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#SearchInstanceType": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#PartitionCount": {
      type: "integer",
    },
    "com.amazonaws.cloudsearch#InstanceCount": {
      type: "integer",
    },
    "com.amazonaws.cloudsearch#Limits": {
      type: "structure",
      members: {
        MaximumReplicationCount: {
          target: "com.amazonaws.cloudsearch#MaximumReplicationCount",
        },
        MaximumPartitionCount: {
          target: "com.amazonaws.cloudsearch#MaximumPartitionCount",
        },
      },
    },
    "com.amazonaws.cloudsearch#MaximumReplicationCount": {
      type: "integer",
    },
    "com.amazonaws.cloudsearch#MaximumPartitionCount": {
      type: "integer",
    },
    "com.amazonaws.cloudsearch#AnalysisScheme": {
      type: "structure",
      members: {
        AnalysisSchemeName: {
          target: "com.amazonaws.cloudsearch#StandardName",
        },
        AnalysisSchemeLanguage: {
          target: "com.amazonaws.cloudsearch#AnalysisSchemeLanguage",
        },
        AnalysisOptions: {
          target: "com.amazonaws.cloudsearch#AnalysisOptions",
        },
      },
    },
    "com.amazonaws.cloudsearch#StandardName": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#AnalysisSchemeLanguage": {
      type: "enum",
    },
    "com.amazonaws.cloudsearch#AnalysisOptions": {
      type: "structure",
      members: {
        Synonyms: {
          target: "com.amazonaws.cloudsearch#String",
        },
        Stopwords: {
          target: "com.amazonaws.cloudsearch#String",
        },
        StemmingDictionary: {
          target: "com.amazonaws.cloudsearch#String",
        },
        JapaneseTokenizationDictionary: {
          target: "com.amazonaws.cloudsearch#String",
        },
        AlgorithmicStemming: {
          target: "com.amazonaws.cloudsearch#AlgorithmicStemming",
        },
      },
    },
    "com.amazonaws.cloudsearch#String": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#AlgorithmicStemming": {
      type: "enum",
    },
    "com.amazonaws.cloudsearch#AnalysisSchemeStatus": {
      type: "structure",
      members: {
        Options: {
          target: "com.amazonaws.cloudsearch#AnalysisScheme",
        },
        Status: {
          target: "com.amazonaws.cloudsearch#OptionStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#OptionStatus": {
      type: "structure",
      members: {
        CreationDate: {
          target: "com.amazonaws.cloudsearch#UpdateTimestamp",
        },
        UpdateDate: {
          target: "com.amazonaws.cloudsearch#UpdateTimestamp",
        },
        UpdateVersion: {
          target: "com.amazonaws.cloudsearch#UIntValue",
        },
        State: {
          target: "com.amazonaws.cloudsearch#OptionState",
        },
        PendingDeletion: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#UpdateTimestamp": {
      type: "timestamp",
    },
    "com.amazonaws.cloudsearch#UIntValue": {
      type: "integer",
    },
    "com.amazonaws.cloudsearch#OptionState": {
      type: "enum",
    },
    "com.amazonaws.cloudsearch#Expression": {
      type: "structure",
      members: {
        ExpressionName: {
          target: "com.amazonaws.cloudsearch#StandardName",
        },
        ExpressionValue: {
          target: "com.amazonaws.cloudsearch#ExpressionValue",
        },
      },
    },
    "com.amazonaws.cloudsearch#ExpressionValue": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#ExpressionStatus": {
      type: "structure",
      members: {
        Options: {
          target: "com.amazonaws.cloudsearch#Expression",
        },
        Status: {
          target: "com.amazonaws.cloudsearch#OptionStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#IndexField": {
      type: "structure",
      members: {
        IndexFieldName: {
          target: "com.amazonaws.cloudsearch#DynamicFieldName",
        },
        IndexFieldType: {
          target: "com.amazonaws.cloudsearch#IndexFieldType",
        },
        IntOptions: {
          target: "com.amazonaws.cloudsearch#IntOptions",
        },
        DoubleOptions: {
          target: "com.amazonaws.cloudsearch#DoubleOptions",
        },
        LiteralOptions: {
          target: "com.amazonaws.cloudsearch#LiteralOptions",
        },
        TextOptions: {
          target: "com.amazonaws.cloudsearch#TextOptions",
        },
        DateOptions: {
          target: "com.amazonaws.cloudsearch#DateOptions",
        },
        LatLonOptions: {
          target: "com.amazonaws.cloudsearch#LatLonOptions",
        },
        IntArrayOptions: {
          target: "com.amazonaws.cloudsearch#IntArrayOptions",
        },
        DoubleArrayOptions: {
          target: "com.amazonaws.cloudsearch#DoubleArrayOptions",
        },
        LiteralArrayOptions: {
          target: "com.amazonaws.cloudsearch#LiteralArrayOptions",
        },
        TextArrayOptions: {
          target: "com.amazonaws.cloudsearch#TextArrayOptions",
        },
        DateArrayOptions: {
          target: "com.amazonaws.cloudsearch#DateArrayOptions",
        },
      },
    },
    "com.amazonaws.cloudsearch#DynamicFieldName": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#IndexFieldType": {
      type: "enum",
    },
    "com.amazonaws.cloudsearch#IntOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#Long",
        },
        SourceField: {
          target: "com.amazonaws.cloudsearch#FieldName",
        },
        FacetEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SearchEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SortEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#Long": {
      type: "long",
    },
    "com.amazonaws.cloudsearch#DoubleOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#Double",
        },
        SourceField: {
          target: "com.amazonaws.cloudsearch#FieldName",
        },
        FacetEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SearchEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SortEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#Double": {
      type: "double",
    },
    "com.amazonaws.cloudsearch#LiteralOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#FieldValue",
        },
        SourceField: {
          target: "com.amazonaws.cloudsearch#FieldName",
        },
        FacetEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SearchEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SortEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#FieldValue": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#TextOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#FieldValue",
        },
        SourceField: {
          target: "com.amazonaws.cloudsearch#FieldName",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SortEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        HighlightEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        AnalysisScheme: {
          target: "com.amazonaws.cloudsearch#Word",
        },
      },
    },
    "com.amazonaws.cloudsearch#Word": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#DateOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#FieldValue",
        },
        SourceField: {
          target: "com.amazonaws.cloudsearch#FieldName",
        },
        FacetEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SearchEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SortEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#LatLonOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#FieldValue",
        },
        SourceField: {
          target: "com.amazonaws.cloudsearch#FieldName",
        },
        FacetEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SearchEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SortEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#IntArrayOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#Long",
        },
        SourceFields: {
          target: "com.amazonaws.cloudsearch#FieldNameCommaList",
        },
        FacetEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SearchEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#FieldNameCommaList": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#DoubleArrayOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#Double",
        },
        SourceFields: {
          target: "com.amazonaws.cloudsearch#FieldNameCommaList",
        },
        FacetEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SearchEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#LiteralArrayOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#FieldValue",
        },
        SourceFields: {
          target: "com.amazonaws.cloudsearch#FieldNameCommaList",
        },
        FacetEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SearchEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#TextArrayOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#FieldValue",
        },
        SourceFields: {
          target: "com.amazonaws.cloudsearch#FieldNameCommaList",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        HighlightEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        AnalysisScheme: {
          target: "com.amazonaws.cloudsearch#Word",
        },
      },
    },
    "com.amazonaws.cloudsearch#DateArrayOptions": {
      type: "structure",
      members: {
        DefaultValue: {
          target: "com.amazonaws.cloudsearch#FieldValue",
        },
        SourceFields: {
          target: "com.amazonaws.cloudsearch#FieldNameCommaList",
        },
        FacetEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        SearchEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        ReturnEnabled: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
      },
    },
    "com.amazonaws.cloudsearch#IndexFieldStatus": {
      type: "structure",
      members: {
        Options: {
          target: "com.amazonaws.cloudsearch#IndexField",
        },
        Status: {
          target: "com.amazonaws.cloudsearch#OptionStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#Suggester": {
      type: "structure",
      members: {
        SuggesterName: {
          target: "com.amazonaws.cloudsearch#StandardName",
        },
        DocumentSuggesterOptions: {
          target: "com.amazonaws.cloudsearch#DocumentSuggesterOptions",
        },
      },
    },
    "com.amazonaws.cloudsearch#DocumentSuggesterOptions": {
      type: "structure",
      members: {
        SourceField: {
          target: "com.amazonaws.cloudsearch#FieldName",
        },
        FuzzyMatching: {
          target: "com.amazonaws.cloudsearch#SuggesterFuzzyMatching",
        },
        SortExpression: {
          target: "com.amazonaws.cloudsearch#String",
        },
      },
    },
    "com.amazonaws.cloudsearch#SuggesterFuzzyMatching": {
      type: "enum",
    },
    "com.amazonaws.cloudsearch#SuggesterStatus": {
      type: "structure",
      members: {
        Options: {
          target: "com.amazonaws.cloudsearch#Suggester",
        },
        Status: {
          target: "com.amazonaws.cloudsearch#OptionStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#StandardNameList": {
      type: "list",
      member: {
        target: "com.amazonaws.cloudsearch#StandardName",
      },
    },
    "com.amazonaws.cloudsearch#AnalysisSchemeStatusList": {
      type: "list",
      member: {
        target: "com.amazonaws.cloudsearch#AnalysisSchemeStatus",
      },
    },
    "com.amazonaws.cloudsearch#AvailabilityOptionsStatus": {
      type: "structure",
      members: {
        Options: {
          target: "com.amazonaws.cloudsearch#MultiAZ",
        },
        Status: {
          target: "com.amazonaws.cloudsearch#OptionStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#MultiAZ": {
      type: "boolean",
    },
    "com.amazonaws.cloudsearch#DomainEndpointOptionsStatus": {
      type: "structure",
      members: {
        Options: {
          target: "com.amazonaws.cloudsearch#DomainEndpointOptions",
        },
        Status: {
          target: "com.amazonaws.cloudsearch#OptionStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#DomainEndpointOptions": {
      type: "structure",
      members: {
        EnforceHTTPS: {
          target: "com.amazonaws.cloudsearch#Boolean",
        },
        TLSSecurityPolicy: {
          target: "com.amazonaws.cloudsearch#TLSSecurityPolicy",
        },
      },
    },
    "com.amazonaws.cloudsearch#TLSSecurityPolicy": {
      type: "enum",
    },
    "com.amazonaws.cloudsearch#DomainNameList": {
      type: "list",
      member: {
        target: "com.amazonaws.cloudsearch#DomainName",
      },
    },
    "com.amazonaws.cloudsearch#DomainStatusList": {
      type: "list",
      member: {
        target: "com.amazonaws.cloudsearch#DomainStatus",
      },
    },
    "com.amazonaws.cloudsearch#ExpressionStatusList": {
      type: "list",
      member: {
        target: "com.amazonaws.cloudsearch#ExpressionStatus",
      },
    },
    "com.amazonaws.cloudsearch#DynamicFieldNameList": {
      type: "list",
      member: {
        target: "com.amazonaws.cloudsearch#DynamicFieldName",
      },
    },
    "com.amazonaws.cloudsearch#IndexFieldStatusList": {
      type: "list",
      member: {
        target: "com.amazonaws.cloudsearch#IndexFieldStatus",
      },
    },
    "com.amazonaws.cloudsearch#ScalingParametersStatus": {
      type: "structure",
      members: {
        Options: {
          target: "com.amazonaws.cloudsearch#ScalingParameters",
        },
        Status: {
          target: "com.amazonaws.cloudsearch#OptionStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#ScalingParameters": {
      type: "structure",
      members: {
        DesiredInstanceType: {
          target: "com.amazonaws.cloudsearch#PartitionInstanceType",
        },
        DesiredReplicationCount: {
          target: "com.amazonaws.cloudsearch#UIntValue",
        },
        DesiredPartitionCount: {
          target: "com.amazonaws.cloudsearch#UIntValue",
        },
      },
    },
    "com.amazonaws.cloudsearch#PartitionInstanceType": {
      type: "enum",
    },
    "com.amazonaws.cloudsearch#AccessPoliciesStatus": {
      type: "structure",
      members: {
        Options: {
          target: "com.amazonaws.cloudsearch#PolicyDocument",
        },
        Status: {
          target: "com.amazonaws.cloudsearch#OptionStatus",
        },
      },
    },
    "com.amazonaws.cloudsearch#PolicyDocument": {
      type: "string",
    },
    "com.amazonaws.cloudsearch#SuggesterStatusList": {
      type: "list",
      member: {
        target: "com.amazonaws.cloudsearch#SuggesterStatus",
      },
    },
    "com.amazonaws.cloudsearch#DomainNameMap": {
      type: "map",
      key: {
        target: "com.amazonaws.cloudsearch#DomainName",
      },
      value: {
        target: "com.amazonaws.cloudsearch#APIVersion",
      },
    },
    "com.amazonaws.cloudsearch#APIVersion": {
      type: "string",
    },
  },
} as const;
