// Auto-generated by generate-awsquery-metadata.ts. DO NOT EDIT BY HAND.

export type ShapeKind =
  | "structure"
  | "list"
  | "map"
  | "string"
  | "integer"
  | "boolean"
  | "timestamp"
  | "blob"
  | "enum"
  | "double"
  | "long"
  | "float"
  | "union";

export interface MemberMeta {
  target: string;
  locationName?: string;
  queryName?: string;
  flattened?: boolean;
  timestampFormat?: "iso8601" | "epoch-seconds" | "http-date";
}

export interface ShapeMeta {
  type: ShapeKind;
  xmlName?: string;
  members?: Record<string, MemberMeta>;
  member?: MemberMeta;
  key?: MemberMeta;
  value?: MemberMeta;
  enum?: string[];
  flattened?: boolean;
}

export interface OperationMeta {
  name: string;
  input?: string;
  output?: string;
  responseWrapper?: string;
}

export interface AwsQueryServiceMeta {
  serviceId: string;
  serviceName: string;
  version: string;
  endpointPrefix?: string;
  operations: Record<string, OperationMeta>;
  shapes: Record<string, ShapeMeta>;
}

export const metadata: AwsQueryServiceMeta = {
  serviceId: "DocDB",
  serviceName: "DocDB",
  version: "2014-10-31",
  endpointPrefix: "rds",
  operations: {
    AddSourceIdentifierToSubscription: {
      name: "AddSourceIdentifierToSubscription",
      input: "com.amazonaws.docdb#AddSourceIdentifierToSubscriptionMessage",
      output: "com.amazonaws.docdb#AddSourceIdentifierToSubscriptionResult",
      responseWrapper: "AddSourceIdentifierToSubscriptionResponse",
    },
    AddTagsToResource: {
      name: "AddTagsToResource",
      input: "com.amazonaws.docdb#AddTagsToResourceMessage",
      output: "smithy.api#Unit",
      responseWrapper: "AddTagsToResourceResponse",
    },
    ApplyPendingMaintenanceAction: {
      name: "ApplyPendingMaintenanceAction",
      input: "com.amazonaws.docdb#ApplyPendingMaintenanceActionMessage",
      output: "com.amazonaws.docdb#ApplyPendingMaintenanceActionResult",
      responseWrapper: "ApplyPendingMaintenanceActionResponse",
    },
    CopyDBClusterParameterGroup: {
      name: "CopyDBClusterParameterGroup",
      input: "com.amazonaws.docdb#CopyDBClusterParameterGroupMessage",
      output: "com.amazonaws.docdb#CopyDBClusterParameterGroupResult",
      responseWrapper: "CopyDBClusterParameterGroupResponse",
    },
    CopyDBClusterSnapshot: {
      name: "CopyDBClusterSnapshot",
      input: "com.amazonaws.docdb#CopyDBClusterSnapshotMessage",
      output: "com.amazonaws.docdb#CopyDBClusterSnapshotResult",
      responseWrapper: "CopyDBClusterSnapshotResponse",
    },
    CreateDBCluster: {
      name: "CreateDBCluster",
      input: "com.amazonaws.docdb#CreateDBClusterMessage",
      output: "com.amazonaws.docdb#CreateDBClusterResult",
      responseWrapper: "CreateDBClusterResponse",
    },
    CreateDBClusterParameterGroup: {
      name: "CreateDBClusterParameterGroup",
      input: "com.amazonaws.docdb#CreateDBClusterParameterGroupMessage",
      output: "com.amazonaws.docdb#CreateDBClusterParameterGroupResult",
      responseWrapper: "CreateDBClusterParameterGroupResponse",
    },
    CreateDBClusterSnapshot: {
      name: "CreateDBClusterSnapshot",
      input: "com.amazonaws.docdb#CreateDBClusterSnapshotMessage",
      output: "com.amazonaws.docdb#CreateDBClusterSnapshotResult",
      responseWrapper: "CreateDBClusterSnapshotResponse",
    },
    CreateDBInstance: {
      name: "CreateDBInstance",
      input: "com.amazonaws.docdb#CreateDBInstanceMessage",
      output: "com.amazonaws.docdb#CreateDBInstanceResult",
      responseWrapper: "CreateDBInstanceResponse",
    },
    CreateDBSubnetGroup: {
      name: "CreateDBSubnetGroup",
      input: "com.amazonaws.docdb#CreateDBSubnetGroupMessage",
      output: "com.amazonaws.docdb#CreateDBSubnetGroupResult",
      responseWrapper: "CreateDBSubnetGroupResponse",
    },
    CreateEventSubscription: {
      name: "CreateEventSubscription",
      input: "com.amazonaws.docdb#CreateEventSubscriptionMessage",
      output: "com.amazonaws.docdb#CreateEventSubscriptionResult",
      responseWrapper: "CreateEventSubscriptionResponse",
    },
    CreateGlobalCluster: {
      name: "CreateGlobalCluster",
      input: "com.amazonaws.docdb#CreateGlobalClusterMessage",
      output: "com.amazonaws.docdb#CreateGlobalClusterResult",
      responseWrapper: "CreateGlobalClusterResponse",
    },
    DeleteDBCluster: {
      name: "DeleteDBCluster",
      input: "com.amazonaws.docdb#DeleteDBClusterMessage",
      output: "com.amazonaws.docdb#DeleteDBClusterResult",
      responseWrapper: "DeleteDBClusterResponse",
    },
    DeleteDBClusterParameterGroup: {
      name: "DeleteDBClusterParameterGroup",
      input: "com.amazonaws.docdb#DeleteDBClusterParameterGroupMessage",
      output: "smithy.api#Unit",
      responseWrapper: "DeleteDBClusterParameterGroupResponse",
    },
    DeleteDBClusterSnapshot: {
      name: "DeleteDBClusterSnapshot",
      input: "com.amazonaws.docdb#DeleteDBClusterSnapshotMessage",
      output: "com.amazonaws.docdb#DeleteDBClusterSnapshotResult",
      responseWrapper: "DeleteDBClusterSnapshotResponse",
    },
    DeleteDBInstance: {
      name: "DeleteDBInstance",
      input: "com.amazonaws.docdb#DeleteDBInstanceMessage",
      output: "com.amazonaws.docdb#DeleteDBInstanceResult",
      responseWrapper: "DeleteDBInstanceResponse",
    },
    DeleteDBSubnetGroup: {
      name: "DeleteDBSubnetGroup",
      input: "com.amazonaws.docdb#DeleteDBSubnetGroupMessage",
      output: "smithy.api#Unit",
      responseWrapper: "DeleteDBSubnetGroupResponse",
    },
    DeleteEventSubscription: {
      name: "DeleteEventSubscription",
      input: "com.amazonaws.docdb#DeleteEventSubscriptionMessage",
      output: "com.amazonaws.docdb#DeleteEventSubscriptionResult",
      responseWrapper: "DeleteEventSubscriptionResponse",
    },
    DeleteGlobalCluster: {
      name: "DeleteGlobalCluster",
      input: "com.amazonaws.docdb#DeleteGlobalClusterMessage",
      output: "com.amazonaws.docdb#DeleteGlobalClusterResult",
      responseWrapper: "DeleteGlobalClusterResponse",
    },
    DescribeCertificates: {
      name: "DescribeCertificates",
      input: "com.amazonaws.docdb#DescribeCertificatesMessage",
      output: "com.amazonaws.docdb#CertificateMessage",
      responseWrapper: "DescribeCertificatesResponse",
    },
    DescribeDBClusterParameterGroups: {
      name: "DescribeDBClusterParameterGroups",
      input: "com.amazonaws.docdb#DescribeDBClusterParameterGroupsMessage",
      output: "com.amazonaws.docdb#DBClusterParameterGroupsMessage",
      responseWrapper: "DescribeDBClusterParameterGroupsResponse",
    },
    DescribeDBClusterParameters: {
      name: "DescribeDBClusterParameters",
      input: "com.amazonaws.docdb#DescribeDBClusterParametersMessage",
      output: "com.amazonaws.docdb#DBClusterParameterGroupDetails",
      responseWrapper: "DescribeDBClusterParametersResponse",
    },
    DescribeDBClusterSnapshotAttributes: {
      name: "DescribeDBClusterSnapshotAttributes",
      input: "com.amazonaws.docdb#DescribeDBClusterSnapshotAttributesMessage",
      output: "com.amazonaws.docdb#DescribeDBClusterSnapshotAttributesResult",
      responseWrapper: "DescribeDBClusterSnapshotAttributesResponse",
    },
    DescribeDBClusterSnapshots: {
      name: "DescribeDBClusterSnapshots",
      input: "com.amazonaws.docdb#DescribeDBClusterSnapshotsMessage",
      output: "com.amazonaws.docdb#DBClusterSnapshotMessage",
      responseWrapper: "DescribeDBClusterSnapshotsResponse",
    },
    DescribeDBClusters: {
      name: "DescribeDBClusters",
      input: "com.amazonaws.docdb#DescribeDBClustersMessage",
      output: "com.amazonaws.docdb#DBClusterMessage",
      responseWrapper: "DescribeDBClustersResponse",
    },
    DescribeDBEngineVersions: {
      name: "DescribeDBEngineVersions",
      input: "com.amazonaws.docdb#DescribeDBEngineVersionsMessage",
      output: "com.amazonaws.docdb#DBEngineVersionMessage",
      responseWrapper: "DescribeDBEngineVersionsResponse",
    },
    DescribeDBInstances: {
      name: "DescribeDBInstances",
      input: "com.amazonaws.docdb#DescribeDBInstancesMessage",
      output: "com.amazonaws.docdb#DBInstanceMessage",
      responseWrapper: "DescribeDBInstancesResponse",
    },
    DescribeDBSubnetGroups: {
      name: "DescribeDBSubnetGroups",
      input: "com.amazonaws.docdb#DescribeDBSubnetGroupsMessage",
      output: "com.amazonaws.docdb#DBSubnetGroupMessage",
      responseWrapper: "DescribeDBSubnetGroupsResponse",
    },
    DescribeEngineDefaultClusterParameters: {
      name: "DescribeEngineDefaultClusterParameters",
      input:
        "com.amazonaws.docdb#DescribeEngineDefaultClusterParametersMessage",
      output:
        "com.amazonaws.docdb#DescribeEngineDefaultClusterParametersResult",
      responseWrapper: "DescribeEngineDefaultClusterParametersResponse",
    },
    DescribeEventCategories: {
      name: "DescribeEventCategories",
      input: "com.amazonaws.docdb#DescribeEventCategoriesMessage",
      output: "com.amazonaws.docdb#EventCategoriesMessage",
      responseWrapper: "DescribeEventCategoriesResponse",
    },
    DescribeEventSubscriptions: {
      name: "DescribeEventSubscriptions",
      input: "com.amazonaws.docdb#DescribeEventSubscriptionsMessage",
      output: "com.amazonaws.docdb#EventSubscriptionsMessage",
      responseWrapper: "DescribeEventSubscriptionsResponse",
    },
    DescribeEvents: {
      name: "DescribeEvents",
      input: "com.amazonaws.docdb#DescribeEventsMessage",
      output: "com.amazonaws.docdb#EventsMessage",
      responseWrapper: "DescribeEventsResponse",
    },
    DescribeGlobalClusters: {
      name: "DescribeGlobalClusters",
      input: "com.amazonaws.docdb#DescribeGlobalClustersMessage",
      output: "com.amazonaws.docdb#GlobalClustersMessage",
      responseWrapper: "DescribeGlobalClustersResponse",
    },
    DescribeOrderableDBInstanceOptions: {
      name: "DescribeOrderableDBInstanceOptions",
      input: "com.amazonaws.docdb#DescribeOrderableDBInstanceOptionsMessage",
      output: "com.amazonaws.docdb#OrderableDBInstanceOptionsMessage",
      responseWrapper: "DescribeOrderableDBInstanceOptionsResponse",
    },
    DescribePendingMaintenanceActions: {
      name: "DescribePendingMaintenanceActions",
      input: "com.amazonaws.docdb#DescribePendingMaintenanceActionsMessage",
      output: "com.amazonaws.docdb#PendingMaintenanceActionsMessage",
      responseWrapper: "DescribePendingMaintenanceActionsResponse",
    },
    FailoverDBCluster: {
      name: "FailoverDBCluster",
      input: "com.amazonaws.docdb#FailoverDBClusterMessage",
      output: "com.amazonaws.docdb#FailoverDBClusterResult",
      responseWrapper: "FailoverDBClusterResponse",
    },
    FailoverGlobalCluster: {
      name: "FailoverGlobalCluster",
      input: "com.amazonaws.docdb#FailoverGlobalClusterMessage",
      output: "com.amazonaws.docdb#FailoverGlobalClusterResult",
      responseWrapper: "FailoverGlobalClusterResponse",
    },
    ListTagsForResource: {
      name: "ListTagsForResource",
      input: "com.amazonaws.docdb#ListTagsForResourceMessage",
      output: "com.amazonaws.docdb#TagListMessage",
      responseWrapper: "ListTagsForResourceResponse",
    },
    ModifyDBCluster: {
      name: "ModifyDBCluster",
      input: "com.amazonaws.docdb#ModifyDBClusterMessage",
      output: "com.amazonaws.docdb#ModifyDBClusterResult",
      responseWrapper: "ModifyDBClusterResponse",
    },
    ModifyDBClusterParameterGroup: {
      name: "ModifyDBClusterParameterGroup",
      input: "com.amazonaws.docdb#ModifyDBClusterParameterGroupMessage",
      output: "com.amazonaws.docdb#DBClusterParameterGroupNameMessage",
      responseWrapper: "ModifyDBClusterParameterGroupResponse",
    },
    ModifyDBClusterSnapshotAttribute: {
      name: "ModifyDBClusterSnapshotAttribute",
      input: "com.amazonaws.docdb#ModifyDBClusterSnapshotAttributeMessage",
      output: "com.amazonaws.docdb#ModifyDBClusterSnapshotAttributeResult",
      responseWrapper: "ModifyDBClusterSnapshotAttributeResponse",
    },
    ModifyDBInstance: {
      name: "ModifyDBInstance",
      input: "com.amazonaws.docdb#ModifyDBInstanceMessage",
      output: "com.amazonaws.docdb#ModifyDBInstanceResult",
      responseWrapper: "ModifyDBInstanceResponse",
    },
    ModifyDBSubnetGroup: {
      name: "ModifyDBSubnetGroup",
      input: "com.amazonaws.docdb#ModifyDBSubnetGroupMessage",
      output: "com.amazonaws.docdb#ModifyDBSubnetGroupResult",
      responseWrapper: "ModifyDBSubnetGroupResponse",
    },
    ModifyEventSubscription: {
      name: "ModifyEventSubscription",
      input: "com.amazonaws.docdb#ModifyEventSubscriptionMessage",
      output: "com.amazonaws.docdb#ModifyEventSubscriptionResult",
      responseWrapper: "ModifyEventSubscriptionResponse",
    },
    ModifyGlobalCluster: {
      name: "ModifyGlobalCluster",
      input: "com.amazonaws.docdb#ModifyGlobalClusterMessage",
      output: "com.amazonaws.docdb#ModifyGlobalClusterResult",
      responseWrapper: "ModifyGlobalClusterResponse",
    },
    RebootDBInstance: {
      name: "RebootDBInstance",
      input: "com.amazonaws.docdb#RebootDBInstanceMessage",
      output: "com.amazonaws.docdb#RebootDBInstanceResult",
      responseWrapper: "RebootDBInstanceResponse",
    },
    RemoveFromGlobalCluster: {
      name: "RemoveFromGlobalCluster",
      input: "com.amazonaws.docdb#RemoveFromGlobalClusterMessage",
      output: "com.amazonaws.docdb#RemoveFromGlobalClusterResult",
      responseWrapper: "RemoveFromGlobalClusterResponse",
    },
    RemoveSourceIdentifierFromSubscription: {
      name: "RemoveSourceIdentifierFromSubscription",
      input:
        "com.amazonaws.docdb#RemoveSourceIdentifierFromSubscriptionMessage",
      output:
        "com.amazonaws.docdb#RemoveSourceIdentifierFromSubscriptionResult",
      responseWrapper: "RemoveSourceIdentifierFromSubscriptionResponse",
    },
    RemoveTagsFromResource: {
      name: "RemoveTagsFromResource",
      input: "com.amazonaws.docdb#RemoveTagsFromResourceMessage",
      output: "smithy.api#Unit",
      responseWrapper: "RemoveTagsFromResourceResponse",
    },
    ResetDBClusterParameterGroup: {
      name: "ResetDBClusterParameterGroup",
      input: "com.amazonaws.docdb#ResetDBClusterParameterGroupMessage",
      output: "com.amazonaws.docdb#DBClusterParameterGroupNameMessage",
      responseWrapper: "ResetDBClusterParameterGroupResponse",
    },
    RestoreDBClusterFromSnapshot: {
      name: "RestoreDBClusterFromSnapshot",
      input: "com.amazonaws.docdb#RestoreDBClusterFromSnapshotMessage",
      output: "com.amazonaws.docdb#RestoreDBClusterFromSnapshotResult",
      responseWrapper: "RestoreDBClusterFromSnapshotResponse",
    },
    RestoreDBClusterToPointInTime: {
      name: "RestoreDBClusterToPointInTime",
      input: "com.amazonaws.docdb#RestoreDBClusterToPointInTimeMessage",
      output: "com.amazonaws.docdb#RestoreDBClusterToPointInTimeResult",
      responseWrapper: "RestoreDBClusterToPointInTimeResponse",
    },
    StartDBCluster: {
      name: "StartDBCluster",
      input: "com.amazonaws.docdb#StartDBClusterMessage",
      output: "com.amazonaws.docdb#StartDBClusterResult",
      responseWrapper: "StartDBClusterResponse",
    },
    StopDBCluster: {
      name: "StopDBCluster",
      input: "com.amazonaws.docdb#StopDBClusterMessage",
      output: "com.amazonaws.docdb#StopDBClusterResult",
      responseWrapper: "StopDBClusterResponse",
    },
    SwitchoverGlobalCluster: {
      name: "SwitchoverGlobalCluster",
      input: "com.amazonaws.docdb#SwitchoverGlobalClusterMessage",
      output: "com.amazonaws.docdb#SwitchoverGlobalClusterResult",
      responseWrapper: "SwitchoverGlobalClusterResponse",
    },
  },
  shapes: {
    "com.amazonaws.docdb#AddSourceIdentifierToSubscriptionMessage": {
      type: "structure",
      members: {
        SubscriptionName: {
          target: "com.amazonaws.docdb#String",
        },
        SourceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#AddSourceIdentifierToSubscriptionResult": {
      type: "structure",
      members: {
        EventSubscription: {
          target: "com.amazonaws.docdb#EventSubscription",
        },
      },
    },
    "com.amazonaws.docdb#AddTagsToResourceMessage": {
      type: "structure",
      members: {
        ResourceName: {
          target: "com.amazonaws.docdb#String",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
      },
    },
    "com.amazonaws.docdb#ApplyPendingMaintenanceActionMessage": {
      type: "structure",
      members: {
        ResourceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        ApplyAction: {
          target: "com.amazonaws.docdb#String",
        },
        OptInType: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#ApplyPendingMaintenanceActionResult": {
      type: "structure",
      members: {
        ResourcePendingMaintenanceActions: {
          target: "com.amazonaws.docdb#ResourcePendingMaintenanceActions",
        },
      },
    },
    "com.amazonaws.docdb#CopyDBClusterParameterGroupMessage": {
      type: "structure",
      members: {
        SourceDBClusterParameterGroupIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        TargetDBClusterParameterGroupIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        TargetDBClusterParameterGroupDescription: {
          target: "com.amazonaws.docdb#String",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
      },
    },
    "com.amazonaws.docdb#CopyDBClusterParameterGroupResult": {
      type: "structure",
      members: {
        DBClusterParameterGroup: {
          target: "com.amazonaws.docdb#DBClusterParameterGroup",
        },
      },
    },
    "com.amazonaws.docdb#CopyDBClusterSnapshotMessage": {
      type: "structure",
      members: {
        SourceDBClusterSnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        TargetDBClusterSnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        KmsKeyId: {
          target: "com.amazonaws.docdb#String",
        },
        PreSignedUrl: {
          target: "com.amazonaws.docdb#String",
        },
        CopyTags: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
      },
    },
    "com.amazonaws.docdb#CopyDBClusterSnapshotResult": {
      type: "structure",
      members: {
        DBClusterSnapshot: {
          target: "com.amazonaws.docdb#DBClusterSnapshot",
        },
      },
    },
    "com.amazonaws.docdb#CreateDBClusterMessage": {
      type: "structure",
      members: {
        AvailabilityZones: {
          target: "com.amazonaws.docdb#AvailabilityZones",
        },
        BackupRetentionPeriod: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        VpcSecurityGroupIds: {
          target: "com.amazonaws.docdb#VpcSecurityGroupIdList",
        },
        DBSubnetGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        Port: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        MasterUsername: {
          target: "com.amazonaws.docdb#String",
        },
        MasterUserPassword: {
          target: "com.amazonaws.docdb#String",
        },
        PreferredBackupWindow: {
          target: "com.amazonaws.docdb#String",
        },
        PreferredMaintenanceWindow: {
          target: "com.amazonaws.docdb#String",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
        StorageEncrypted: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        KmsKeyId: {
          target: "com.amazonaws.docdb#String",
        },
        PreSignedUrl: {
          target: "com.amazonaws.docdb#String",
        },
        EnableCloudwatchLogsExports: {
          target: "com.amazonaws.docdb#LogTypeList",
        },
        DeletionProtection: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        GlobalClusterIdentifier: {
          target: "com.amazonaws.docdb#GlobalClusterIdentifier",
        },
        StorageType: {
          target: "com.amazonaws.docdb#String",
        },
        ServerlessV2ScalingConfiguration: {
          target: "com.amazonaws.docdb#ServerlessV2ScalingConfiguration",
        },
        ManageMasterUserPassword: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        MasterUserSecretKmsKeyId: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#CreateDBClusterResult": {
      type: "structure",
      members: {
        DBCluster: {
          target: "com.amazonaws.docdb#DBCluster",
        },
      },
    },
    "com.amazonaws.docdb#CreateDBClusterParameterGroupMessage": {
      type: "structure",
      members: {
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        DBParameterGroupFamily: {
          target: "com.amazonaws.docdb#String",
        },
        Description: {
          target: "com.amazonaws.docdb#String",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
      },
    },
    "com.amazonaws.docdb#CreateDBClusterParameterGroupResult": {
      type: "structure",
      members: {
        DBClusterParameterGroup: {
          target: "com.amazonaws.docdb#DBClusterParameterGroup",
        },
      },
    },
    "com.amazonaws.docdb#CreateDBClusterSnapshotMessage": {
      type: "structure",
      members: {
        DBClusterSnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
      },
    },
    "com.amazonaws.docdb#CreateDBClusterSnapshotResult": {
      type: "structure",
      members: {
        DBClusterSnapshot: {
          target: "com.amazonaws.docdb#DBClusterSnapshot",
        },
      },
    },
    "com.amazonaws.docdb#CreateDBInstanceMessage": {
      type: "structure",
      members: {
        DBInstanceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        DBInstanceClass: {
          target: "com.amazonaws.docdb#String",
        },
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        AvailabilityZone: {
          target: "com.amazonaws.docdb#String",
        },
        PreferredMaintenanceWindow: {
          target: "com.amazonaws.docdb#String",
        },
        AutoMinorVersionUpgrade: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        CopyTagsToSnapshot: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        PromotionTier: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        EnablePerformanceInsights: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        PerformanceInsightsKMSKeyId: {
          target: "com.amazonaws.docdb#String",
        },
        CACertificateIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#CreateDBInstanceResult": {
      type: "structure",
      members: {
        DBInstance: {
          target: "com.amazonaws.docdb#DBInstance",
        },
      },
    },
    "com.amazonaws.docdb#CreateDBSubnetGroupMessage": {
      type: "structure",
      members: {
        DBSubnetGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        DBSubnetGroupDescription: {
          target: "com.amazonaws.docdb#String",
        },
        SubnetIds: {
          target: "com.amazonaws.docdb#SubnetIdentifierList",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
      },
    },
    "com.amazonaws.docdb#CreateDBSubnetGroupResult": {
      type: "structure",
      members: {
        DBSubnetGroup: {
          target: "com.amazonaws.docdb#DBSubnetGroup",
        },
      },
    },
    "com.amazonaws.docdb#CreateEventSubscriptionMessage": {
      type: "structure",
      members: {
        SubscriptionName: {
          target: "com.amazonaws.docdb#String",
        },
        SnsTopicArn: {
          target: "com.amazonaws.docdb#String",
        },
        SourceType: {
          target: "com.amazonaws.docdb#String",
        },
        EventCategories: {
          target: "com.amazonaws.docdb#EventCategoriesList",
        },
        SourceIds: {
          target: "com.amazonaws.docdb#SourceIdsList",
        },
        Enabled: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
      },
    },
    "com.amazonaws.docdb#CreateEventSubscriptionResult": {
      type: "structure",
      members: {
        EventSubscription: {
          target: "com.amazonaws.docdb#EventSubscription",
        },
      },
    },
    "com.amazonaws.docdb#CreateGlobalClusterMessage": {
      type: "structure",
      members: {
        GlobalClusterIdentifier: {
          target: "com.amazonaws.docdb#GlobalClusterIdentifier",
        },
        SourceDBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        DeletionProtection: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        DatabaseName: {
          target: "com.amazonaws.docdb#String",
        },
        StorageEncrypted: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
      },
    },
    "com.amazonaws.docdb#CreateGlobalClusterResult": {
      type: "structure",
      members: {
        GlobalCluster: {
          target: "com.amazonaws.docdb#GlobalCluster",
        },
      },
    },
    "com.amazonaws.docdb#DeleteDBClusterMessage": {
      type: "structure",
      members: {
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        SkipFinalSnapshot: {
          target: "com.amazonaws.docdb#Boolean",
        },
        FinalDBSnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DeleteDBClusterResult": {
      type: "structure",
      members: {
        DBCluster: {
          target: "com.amazonaws.docdb#DBCluster",
        },
      },
    },
    "com.amazonaws.docdb#DeleteDBClusterParameterGroupMessage": {
      type: "structure",
      members: {
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DeleteDBClusterSnapshotMessage": {
      type: "structure",
      members: {
        DBClusterSnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DeleteDBClusterSnapshotResult": {
      type: "structure",
      members: {
        DBClusterSnapshot: {
          target: "com.amazonaws.docdb#DBClusterSnapshot",
        },
      },
    },
    "com.amazonaws.docdb#DeleteDBInstanceMessage": {
      type: "structure",
      members: {
        DBInstanceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DeleteDBInstanceResult": {
      type: "structure",
      members: {
        DBInstance: {
          target: "com.amazonaws.docdb#DBInstance",
        },
      },
    },
    "com.amazonaws.docdb#DeleteDBSubnetGroupMessage": {
      type: "structure",
      members: {
        DBSubnetGroupName: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DeleteEventSubscriptionMessage": {
      type: "structure",
      members: {
        SubscriptionName: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DeleteEventSubscriptionResult": {
      type: "structure",
      members: {
        EventSubscription: {
          target: "com.amazonaws.docdb#EventSubscription",
        },
      },
    },
    "com.amazonaws.docdb#DeleteGlobalClusterMessage": {
      type: "structure",
      members: {
        GlobalClusterIdentifier: {
          target: "com.amazonaws.docdb#GlobalClusterIdentifier",
        },
      },
    },
    "com.amazonaws.docdb#DeleteGlobalClusterResult": {
      type: "structure",
      members: {
        GlobalCluster: {
          target: "com.amazonaws.docdb#GlobalCluster",
        },
      },
    },
    "com.amazonaws.docdb#DescribeCertificatesMessage": {
      type: "structure",
      members: {
        CertificateIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#CertificateMessage": {
      type: "structure",
      members: {
        Certificates: {
          target: "com.amazonaws.docdb#CertificateList",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DescribeDBClusterParameterGroupsMessage": {
      type: "structure",
      members: {
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DBClusterParameterGroupsMessage": {
      type: "structure",
      members: {
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterParameterGroups: {
          target: "com.amazonaws.docdb#DBClusterParameterGroupList",
        },
      },
    },
    "com.amazonaws.docdb#DescribeDBClusterParametersMessage": {
      type: "structure",
      members: {
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        Source: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DBClusterParameterGroupDetails": {
      type: "structure",
      members: {
        Parameters: {
          target: "com.amazonaws.docdb#ParametersList",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DescribeDBClusterSnapshotAttributesMessage": {
      type: "structure",
      members: {
        DBClusterSnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DescribeDBClusterSnapshotAttributesResult": {
      type: "structure",
      members: {
        DBClusterSnapshotAttributesResult: {
          target: "com.amazonaws.docdb#DBClusterSnapshotAttributesResult",
        },
      },
    },
    "com.amazonaws.docdb#DescribeDBClusterSnapshotsMessage": {
      type: "structure",
      members: {
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterSnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        SnapshotType: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        IncludeShared: {
          target: "com.amazonaws.docdb#Boolean",
        },
        IncludePublic: {
          target: "com.amazonaws.docdb#Boolean",
        },
      },
    },
    "com.amazonaws.docdb#DBClusterSnapshotMessage": {
      type: "structure",
      members: {
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterSnapshots: {
          target: "com.amazonaws.docdb#DBClusterSnapshotList",
        },
      },
    },
    "com.amazonaws.docdb#DescribeDBClustersMessage": {
      type: "structure",
      members: {
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DBClusterMessage": {
      type: "structure",
      members: {
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusters: {
          target: "com.amazonaws.docdb#DBClusterList",
        },
      },
    },
    "com.amazonaws.docdb#DescribeDBEngineVersionsMessage": {
      type: "structure",
      members: {
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        DBParameterGroupFamily: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        DefaultOnly: {
          target: "com.amazonaws.docdb#Boolean",
        },
        ListSupportedCharacterSets: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        ListSupportedTimezones: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
      },
    },
    "com.amazonaws.docdb#DBEngineVersionMessage": {
      type: "structure",
      members: {
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        DBEngineVersions: {
          target: "com.amazonaws.docdb#DBEngineVersionList",
        },
      },
    },
    "com.amazonaws.docdb#DescribeDBInstancesMessage": {
      type: "structure",
      members: {
        DBInstanceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DBInstanceMessage": {
      type: "structure",
      members: {
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        DBInstances: {
          target: "com.amazonaws.docdb#DBInstanceList",
        },
      },
    },
    "com.amazonaws.docdb#DescribeDBSubnetGroupsMessage": {
      type: "structure",
      members: {
        DBSubnetGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DBSubnetGroupMessage": {
      type: "structure",
      members: {
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        DBSubnetGroups: {
          target: "com.amazonaws.docdb#DBSubnetGroups",
        },
      },
    },
    "com.amazonaws.docdb#DescribeEngineDefaultClusterParametersMessage": {
      type: "structure",
      members: {
        DBParameterGroupFamily: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DescribeEngineDefaultClusterParametersResult": {
      type: "structure",
      members: {
        EngineDefaults: {
          target: "com.amazonaws.docdb#EngineDefaults",
        },
      },
    },
    "com.amazonaws.docdb#DescribeEventCategoriesMessage": {
      type: "structure",
      members: {
        SourceType: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
      },
    },
    "com.amazonaws.docdb#EventCategoriesMessage": {
      type: "structure",
      members: {
        EventCategoriesMapList: {
          target: "com.amazonaws.docdb#EventCategoriesMapList",
        },
      },
    },
    "com.amazonaws.docdb#DescribeEventSubscriptionsMessage": {
      type: "structure",
      members: {
        SubscriptionName: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#EventSubscriptionsMessage": {
      type: "structure",
      members: {
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        EventSubscriptionsList: {
          target: "com.amazonaws.docdb#EventSubscriptionsList",
        },
      },
    },
    "com.amazonaws.docdb#DescribeEventsMessage": {
      type: "structure",
      members: {
        SourceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        SourceType: {
          target: "com.amazonaws.docdb#SourceType",
        },
        StartTime: {
          target: "com.amazonaws.docdb#TStamp",
        },
        EndTime: {
          target: "com.amazonaws.docdb#TStamp",
        },
        Duration: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        EventCategories: {
          target: "com.amazonaws.docdb#EventCategoriesList",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#EventsMessage": {
      type: "structure",
      members: {
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        Events: {
          target: "com.amazonaws.docdb#EventList",
        },
      },
    },
    "com.amazonaws.docdb#DescribeGlobalClustersMessage": {
      type: "structure",
      members: {
        GlobalClusterIdentifier: {
          target: "com.amazonaws.docdb#GlobalClusterIdentifier",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#GlobalClustersMessage": {
      type: "structure",
      members: {
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        GlobalClusters: {
          target: "com.amazonaws.docdb#GlobalClusterList",
        },
      },
    },
    "com.amazonaws.docdb#DescribeOrderableDBInstanceOptionsMessage": {
      type: "structure",
      members: {
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        DBInstanceClass: {
          target: "com.amazonaws.docdb#String",
        },
        LicenseModel: {
          target: "com.amazonaws.docdb#String",
        },
        Vpc: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#OrderableDBInstanceOptionsMessage": {
      type: "structure",
      members: {
        OrderableDBInstanceOptions: {
          target: "com.amazonaws.docdb#OrderableDBInstanceOptionsList",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DescribePendingMaintenanceActionsMessage": {
      type: "structure",
      members: {
        ResourceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        MaxRecords: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
      },
    },
    "com.amazonaws.docdb#PendingMaintenanceActionsMessage": {
      type: "structure",
      members: {
        PendingMaintenanceActions: {
          target: "com.amazonaws.docdb#PendingMaintenanceActions",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#FailoverDBClusterMessage": {
      type: "structure",
      members: {
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        TargetDBInstanceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#FailoverDBClusterResult": {
      type: "structure",
      members: {
        DBCluster: {
          target: "com.amazonaws.docdb#DBCluster",
        },
      },
    },
    "com.amazonaws.docdb#FailoverGlobalClusterMessage": {
      type: "structure",
      members: {
        GlobalClusterIdentifier: {
          target: "com.amazonaws.docdb#GlobalClusterIdentifier",
        },
        TargetDbClusterIdentifier: {
          target: "com.amazonaws.docdb#DBClusterIdentifier",
        },
        AllowDataLoss: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        Switchover: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
      },
    },
    "com.amazonaws.docdb#FailoverGlobalClusterResult": {
      type: "structure",
      members: {
        GlobalCluster: {
          target: "com.amazonaws.docdb#GlobalCluster",
        },
      },
    },
    "com.amazonaws.docdb#ListTagsForResourceMessage": {
      type: "structure",
      members: {
        ResourceName: {
          target: "com.amazonaws.docdb#String",
        },
        Filters: {
          target: "com.amazonaws.docdb#FilterList",
        },
      },
    },
    "com.amazonaws.docdb#TagListMessage": {
      type: "structure",
      members: {
        TagList: {
          target: "com.amazonaws.docdb#TagList",
        },
      },
    },
    "com.amazonaws.docdb#ModifyDBClusterMessage": {
      type: "structure",
      members: {
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        NewDBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        ApplyImmediately: {
          target: "com.amazonaws.docdb#Boolean",
        },
        BackupRetentionPeriod: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        VpcSecurityGroupIds: {
          target: "com.amazonaws.docdb#VpcSecurityGroupIdList",
        },
        Port: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        MasterUserPassword: {
          target: "com.amazonaws.docdb#String",
        },
        PreferredBackupWindow: {
          target: "com.amazonaws.docdb#String",
        },
        PreferredMaintenanceWindow: {
          target: "com.amazonaws.docdb#String",
        },
        CloudwatchLogsExportConfiguration: {
          target: "com.amazonaws.docdb#CloudwatchLogsExportConfiguration",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        AllowMajorVersionUpgrade: {
          target: "com.amazonaws.docdb#Boolean",
        },
        DeletionProtection: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        StorageType: {
          target: "com.amazonaws.docdb#String",
        },
        ServerlessV2ScalingConfiguration: {
          target: "com.amazonaws.docdb#ServerlessV2ScalingConfiguration",
        },
        ManageMasterUserPassword: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        MasterUserSecretKmsKeyId: {
          target: "com.amazonaws.docdb#String",
        },
        RotateMasterUserPassword: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
      },
    },
    "com.amazonaws.docdb#ModifyDBClusterResult": {
      type: "structure",
      members: {
        DBCluster: {
          target: "com.amazonaws.docdb#DBCluster",
        },
      },
    },
    "com.amazonaws.docdb#ModifyDBClusterParameterGroupMessage": {
      type: "structure",
      members: {
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        Parameters: {
          target: "com.amazonaws.docdb#ParametersList",
        },
      },
    },
    "com.amazonaws.docdb#DBClusterParameterGroupNameMessage": {
      type: "structure",
      members: {
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#ModifyDBClusterSnapshotAttributeMessage": {
      type: "structure",
      members: {
        DBClusterSnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        AttributeName: {
          target: "com.amazonaws.docdb#String",
        },
        ValuesToAdd: {
          target: "com.amazonaws.docdb#AttributeValueList",
        },
        ValuesToRemove: {
          target: "com.amazonaws.docdb#AttributeValueList",
        },
      },
    },
    "com.amazonaws.docdb#ModifyDBClusterSnapshotAttributeResult": {
      type: "structure",
      members: {
        DBClusterSnapshotAttributesResult: {
          target: "com.amazonaws.docdb#DBClusterSnapshotAttributesResult",
        },
      },
    },
    "com.amazonaws.docdb#ModifyDBInstanceMessage": {
      type: "structure",
      members: {
        DBInstanceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        DBInstanceClass: {
          target: "com.amazonaws.docdb#String",
        },
        ApplyImmediately: {
          target: "com.amazonaws.docdb#Boolean",
        },
        PreferredMaintenanceWindow: {
          target: "com.amazonaws.docdb#String",
        },
        AutoMinorVersionUpgrade: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        NewDBInstanceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        CACertificateIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        CopyTagsToSnapshot: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        PromotionTier: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        EnablePerformanceInsights: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        PerformanceInsightsKMSKeyId: {
          target: "com.amazonaws.docdb#String",
        },
        CertificateRotationRestart: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
      },
    },
    "com.amazonaws.docdb#ModifyDBInstanceResult": {
      type: "structure",
      members: {
        DBInstance: {
          target: "com.amazonaws.docdb#DBInstance",
        },
      },
    },
    "com.amazonaws.docdb#ModifyDBSubnetGroupMessage": {
      type: "structure",
      members: {
        DBSubnetGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        DBSubnetGroupDescription: {
          target: "com.amazonaws.docdb#String",
        },
        SubnetIds: {
          target: "com.amazonaws.docdb#SubnetIdentifierList",
        },
      },
    },
    "com.amazonaws.docdb#ModifyDBSubnetGroupResult": {
      type: "structure",
      members: {
        DBSubnetGroup: {
          target: "com.amazonaws.docdb#DBSubnetGroup",
        },
      },
    },
    "com.amazonaws.docdb#ModifyEventSubscriptionMessage": {
      type: "structure",
      members: {
        SubscriptionName: {
          target: "com.amazonaws.docdb#String",
        },
        SnsTopicArn: {
          target: "com.amazonaws.docdb#String",
        },
        SourceType: {
          target: "com.amazonaws.docdb#String",
        },
        EventCategories: {
          target: "com.amazonaws.docdb#EventCategoriesList",
        },
        Enabled: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
      },
    },
    "com.amazonaws.docdb#ModifyEventSubscriptionResult": {
      type: "structure",
      members: {
        EventSubscription: {
          target: "com.amazonaws.docdb#EventSubscription",
        },
      },
    },
    "com.amazonaws.docdb#ModifyGlobalClusterMessage": {
      type: "structure",
      members: {
        GlobalClusterIdentifier: {
          target: "com.amazonaws.docdb#GlobalClusterIdentifier",
        },
        NewGlobalClusterIdentifier: {
          target: "com.amazonaws.docdb#GlobalClusterIdentifier",
        },
        DeletionProtection: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
      },
    },
    "com.amazonaws.docdb#ModifyGlobalClusterResult": {
      type: "structure",
      members: {
        GlobalCluster: {
          target: "com.amazonaws.docdb#GlobalCluster",
        },
      },
    },
    "com.amazonaws.docdb#RebootDBInstanceMessage": {
      type: "structure",
      members: {
        DBInstanceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        ForceFailover: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
      },
    },
    "com.amazonaws.docdb#RebootDBInstanceResult": {
      type: "structure",
      members: {
        DBInstance: {
          target: "com.amazonaws.docdb#DBInstance",
        },
      },
    },
    "com.amazonaws.docdb#RemoveFromGlobalClusterMessage": {
      type: "structure",
      members: {
        GlobalClusterIdentifier: {
          target: "com.amazonaws.docdb#GlobalClusterIdentifier",
        },
        DbClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#RemoveFromGlobalClusterResult": {
      type: "structure",
      members: {
        GlobalCluster: {
          target: "com.amazonaws.docdb#GlobalCluster",
        },
      },
    },
    "com.amazonaws.docdb#RemoveSourceIdentifierFromSubscriptionMessage": {
      type: "structure",
      members: {
        SubscriptionName: {
          target: "com.amazonaws.docdb#String",
        },
        SourceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#RemoveSourceIdentifierFromSubscriptionResult": {
      type: "structure",
      members: {
        EventSubscription: {
          target: "com.amazonaws.docdb#EventSubscription",
        },
      },
    },
    "com.amazonaws.docdb#RemoveTagsFromResourceMessage": {
      type: "structure",
      members: {
        ResourceName: {
          target: "com.amazonaws.docdb#String",
        },
        TagKeys: {
          target: "com.amazonaws.docdb#KeyList",
        },
      },
    },
    "com.amazonaws.docdb#ResetDBClusterParameterGroupMessage": {
      type: "structure",
      members: {
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        ResetAllParameters: {
          target: "com.amazonaws.docdb#Boolean",
        },
        Parameters: {
          target: "com.amazonaws.docdb#ParametersList",
        },
      },
    },
    "com.amazonaws.docdb#RestoreDBClusterFromSnapshotMessage": {
      type: "structure",
      members: {
        AvailabilityZones: {
          target: "com.amazonaws.docdb#AvailabilityZones",
        },
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        SnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        Port: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        DBSubnetGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        VpcSecurityGroupIds: {
          target: "com.amazonaws.docdb#VpcSecurityGroupIdList",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
        KmsKeyId: {
          target: "com.amazonaws.docdb#String",
        },
        EnableCloudwatchLogsExports: {
          target: "com.amazonaws.docdb#LogTypeList",
        },
        DeletionProtection: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        ServerlessV2ScalingConfiguration: {
          target: "com.amazonaws.docdb#ServerlessV2ScalingConfiguration",
        },
        StorageType: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#RestoreDBClusterFromSnapshotResult": {
      type: "structure",
      members: {
        DBCluster: {
          target: "com.amazonaws.docdb#DBCluster",
        },
      },
    },
    "com.amazonaws.docdb#RestoreDBClusterToPointInTimeMessage": {
      type: "structure",
      members: {
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        RestoreType: {
          target: "com.amazonaws.docdb#String",
        },
        SourceDBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        RestoreToTime: {
          target: "com.amazonaws.docdb#TStamp",
        },
        UseLatestRestorableTime: {
          target: "com.amazonaws.docdb#Boolean",
        },
        Port: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        DBSubnetGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        VpcSecurityGroupIds: {
          target: "com.amazonaws.docdb#VpcSecurityGroupIdList",
        },
        Tags: {
          target: "com.amazonaws.docdb#TagList",
        },
        KmsKeyId: {
          target: "com.amazonaws.docdb#String",
        },
        EnableCloudwatchLogsExports: {
          target: "com.amazonaws.docdb#LogTypeList",
        },
        DeletionProtection: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        ServerlessV2ScalingConfiguration: {
          target: "com.amazonaws.docdb#ServerlessV2ScalingConfiguration",
        },
        StorageType: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#RestoreDBClusterToPointInTimeResult": {
      type: "structure",
      members: {
        DBCluster: {
          target: "com.amazonaws.docdb#DBCluster",
        },
      },
    },
    "com.amazonaws.docdb#StartDBClusterMessage": {
      type: "structure",
      members: {
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#StartDBClusterResult": {
      type: "structure",
      members: {
        DBCluster: {
          target: "com.amazonaws.docdb#DBCluster",
        },
      },
    },
    "com.amazonaws.docdb#StopDBClusterMessage": {
      type: "structure",
      members: {
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#StopDBClusterResult": {
      type: "structure",
      members: {
        DBCluster: {
          target: "com.amazonaws.docdb#DBCluster",
        },
      },
    },
    "com.amazonaws.docdb#SwitchoverGlobalClusterMessage": {
      type: "structure",
      members: {
        GlobalClusterIdentifier: {
          target: "com.amazonaws.docdb#GlobalClusterIdentifier",
        },
        TargetDbClusterIdentifier: {
          target: "com.amazonaws.docdb#DBClusterIdentifier",
        },
      },
    },
    "com.amazonaws.docdb#SwitchoverGlobalClusterResult": {
      type: "structure",
      members: {
        GlobalCluster: {
          target: "com.amazonaws.docdb#GlobalCluster",
        },
      },
    },
    "com.amazonaws.docdb#String": {
      type: "string",
    },
    "com.amazonaws.docdb#EventSubscription": {
      type: "structure",
      members: {
        CustomerAwsId: {
          target: "com.amazonaws.docdb#String",
        },
        CustSubscriptionId: {
          target: "com.amazonaws.docdb#String",
        },
        SnsTopicArn: {
          target: "com.amazonaws.docdb#String",
        },
        Status: {
          target: "com.amazonaws.docdb#String",
        },
        SubscriptionCreationTime: {
          target: "com.amazonaws.docdb#String",
        },
        SourceType: {
          target: "com.amazonaws.docdb#String",
        },
        SourceIdsList: {
          target: "com.amazonaws.docdb#SourceIdsList",
        },
        EventCategoriesList: {
          target: "com.amazonaws.docdb#EventCategoriesList",
        },
        Enabled: {
          target: "com.amazonaws.docdb#Boolean",
        },
        EventSubscriptionArn: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#SourceIdsList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
        locationName: "SourceId",
      },
    },
    "com.amazonaws.docdb#EventCategoriesList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
        locationName: "EventCategory",
      },
    },
    "com.amazonaws.docdb#Boolean": {
      type: "boolean",
    },
    "com.amazonaws.docdb#TagList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#Tag",
        locationName: "Tag",
      },
    },
    "com.amazonaws.docdb#Tag": {
      type: "structure",
      members: {
        Key: {
          target: "com.amazonaws.docdb#String",
        },
        Value: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#ResourcePendingMaintenanceActions": {
      type: "structure",
      members: {
        ResourceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        PendingMaintenanceActionDetails: {
          target: "com.amazonaws.docdb#PendingMaintenanceActionDetails",
        },
      },
    },
    "com.amazonaws.docdb#PendingMaintenanceActionDetails": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#PendingMaintenanceAction",
        locationName: "PendingMaintenanceAction",
      },
    },
    "com.amazonaws.docdb#PendingMaintenanceAction": {
      type: "structure",
      members: {
        Action: {
          target: "com.amazonaws.docdb#String",
        },
        AutoAppliedAfterDate: {
          target: "com.amazonaws.docdb#TStamp",
        },
        ForcedApplyDate: {
          target: "com.amazonaws.docdb#TStamp",
        },
        OptInStatus: {
          target: "com.amazonaws.docdb#String",
        },
        CurrentApplyDate: {
          target: "com.amazonaws.docdb#TStamp",
        },
        Description: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#TStamp": {
      type: "timestamp",
    },
    "com.amazonaws.docdb#DBClusterParameterGroup": {
      type: "structure",
      members: {
        DBClusterParameterGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        DBParameterGroupFamily: {
          target: "com.amazonaws.docdb#String",
        },
        Description: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterParameterGroupArn: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#BooleanOptional": {
      type: "boolean",
    },
    "com.amazonaws.docdb#DBClusterSnapshot": {
      type: "structure",
      members: {
        AvailabilityZones: {
          target: "com.amazonaws.docdb#AvailabilityZones",
        },
        DBClusterSnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        SnapshotCreateTime: {
          target: "com.amazonaws.docdb#TStamp",
        },
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        Status: {
          target: "com.amazonaws.docdb#String",
        },
        Port: {
          target: "com.amazonaws.docdb#Integer",
        },
        VpcId: {
          target: "com.amazonaws.docdb#String",
        },
        ClusterCreateTime: {
          target: "com.amazonaws.docdb#TStamp",
        },
        MasterUsername: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        SnapshotType: {
          target: "com.amazonaws.docdb#String",
        },
        PercentProgress: {
          target: "com.amazonaws.docdb#Integer",
        },
        StorageEncrypted: {
          target: "com.amazonaws.docdb#Boolean",
        },
        KmsKeyId: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterSnapshotArn: {
          target: "com.amazonaws.docdb#String",
        },
        SourceDBClusterSnapshotArn: {
          target: "com.amazonaws.docdb#String",
        },
        StorageType: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#AvailabilityZones": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
        locationName: "AvailabilityZone",
      },
    },
    "com.amazonaws.docdb#Integer": {
      type: "integer",
    },
    "com.amazonaws.docdb#IntegerOptional": {
      type: "integer",
    },
    "com.amazonaws.docdb#VpcSecurityGroupIdList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
        locationName: "VpcSecurityGroupId",
      },
    },
    "com.amazonaws.docdb#LogTypeList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
      },
    },
    "com.amazonaws.docdb#GlobalClusterIdentifier": {
      type: "string",
    },
    "com.amazonaws.docdb#ServerlessV2ScalingConfiguration": {
      type: "structure",
      members: {
        MinCapacity: {
          target: "com.amazonaws.docdb#DoubleOptional",
        },
        MaxCapacity: {
          target: "com.amazonaws.docdb#DoubleOptional",
        },
      },
    },
    "com.amazonaws.docdb#DoubleOptional": {
      type: "double",
    },
    "com.amazonaws.docdb#DBCluster": {
      type: "structure",
      members: {
        AvailabilityZones: {
          target: "com.amazonaws.docdb#AvailabilityZones",
        },
        BackupRetentionPeriod: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterParameterGroup: {
          target: "com.amazonaws.docdb#String",
        },
        DBSubnetGroup: {
          target: "com.amazonaws.docdb#String",
        },
        Status: {
          target: "com.amazonaws.docdb#String",
        },
        PercentProgress: {
          target: "com.amazonaws.docdb#String",
        },
        EarliestRestorableTime: {
          target: "com.amazonaws.docdb#TStamp",
        },
        Endpoint: {
          target: "com.amazonaws.docdb#String",
        },
        ReaderEndpoint: {
          target: "com.amazonaws.docdb#String",
        },
        MultiAZ: {
          target: "com.amazonaws.docdb#Boolean",
        },
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        LatestRestorableTime: {
          target: "com.amazonaws.docdb#TStamp",
        },
        Port: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        MasterUsername: {
          target: "com.amazonaws.docdb#String",
        },
        PreferredBackupWindow: {
          target: "com.amazonaws.docdb#String",
        },
        PreferredMaintenanceWindow: {
          target: "com.amazonaws.docdb#String",
        },
        ReplicationSourceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        ReadReplicaIdentifiers: {
          target: "com.amazonaws.docdb#ReadReplicaIdentifierList",
        },
        DBClusterMembers: {
          target: "com.amazonaws.docdb#DBClusterMemberList",
        },
        VpcSecurityGroups: {
          target: "com.amazonaws.docdb#VpcSecurityGroupMembershipList",
        },
        HostedZoneId: {
          target: "com.amazonaws.docdb#String",
        },
        StorageEncrypted: {
          target: "com.amazonaws.docdb#Boolean",
        },
        KmsKeyId: {
          target: "com.amazonaws.docdb#String",
        },
        DbClusterResourceId: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterArn: {
          target: "com.amazonaws.docdb#String",
        },
        AssociatedRoles: {
          target: "com.amazonaws.docdb#DBClusterRoles",
        },
        CloneGroupId: {
          target: "com.amazonaws.docdb#String",
        },
        ClusterCreateTime: {
          target: "com.amazonaws.docdb#TStamp",
        },
        EnabledCloudwatchLogsExports: {
          target: "com.amazonaws.docdb#LogTypeList",
        },
        DeletionProtection: {
          target: "com.amazonaws.docdb#Boolean",
        },
        StorageType: {
          target: "com.amazonaws.docdb#String",
        },
        ServerlessV2ScalingConfiguration: {
          target: "com.amazonaws.docdb#ServerlessV2ScalingConfigurationInfo",
        },
        MasterUserSecret: {
          target: "com.amazonaws.docdb#ClusterMasterUserSecret",
        },
      },
    },
    "com.amazonaws.docdb#ReadReplicaIdentifierList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
        locationName: "ReadReplicaIdentifier",
      },
    },
    "com.amazonaws.docdb#DBClusterMemberList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#DBClusterMember",
        locationName: "DBClusterMember",
      },
    },
    "com.amazonaws.docdb#DBClusterMember": {
      type: "structure",
      members: {
        DBInstanceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        IsClusterWriter: {
          target: "com.amazonaws.docdb#Boolean",
        },
        DBClusterParameterGroupStatus: {
          target: "com.amazonaws.docdb#String",
        },
        PromotionTier: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
      },
    },
    "com.amazonaws.docdb#VpcSecurityGroupMembershipList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#VpcSecurityGroupMembership",
        locationName: "VpcSecurityGroupMembership",
      },
    },
    "com.amazonaws.docdb#VpcSecurityGroupMembership": {
      type: "structure",
      members: {
        VpcSecurityGroupId: {
          target: "com.amazonaws.docdb#String",
        },
        Status: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DBClusterRoles": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#DBClusterRole",
        locationName: "DBClusterRole",
      },
    },
    "com.amazonaws.docdb#DBClusterRole": {
      type: "structure",
      members: {
        RoleArn: {
          target: "com.amazonaws.docdb#String",
        },
        Status: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#ServerlessV2ScalingConfigurationInfo": {
      type: "structure",
      members: {
        MinCapacity: {
          target: "com.amazonaws.docdb#DoubleOptional",
        },
        MaxCapacity: {
          target: "com.amazonaws.docdb#DoubleOptional",
        },
      },
    },
    "com.amazonaws.docdb#ClusterMasterUserSecret": {
      type: "structure",
      members: {
        SecretArn: {
          target: "com.amazonaws.docdb#String",
        },
        SecretStatus: {
          target: "com.amazonaws.docdb#String",
        },
        KmsKeyId: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DBInstance": {
      type: "structure",
      members: {
        DBInstanceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        DBInstanceClass: {
          target: "com.amazonaws.docdb#String",
        },
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        DBInstanceStatus: {
          target: "com.amazonaws.docdb#String",
        },
        Endpoint: {
          target: "com.amazonaws.docdb#Endpoint",
        },
        InstanceCreateTime: {
          target: "com.amazonaws.docdb#TStamp",
        },
        PreferredBackupWindow: {
          target: "com.amazonaws.docdb#String",
        },
        BackupRetentionPeriod: {
          target: "com.amazonaws.docdb#Integer",
        },
        VpcSecurityGroups: {
          target: "com.amazonaws.docdb#VpcSecurityGroupMembershipList",
        },
        AvailabilityZone: {
          target: "com.amazonaws.docdb#String",
        },
        DBSubnetGroup: {
          target: "com.amazonaws.docdb#DBSubnetGroup",
        },
        PreferredMaintenanceWindow: {
          target: "com.amazonaws.docdb#String",
        },
        PendingModifiedValues: {
          target: "com.amazonaws.docdb#PendingModifiedValues",
        },
        LatestRestorableTime: {
          target: "com.amazonaws.docdb#TStamp",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        AutoMinorVersionUpgrade: {
          target: "com.amazonaws.docdb#Boolean",
        },
        PubliclyAccessible: {
          target: "com.amazonaws.docdb#Boolean",
        },
        StatusInfos: {
          target: "com.amazonaws.docdb#DBInstanceStatusInfoList",
        },
        DBClusterIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        StorageEncrypted: {
          target: "com.amazonaws.docdb#Boolean",
        },
        KmsKeyId: {
          target: "com.amazonaws.docdb#String",
        },
        DbiResourceId: {
          target: "com.amazonaws.docdb#String",
        },
        CACertificateIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        CopyTagsToSnapshot: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        PromotionTier: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        DBInstanceArn: {
          target: "com.amazonaws.docdb#String",
        },
        EnabledCloudwatchLogsExports: {
          target: "com.amazonaws.docdb#LogTypeList",
        },
        CertificateDetails: {
          target: "com.amazonaws.docdb#CertificateDetails",
        },
        PerformanceInsightsEnabled: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        PerformanceInsightsKMSKeyId: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#Endpoint": {
      type: "structure",
      members: {
        Address: {
          target: "com.amazonaws.docdb#String",
        },
        Port: {
          target: "com.amazonaws.docdb#Integer",
        },
        HostedZoneId: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DBSubnetGroup": {
      type: "structure",
      members: {
        DBSubnetGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        DBSubnetGroupDescription: {
          target: "com.amazonaws.docdb#String",
        },
        VpcId: {
          target: "com.amazonaws.docdb#String",
        },
        SubnetGroupStatus: {
          target: "com.amazonaws.docdb#String",
        },
        Subnets: {
          target: "com.amazonaws.docdb#SubnetList",
        },
        DBSubnetGroupArn: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#SubnetList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#Subnet",
        locationName: "Subnet",
      },
    },
    "com.amazonaws.docdb#Subnet": {
      type: "structure",
      members: {
        SubnetIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        SubnetAvailabilityZone: {
          target: "com.amazonaws.docdb#AvailabilityZone",
        },
        SubnetStatus: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#AvailabilityZone": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#PendingModifiedValues": {
      type: "structure",
      members: {
        DBInstanceClass: {
          target: "com.amazonaws.docdb#String",
        },
        AllocatedStorage: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        MasterUserPassword: {
          target: "com.amazonaws.docdb#String",
        },
        Port: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        BackupRetentionPeriod: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        MultiAZ: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        LicenseModel: {
          target: "com.amazonaws.docdb#String",
        },
        Iops: {
          target: "com.amazonaws.docdb#IntegerOptional",
        },
        DBInstanceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        StorageType: {
          target: "com.amazonaws.docdb#String",
        },
        CACertificateIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        DBSubnetGroupName: {
          target: "com.amazonaws.docdb#String",
        },
        PendingCloudwatchLogsExports: {
          target: "com.amazonaws.docdb#PendingCloudwatchLogsExports",
        },
      },
    },
    "com.amazonaws.docdb#PendingCloudwatchLogsExports": {
      type: "structure",
      members: {
        LogTypesToEnable: {
          target: "com.amazonaws.docdb#LogTypeList",
        },
        LogTypesToDisable: {
          target: "com.amazonaws.docdb#LogTypeList",
        },
      },
    },
    "com.amazonaws.docdb#DBInstanceStatusInfoList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#DBInstanceStatusInfo",
        locationName: "DBInstanceStatusInfo",
      },
    },
    "com.amazonaws.docdb#DBInstanceStatusInfo": {
      type: "structure",
      members: {
        StatusType: {
          target: "com.amazonaws.docdb#String",
        },
        Normal: {
          target: "com.amazonaws.docdb#Boolean",
        },
        Status: {
          target: "com.amazonaws.docdb#String",
        },
        Message: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#CertificateDetails": {
      type: "structure",
      members: {
        CAIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        ValidTill: {
          target: "com.amazonaws.docdb#TStamp",
        },
      },
    },
    "com.amazonaws.docdb#SubnetIdentifierList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
        locationName: "SubnetIdentifier",
      },
    },
    "com.amazonaws.docdb#GlobalCluster": {
      type: "structure",
      members: {
        GlobalClusterIdentifier: {
          target: "com.amazonaws.docdb#GlobalClusterIdentifier",
        },
        GlobalClusterResourceId: {
          target: "com.amazonaws.docdb#String",
        },
        GlobalClusterArn: {
          target: "com.amazonaws.docdb#String",
        },
        Status: {
          target: "com.amazonaws.docdb#String",
        },
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        DatabaseName: {
          target: "com.amazonaws.docdb#String",
        },
        StorageEncrypted: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        DeletionProtection: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        GlobalClusterMembers: {
          target: "com.amazonaws.docdb#GlobalClusterMemberList",
        },
      },
    },
    "com.amazonaws.docdb#GlobalClusterMemberList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#GlobalClusterMember",
        locationName: "GlobalClusterMember",
      },
    },
    "com.amazonaws.docdb#GlobalClusterMember": {
      type: "structure",
      members: {
        DBClusterArn: {
          target: "com.amazonaws.docdb#String",
        },
        Readers: {
          target: "com.amazonaws.docdb#ReadersArnList",
        },
        IsWriter: {
          target: "com.amazonaws.docdb#Boolean",
        },
      },
    },
    "com.amazonaws.docdb#ReadersArnList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
      },
    },
    "com.amazonaws.docdb#FilterList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#Filter",
        locationName: "Filter",
      },
    },
    "com.amazonaws.docdb#Filter": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.docdb#String",
        },
        Values: {
          target: "com.amazonaws.docdb#FilterValueList",
        },
      },
    },
    "com.amazonaws.docdb#FilterValueList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
        locationName: "Value",
      },
    },
    "com.amazonaws.docdb#CertificateList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#Certificate",
        locationName: "Certificate",
      },
    },
    "com.amazonaws.docdb#Certificate": {
      type: "structure",
      members: {
        CertificateIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        CertificateType: {
          target: "com.amazonaws.docdb#String",
        },
        Thumbprint: {
          target: "com.amazonaws.docdb#String",
        },
        ValidFrom: {
          target: "com.amazonaws.docdb#TStamp",
        },
        ValidTill: {
          target: "com.amazonaws.docdb#TStamp",
        },
        CertificateArn: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#DBClusterParameterGroupList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#DBClusterParameterGroup",
        locationName: "DBClusterParameterGroup",
      },
    },
    "com.amazonaws.docdb#ParametersList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#Parameter",
        locationName: "Parameter",
      },
    },
    "com.amazonaws.docdb#Parameter": {
      type: "structure",
      members: {
        ParameterName: {
          target: "com.amazonaws.docdb#String",
        },
        ParameterValue: {
          target: "com.amazonaws.docdb#String",
        },
        Description: {
          target: "com.amazonaws.docdb#String",
        },
        Source: {
          target: "com.amazonaws.docdb#String",
        },
        ApplyType: {
          target: "com.amazonaws.docdb#String",
        },
        DataType: {
          target: "com.amazonaws.docdb#String",
        },
        AllowedValues: {
          target: "com.amazonaws.docdb#String",
        },
        IsModifiable: {
          target: "com.amazonaws.docdb#Boolean",
        },
        MinimumEngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        ApplyMethod: {
          target: "com.amazonaws.docdb#ApplyMethod",
        },
      },
    },
    "com.amazonaws.docdb#ApplyMethod": {
      type: "enum",
    },
    "com.amazonaws.docdb#DBClusterSnapshotAttributesResult": {
      type: "structure",
      members: {
        DBClusterSnapshotIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        DBClusterSnapshotAttributes: {
          target: "com.amazonaws.docdb#DBClusterSnapshotAttributeList",
        },
      },
    },
    "com.amazonaws.docdb#DBClusterSnapshotAttributeList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#DBClusterSnapshotAttribute",
        locationName: "DBClusterSnapshotAttribute",
      },
    },
    "com.amazonaws.docdb#DBClusterSnapshotAttribute": {
      type: "structure",
      members: {
        AttributeName: {
          target: "com.amazonaws.docdb#String",
        },
        AttributeValues: {
          target: "com.amazonaws.docdb#AttributeValueList",
        },
      },
    },
    "com.amazonaws.docdb#AttributeValueList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
        locationName: "AttributeValue",
      },
    },
    "com.amazonaws.docdb#DBClusterSnapshotList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#DBClusterSnapshot",
        locationName: "DBClusterSnapshot",
      },
    },
    "com.amazonaws.docdb#DBClusterList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#DBCluster",
        locationName: "DBCluster",
      },
    },
    "com.amazonaws.docdb#DBEngineVersionList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#DBEngineVersion",
        locationName: "DBEngineVersion",
      },
    },
    "com.amazonaws.docdb#DBEngineVersion": {
      type: "structure",
      members: {
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        DBParameterGroupFamily: {
          target: "com.amazonaws.docdb#String",
        },
        DBEngineDescription: {
          target: "com.amazonaws.docdb#String",
        },
        DBEngineVersionDescription: {
          target: "com.amazonaws.docdb#String",
        },
        ValidUpgradeTarget: {
          target: "com.amazonaws.docdb#ValidUpgradeTargetList",
        },
        ExportableLogTypes: {
          target: "com.amazonaws.docdb#LogTypeList",
        },
        SupportsLogExportsToCloudwatchLogs: {
          target: "com.amazonaws.docdb#Boolean",
        },
        SupportedCACertificateIdentifiers: {
          target: "com.amazonaws.docdb#CACertificateIdentifiersList",
        },
        SupportsCertificateRotationWithoutRestart: {
          target: "com.amazonaws.docdb#BooleanOptional",
        },
        ServerlessV2FeaturesSupport: {
          target: "com.amazonaws.docdb#ServerlessV2FeaturesSupport",
        },
      },
    },
    "com.amazonaws.docdb#ValidUpgradeTargetList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#UpgradeTarget",
        locationName: "UpgradeTarget",
      },
    },
    "com.amazonaws.docdb#UpgradeTarget": {
      type: "structure",
      members: {
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        Description: {
          target: "com.amazonaws.docdb#String",
        },
        AutoUpgrade: {
          target: "com.amazonaws.docdb#Boolean",
        },
        IsMajorVersionUpgrade: {
          target: "com.amazonaws.docdb#Boolean",
        },
      },
    },
    "com.amazonaws.docdb#CACertificateIdentifiersList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
      },
    },
    "com.amazonaws.docdb#ServerlessV2FeaturesSupport": {
      type: "structure",
      members: {
        MinCapacity: {
          target: "com.amazonaws.docdb#DoubleOptional",
        },
        MaxCapacity: {
          target: "com.amazonaws.docdb#DoubleOptional",
        },
      },
    },
    "com.amazonaws.docdb#DBInstanceList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#DBInstance",
        locationName: "DBInstance",
      },
    },
    "com.amazonaws.docdb#DBSubnetGroups": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#DBSubnetGroup",
        locationName: "DBSubnetGroup",
      },
    },
    "com.amazonaws.docdb#EngineDefaults": {
      type: "structure",
      members: {
        DBParameterGroupFamily: {
          target: "com.amazonaws.docdb#String",
        },
        Marker: {
          target: "com.amazonaws.docdb#String",
        },
        Parameters: {
          target: "com.amazonaws.docdb#ParametersList",
        },
      },
    },
    "com.amazonaws.docdb#EventCategoriesMapList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#EventCategoriesMap",
        locationName: "EventCategoriesMap",
      },
    },
    "com.amazonaws.docdb#EventCategoriesMap": {
      type: "structure",
      members: {
        SourceType: {
          target: "com.amazonaws.docdb#String",
        },
        EventCategories: {
          target: "com.amazonaws.docdb#EventCategoriesList",
        },
      },
    },
    "com.amazonaws.docdb#EventSubscriptionsList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#EventSubscription",
        locationName: "EventSubscription",
      },
    },
    "com.amazonaws.docdb#SourceType": {
      type: "enum",
    },
    "com.amazonaws.docdb#EventList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#Event",
        locationName: "Event",
      },
    },
    "com.amazonaws.docdb#Event": {
      type: "structure",
      members: {
        SourceIdentifier: {
          target: "com.amazonaws.docdb#String",
        },
        SourceType: {
          target: "com.amazonaws.docdb#SourceType",
        },
        Message: {
          target: "com.amazonaws.docdb#String",
        },
        EventCategories: {
          target: "com.amazonaws.docdb#EventCategoriesList",
        },
        Date: {
          target: "com.amazonaws.docdb#TStamp",
        },
        SourceArn: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#GlobalClusterList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#GlobalCluster",
        locationName: "GlobalClusterMember",
      },
    },
    "com.amazonaws.docdb#OrderableDBInstanceOptionsList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#OrderableDBInstanceOption",
        locationName: "OrderableDBInstanceOption",
      },
    },
    "com.amazonaws.docdb#OrderableDBInstanceOption": {
      type: "structure",
      members: {
        Engine: {
          target: "com.amazonaws.docdb#String",
        },
        EngineVersion: {
          target: "com.amazonaws.docdb#String",
        },
        DBInstanceClass: {
          target: "com.amazonaws.docdb#String",
        },
        LicenseModel: {
          target: "com.amazonaws.docdb#String",
        },
        AvailabilityZones: {
          target: "com.amazonaws.docdb#AvailabilityZoneList",
        },
        Vpc: {
          target: "com.amazonaws.docdb#Boolean",
        },
        StorageType: {
          target: "com.amazonaws.docdb#String",
        },
      },
    },
    "com.amazonaws.docdb#AvailabilityZoneList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#AvailabilityZone",
        locationName: "AvailabilityZone",
      },
    },
    "com.amazonaws.docdb#PendingMaintenanceActions": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#ResourcePendingMaintenanceActions",
        locationName: "ResourcePendingMaintenanceActions",
      },
    },
    "com.amazonaws.docdb#DBClusterIdentifier": {
      type: "string",
    },
    "com.amazonaws.docdb#CloudwatchLogsExportConfiguration": {
      type: "structure",
      members: {
        EnableLogTypes: {
          target: "com.amazonaws.docdb#LogTypeList",
        },
        DisableLogTypes: {
          target: "com.amazonaws.docdb#LogTypeList",
        },
      },
    },
    "com.amazonaws.docdb#KeyList": {
      type: "list",
      member: {
        target: "com.amazonaws.docdb#String",
      },
    },
  },
} as const;
