// Auto-generated by generate-awsquery-metadata.ts. DO NOT EDIT BY HAND.

export type ShapeKind =
  | "structure"
  | "list"
  | "map"
  | "string"
  | "integer"
  | "boolean"
  | "timestamp"
  | "blob"
  | "enum"
  | "double"
  | "long"
  | "float"
  | "union";

export interface MemberMeta {
  target: string;
  locationName?: string;
  queryName?: string;
  flattened?: boolean;
  timestampFormat?: "iso8601" | "epoch-seconds" | "http-date";
}

export interface ShapeMeta {
  type: ShapeKind;
  xmlName?: string;
  members?: Record<string, MemberMeta>;
  member?: MemberMeta;
  key?: MemberMeta;
  value?: MemberMeta;
  enum?: string[];
  flattened?: boolean;
}

export interface OperationMeta {
  name: string;
  input?: string;
  output?: string;
  responseWrapper?: string;
}

export interface AwsQueryServiceMeta {
  serviceId: string;
  serviceName: string;
  version: string;
  endpointPrefix?: string;
  operations: Record<string, OperationMeta>;
  shapes: Record<string, ShapeMeta>;
}

export const metadata: AwsQueryServiceMeta = {
  serviceId: "Elastic Beanstalk",
  serviceName: "Elastic Beanstalk",
  version: "2010-12-01",
  endpointPrefix: "elasticbeanstalk",
  operations: {
    AbortEnvironmentUpdate: {
      name: "AbortEnvironmentUpdate",
      input: "com.amazonaws.elasticbeanstalk#AbortEnvironmentUpdateMessage",
      output: "smithy.api#Unit",
      responseWrapper: "AbortEnvironmentUpdateResponse",
    },
    ApplyEnvironmentManagedAction: {
      name: "ApplyEnvironmentManagedAction",
      input:
        "com.amazonaws.elasticbeanstalk#ApplyEnvironmentManagedActionRequest",
      output:
        "com.amazonaws.elasticbeanstalk#ApplyEnvironmentManagedActionResult",
      responseWrapper: "ApplyEnvironmentManagedActionResponse",
    },
    AssociateEnvironmentOperationsRole: {
      name: "AssociateEnvironmentOperationsRole",
      input:
        "com.amazonaws.elasticbeanstalk#AssociateEnvironmentOperationsRoleMessage",
      output: "smithy.api#Unit",
      responseWrapper: "AssociateEnvironmentOperationsRoleResponse",
    },
    CheckDNSAvailability: {
      name: "CheckDNSAvailability",
      input: "com.amazonaws.elasticbeanstalk#CheckDNSAvailabilityMessage",
      output:
        "com.amazonaws.elasticbeanstalk#CheckDNSAvailabilityResultMessage",
      responseWrapper: "CheckDNSAvailabilityResponse",
    },
    ComposeEnvironments: {
      name: "ComposeEnvironments",
      input: "com.amazonaws.elasticbeanstalk#ComposeEnvironmentsMessage",
      output: "com.amazonaws.elasticbeanstalk#EnvironmentDescriptionsMessage",
      responseWrapper: "ComposeEnvironmentsResponse",
    },
    CreateApplication: {
      name: "CreateApplication",
      input: "com.amazonaws.elasticbeanstalk#CreateApplicationMessage",
      output: "com.amazonaws.elasticbeanstalk#ApplicationDescriptionMessage",
      responseWrapper: "CreateApplicationResponse",
    },
    CreateApplicationVersion: {
      name: "CreateApplicationVersion",
      input: "com.amazonaws.elasticbeanstalk#CreateApplicationVersionMessage",
      output:
        "com.amazonaws.elasticbeanstalk#ApplicationVersionDescriptionMessage",
      responseWrapper: "CreateApplicationVersionResponse",
    },
    CreateConfigurationTemplate: {
      name: "CreateConfigurationTemplate",
      input:
        "com.amazonaws.elasticbeanstalk#CreateConfigurationTemplateMessage",
      output: "com.amazonaws.elasticbeanstalk#ConfigurationSettingsDescription",
      responseWrapper: "CreateConfigurationTemplateResponse",
    },
    CreateEnvironment: {
      name: "CreateEnvironment",
      input: "com.amazonaws.elasticbeanstalk#CreateEnvironmentMessage",
      output: "com.amazonaws.elasticbeanstalk#EnvironmentDescription",
      responseWrapper: "CreateEnvironmentResponse",
    },
    CreatePlatformVersion: {
      name: "CreatePlatformVersion",
      input: "com.amazonaws.elasticbeanstalk#CreatePlatformVersionRequest",
      output: "com.amazonaws.elasticbeanstalk#CreatePlatformVersionResult",
      responseWrapper: "CreatePlatformVersionResponse",
    },
    CreateStorageLocation: {
      name: "CreateStorageLocation",
      input: "smithy.api#Unit",
      output:
        "com.amazonaws.elasticbeanstalk#CreateStorageLocationResultMessage",
      responseWrapper: "CreateStorageLocationResponse",
    },
    DeleteApplication: {
      name: "DeleteApplication",
      input: "com.amazonaws.elasticbeanstalk#DeleteApplicationMessage",
      output: "smithy.api#Unit",
      responseWrapper: "DeleteApplicationResponse",
    },
    DeleteApplicationVersion: {
      name: "DeleteApplicationVersion",
      input: "com.amazonaws.elasticbeanstalk#DeleteApplicationVersionMessage",
      output: "smithy.api#Unit",
      responseWrapper: "DeleteApplicationVersionResponse",
    },
    DeleteConfigurationTemplate: {
      name: "DeleteConfigurationTemplate",
      input:
        "com.amazonaws.elasticbeanstalk#DeleteConfigurationTemplateMessage",
      output: "smithy.api#Unit",
      responseWrapper: "DeleteConfigurationTemplateResponse",
    },
    DeleteEnvironmentConfiguration: {
      name: "DeleteEnvironmentConfiguration",
      input:
        "com.amazonaws.elasticbeanstalk#DeleteEnvironmentConfigurationMessage",
      output: "smithy.api#Unit",
      responseWrapper: "DeleteEnvironmentConfigurationResponse",
    },
    DeletePlatformVersion: {
      name: "DeletePlatformVersion",
      input: "com.amazonaws.elasticbeanstalk#DeletePlatformVersionRequest",
      output: "com.amazonaws.elasticbeanstalk#DeletePlatformVersionResult",
      responseWrapper: "DeletePlatformVersionResponse",
    },
    DescribeAccountAttributes: {
      name: "DescribeAccountAttributes",
      input: "smithy.api#Unit",
      output: "com.amazonaws.elasticbeanstalk#DescribeAccountAttributesResult",
      responseWrapper: "DescribeAccountAttributesResponse",
    },
    DescribeApplicationVersions: {
      name: "DescribeApplicationVersions",
      input:
        "com.amazonaws.elasticbeanstalk#DescribeApplicationVersionsMessage",
      output:
        "com.amazonaws.elasticbeanstalk#ApplicationVersionDescriptionsMessage",
      responseWrapper: "DescribeApplicationVersionsResponse",
    },
    DescribeApplications: {
      name: "DescribeApplications",
      input: "com.amazonaws.elasticbeanstalk#DescribeApplicationsMessage",
      output: "com.amazonaws.elasticbeanstalk#ApplicationDescriptionsMessage",
      responseWrapper: "DescribeApplicationsResponse",
    },
    DescribeConfigurationOptions: {
      name: "DescribeConfigurationOptions",
      input:
        "com.amazonaws.elasticbeanstalk#DescribeConfigurationOptionsMessage",
      output: "com.amazonaws.elasticbeanstalk#ConfigurationOptionsDescription",
      responseWrapper: "DescribeConfigurationOptionsResponse",
    },
    DescribeConfigurationSettings: {
      name: "DescribeConfigurationSettings",
      input:
        "com.amazonaws.elasticbeanstalk#DescribeConfigurationSettingsMessage",
      output:
        "com.amazonaws.elasticbeanstalk#ConfigurationSettingsDescriptions",
      responseWrapper: "DescribeConfigurationSettingsResponse",
    },
    DescribeEnvironmentHealth: {
      name: "DescribeEnvironmentHealth",
      input: "com.amazonaws.elasticbeanstalk#DescribeEnvironmentHealthRequest",
      output: "com.amazonaws.elasticbeanstalk#DescribeEnvironmentHealthResult",
      responseWrapper: "DescribeEnvironmentHealthResponse",
    },
    DescribeEnvironmentManagedActionHistory: {
      name: "DescribeEnvironmentManagedActionHistory",
      input:
        "com.amazonaws.elasticbeanstalk#DescribeEnvironmentManagedActionHistoryRequest",
      output:
        "com.amazonaws.elasticbeanstalk#DescribeEnvironmentManagedActionHistoryResult",
      responseWrapper: "DescribeEnvironmentManagedActionHistoryResponse",
    },
    DescribeEnvironmentManagedActions: {
      name: "DescribeEnvironmentManagedActions",
      input:
        "com.amazonaws.elasticbeanstalk#DescribeEnvironmentManagedActionsRequest",
      output:
        "com.amazonaws.elasticbeanstalk#DescribeEnvironmentManagedActionsResult",
      responseWrapper: "DescribeEnvironmentManagedActionsResponse",
    },
    DescribeEnvironmentResources: {
      name: "DescribeEnvironmentResources",
      input:
        "com.amazonaws.elasticbeanstalk#DescribeEnvironmentResourcesMessage",
      output:
        "com.amazonaws.elasticbeanstalk#EnvironmentResourceDescriptionsMessage",
      responseWrapper: "DescribeEnvironmentResourcesResponse",
    },
    DescribeEnvironments: {
      name: "DescribeEnvironments",
      input: "com.amazonaws.elasticbeanstalk#DescribeEnvironmentsMessage",
      output: "com.amazonaws.elasticbeanstalk#EnvironmentDescriptionsMessage",
      responseWrapper: "DescribeEnvironmentsResponse",
    },
    DescribeEvents: {
      name: "DescribeEvents",
      input: "com.amazonaws.elasticbeanstalk#DescribeEventsMessage",
      output: "com.amazonaws.elasticbeanstalk#EventDescriptionsMessage",
      responseWrapper: "DescribeEventsResponse",
    },
    DescribeInstancesHealth: {
      name: "DescribeInstancesHealth",
      input: "com.amazonaws.elasticbeanstalk#DescribeInstancesHealthRequest",
      output: "com.amazonaws.elasticbeanstalk#DescribeInstancesHealthResult",
      responseWrapper: "DescribeInstancesHealthResponse",
    },
    DescribePlatformVersion: {
      name: "DescribePlatformVersion",
      input: "com.amazonaws.elasticbeanstalk#DescribePlatformVersionRequest",
      output: "com.amazonaws.elasticbeanstalk#DescribePlatformVersionResult",
      responseWrapper: "DescribePlatformVersionResponse",
    },
    DisassociateEnvironmentOperationsRole: {
      name: "DisassociateEnvironmentOperationsRole",
      input:
        "com.amazonaws.elasticbeanstalk#DisassociateEnvironmentOperationsRoleMessage",
      output: "smithy.api#Unit",
      responseWrapper: "DisassociateEnvironmentOperationsRoleResponse",
    },
    ListAvailableSolutionStacks: {
      name: "ListAvailableSolutionStacks",
      input: "smithy.api#Unit",
      output:
        "com.amazonaws.elasticbeanstalk#ListAvailableSolutionStacksResultMessage",
      responseWrapper: "ListAvailableSolutionStacksResponse",
    },
    ListPlatformBranches: {
      name: "ListPlatformBranches",
      input: "com.amazonaws.elasticbeanstalk#ListPlatformBranchesRequest",
      output: "com.amazonaws.elasticbeanstalk#ListPlatformBranchesResult",
      responseWrapper: "ListPlatformBranchesResponse",
    },
    ListPlatformVersions: {
      name: "ListPlatformVersions",
      input: "com.amazonaws.elasticbeanstalk#ListPlatformVersionsRequest",
      output: "com.amazonaws.elasticbeanstalk#ListPlatformVersionsResult",
      responseWrapper: "ListPlatformVersionsResponse",
    },
    ListTagsForResource: {
      name: "ListTagsForResource",
      input: "com.amazonaws.elasticbeanstalk#ListTagsForResourceMessage",
      output: "com.amazonaws.elasticbeanstalk#ResourceTagsDescriptionMessage",
      responseWrapper: "ListTagsForResourceResponse",
    },
    RebuildEnvironment: {
      name: "RebuildEnvironment",
      input: "com.amazonaws.elasticbeanstalk#RebuildEnvironmentMessage",
      output: "smithy.api#Unit",
      responseWrapper: "RebuildEnvironmentResponse",
    },
    RequestEnvironmentInfo: {
      name: "RequestEnvironmentInfo",
      input: "com.amazonaws.elasticbeanstalk#RequestEnvironmentInfoMessage",
      output: "smithy.api#Unit",
      responseWrapper: "RequestEnvironmentInfoResponse",
    },
    RestartAppServer: {
      name: "RestartAppServer",
      input: "com.amazonaws.elasticbeanstalk#RestartAppServerMessage",
      output: "smithy.api#Unit",
      responseWrapper: "RestartAppServerResponse",
    },
    RetrieveEnvironmentInfo: {
      name: "RetrieveEnvironmentInfo",
      input: "com.amazonaws.elasticbeanstalk#RetrieveEnvironmentInfoMessage",
      output:
        "com.amazonaws.elasticbeanstalk#RetrieveEnvironmentInfoResultMessage",
      responseWrapper: "RetrieveEnvironmentInfoResponse",
    },
    SwapEnvironmentCNAMEs: {
      name: "SwapEnvironmentCNAMEs",
      input: "com.amazonaws.elasticbeanstalk#SwapEnvironmentCNAMEsMessage",
      output: "smithy.api#Unit",
      responseWrapper: "SwapEnvironmentCNAMEsResponse",
    },
    TerminateEnvironment: {
      name: "TerminateEnvironment",
      input: "com.amazonaws.elasticbeanstalk#TerminateEnvironmentMessage",
      output: "com.amazonaws.elasticbeanstalk#EnvironmentDescription",
      responseWrapper: "TerminateEnvironmentResponse",
    },
    UpdateApplication: {
      name: "UpdateApplication",
      input: "com.amazonaws.elasticbeanstalk#UpdateApplicationMessage",
      output: "com.amazonaws.elasticbeanstalk#ApplicationDescriptionMessage",
      responseWrapper: "UpdateApplicationResponse",
    },
    UpdateApplicationResourceLifecycle: {
      name: "UpdateApplicationResourceLifecycle",
      input:
        "com.amazonaws.elasticbeanstalk#UpdateApplicationResourceLifecycleMessage",
      output:
        "com.amazonaws.elasticbeanstalk#ApplicationResourceLifecycleDescriptionMessage",
      responseWrapper: "UpdateApplicationResourceLifecycleResponse",
    },
    UpdateApplicationVersion: {
      name: "UpdateApplicationVersion",
      input: "com.amazonaws.elasticbeanstalk#UpdateApplicationVersionMessage",
      output:
        "com.amazonaws.elasticbeanstalk#ApplicationVersionDescriptionMessage",
      responseWrapper: "UpdateApplicationVersionResponse",
    },
    UpdateConfigurationTemplate: {
      name: "UpdateConfigurationTemplate",
      input:
        "com.amazonaws.elasticbeanstalk#UpdateConfigurationTemplateMessage",
      output: "com.amazonaws.elasticbeanstalk#ConfigurationSettingsDescription",
      responseWrapper: "UpdateConfigurationTemplateResponse",
    },
    UpdateEnvironment: {
      name: "UpdateEnvironment",
      input: "com.amazonaws.elasticbeanstalk#UpdateEnvironmentMessage",
      output: "com.amazonaws.elasticbeanstalk#EnvironmentDescription",
      responseWrapper: "UpdateEnvironmentResponse",
    },
    UpdateTagsForResource: {
      name: "UpdateTagsForResource",
      input: "com.amazonaws.elasticbeanstalk#UpdateTagsForResourceMessage",
      output: "smithy.api#Unit",
      responseWrapper: "UpdateTagsForResourceResponse",
    },
    ValidateConfigurationSettings: {
      name: "ValidateConfigurationSettings",
      input:
        "com.amazonaws.elasticbeanstalk#ValidateConfigurationSettingsMessage",
      output:
        "com.amazonaws.elasticbeanstalk#ConfigurationSettingsValidationMessages",
      responseWrapper: "ValidateConfigurationSettingsResponse",
    },
  },
  shapes: {
    "com.amazonaws.elasticbeanstalk#AbortEnvironmentUpdateMessage": {
      type: "structure",
      members: {
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplyEnvironmentManagedActionRequest": {
      type: "structure",
      members: {
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        ActionId: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplyEnvironmentManagedActionResult": {
      type: "structure",
      members: {
        ActionId: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        ActionDescription: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        ActionType: {
          target: "com.amazonaws.elasticbeanstalk#ActionType",
        },
        Status: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#AssociateEnvironmentOperationsRoleMessage":
      {
        type: "structure",
        members: {
          EnvironmentName: {
            target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
          },
          OperationsRole: {
            target: "com.amazonaws.elasticbeanstalk#OperationsRole",
          },
        },
      },
    "com.amazonaws.elasticbeanstalk#CheckDNSAvailabilityMessage": {
      type: "structure",
      members: {
        CNAMEPrefix: {
          target: "com.amazonaws.elasticbeanstalk#DNSCnamePrefix",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#CheckDNSAvailabilityResultMessage": {
      type: "structure",
      members: {
        Available: {
          target: "com.amazonaws.elasticbeanstalk#CnameAvailability",
        },
        FullyQualifiedCNAME: {
          target: "com.amazonaws.elasticbeanstalk#DNSCname",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ComposeEnvironmentsMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        GroupName: {
          target: "com.amazonaws.elasticbeanstalk#GroupName",
        },
        VersionLabels: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabels",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentDescriptionsMessage": {
      type: "structure",
      members: {
        Environments: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentDescriptionsList",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#Token",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#CreateApplicationMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        ResourceLifecycleConfig: {
          target:
            "com.amazonaws.elasticbeanstalk#ApplicationResourceLifecycleConfig",
        },
        Tags: {
          target: "com.amazonaws.elasticbeanstalk#Tags",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplicationDescriptionMessage": {
      type: "structure",
      members: {
        Application: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationDescription",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#CreateApplicationVersionMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabel",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        SourceBuildInformation: {
          target: "com.amazonaws.elasticbeanstalk#SourceBuildInformation",
        },
        SourceBundle: {
          target: "com.amazonaws.elasticbeanstalk#S3Location",
        },
        BuildConfiguration: {
          target: "com.amazonaws.elasticbeanstalk#BuildConfiguration",
        },
        AutoCreateApplication: {
          target: "com.amazonaws.elasticbeanstalk#AutoCreateApplication",
        },
        Process: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationVersionProccess",
        },
        Tags: {
          target: "com.amazonaws.elasticbeanstalk#Tags",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplicationVersionDescriptionMessage": {
      type: "structure",
      members: {
        ApplicationVersion: {
          target:
            "com.amazonaws.elasticbeanstalk#ApplicationVersionDescription",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#CreateConfigurationTemplateMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        SolutionStackName: {
          target: "com.amazonaws.elasticbeanstalk#SolutionStackName",
        },
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        SourceConfiguration: {
          target: "com.amazonaws.elasticbeanstalk#SourceConfiguration",
        },
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        OptionSettings: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationOptionSettingsList",
        },
        Tags: {
          target: "com.amazonaws.elasticbeanstalk#Tags",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationSettingsDescription": {
      type: "structure",
      members: {
        SolutionStackName: {
          target: "com.amazonaws.elasticbeanstalk#SolutionStackName",
        },
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        DeploymentStatus: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationDeploymentStatus",
        },
        DateCreated: {
          target: "com.amazonaws.elasticbeanstalk#CreationDate",
        },
        DateUpdated: {
          target: "com.amazonaws.elasticbeanstalk#UpdateDate",
        },
        OptionSettings: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationOptionSettingsList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#CreateEnvironmentMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        GroupName: {
          target: "com.amazonaws.elasticbeanstalk#GroupName",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        CNAMEPrefix: {
          target: "com.amazonaws.elasticbeanstalk#DNSCnamePrefix",
        },
        Tier: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentTier",
        },
        Tags: {
          target: "com.amazonaws.elasticbeanstalk#Tags",
        },
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabel",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        SolutionStackName: {
          target: "com.amazonaws.elasticbeanstalk#SolutionStackName",
        },
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        OptionSettings: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationOptionSettingsList",
        },
        OptionsToRemove: {
          target: "com.amazonaws.elasticbeanstalk#OptionsSpecifierList",
        },
        OperationsRole: {
          target: "com.amazonaws.elasticbeanstalk#OperationsRole",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentDescription": {
      type: "structure",
      members: {
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabel",
        },
        SolutionStackName: {
          target: "com.amazonaws.elasticbeanstalk#SolutionStackName",
        },
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        EndpointURL: {
          target: "com.amazonaws.elasticbeanstalk#EndpointURL",
        },
        CNAME: {
          target: "com.amazonaws.elasticbeanstalk#DNSCname",
        },
        DateCreated: {
          target: "com.amazonaws.elasticbeanstalk#CreationDate",
        },
        DateUpdated: {
          target: "com.amazonaws.elasticbeanstalk#UpdateDate",
        },
        Status: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentStatus",
        },
        AbortableOperationInProgress: {
          target: "com.amazonaws.elasticbeanstalk#AbortableOperationInProgress",
        },
        Health: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentHealth",
        },
        HealthStatus: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentHealthStatus",
        },
        Resources: {
          target:
            "com.amazonaws.elasticbeanstalk#EnvironmentResourcesDescription",
        },
        Tier: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentTier",
        },
        EnvironmentLinks: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentLinks",
        },
        EnvironmentArn: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentArn",
        },
        OperationsRole: {
          target: "com.amazonaws.elasticbeanstalk#OperationsRole",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#CreatePlatformVersionRequest": {
      type: "structure",
      members: {
        PlatformName: {
          target: "com.amazonaws.elasticbeanstalk#PlatformName",
        },
        PlatformVersion: {
          target: "com.amazonaws.elasticbeanstalk#PlatformVersion",
        },
        PlatformDefinitionBundle: {
          target: "com.amazonaws.elasticbeanstalk#S3Location",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        OptionSettings: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationOptionSettingsList",
        },
        Tags: {
          target: "com.amazonaws.elasticbeanstalk#Tags",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#CreatePlatformVersionResult": {
      type: "structure",
      members: {
        PlatformSummary: {
          target: "com.amazonaws.elasticbeanstalk#PlatformSummary",
        },
        Builder: {
          target: "com.amazonaws.elasticbeanstalk#Builder",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#CreateStorageLocationResultMessage": {
      type: "structure",
      members: {
        S3Bucket: {
          target: "com.amazonaws.elasticbeanstalk#S3Bucket",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DeleteApplicationMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        TerminateEnvByForce: {
          target: "com.amazonaws.elasticbeanstalk#TerminateEnvForce",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DeleteApplicationVersionMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabel",
        },
        DeleteSourceBundle: {
          target: "com.amazonaws.elasticbeanstalk#DeleteSourceBundle",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DeleteConfigurationTemplateMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DeleteEnvironmentConfigurationMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DeletePlatformVersionRequest": {
      type: "structure",
      members: {
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DeletePlatformVersionResult": {
      type: "structure",
      members: {
        PlatformSummary: {
          target: "com.amazonaws.elasticbeanstalk#PlatformSummary",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeAccountAttributesResult": {
      type: "structure",
      members: {
        ResourceQuotas: {
          target: "com.amazonaws.elasticbeanstalk#ResourceQuotas",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeApplicationVersionsMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        VersionLabels: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabelsList",
        },
        MaxRecords: {
          target: "com.amazonaws.elasticbeanstalk#MaxRecords",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#Token",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplicationVersionDescriptionsMessage": {
      type: "structure",
      members: {
        ApplicationVersions: {
          target:
            "com.amazonaws.elasticbeanstalk#ApplicationVersionDescriptionList",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#Token",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeApplicationsMessage": {
      type: "structure",
      members: {
        ApplicationNames: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationNamesList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplicationDescriptionsMessage": {
      type: "structure",
      members: {
        Applications: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationDescriptionList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeConfigurationOptionsMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        SolutionStackName: {
          target: "com.amazonaws.elasticbeanstalk#SolutionStackName",
        },
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        Options: {
          target: "com.amazonaws.elasticbeanstalk#OptionsSpecifierList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionsDescription": {
      type: "structure",
      members: {
        SolutionStackName: {
          target: "com.amazonaws.elasticbeanstalk#SolutionStackName",
        },
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        Options: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationOptionDescriptionsList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeConfigurationSettingsMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationSettingsDescriptions": {
      type: "structure",
      members: {
        ConfigurationSettings: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationSettingsDescriptionList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeEnvironmentHealthRequest": {
      type: "structure",
      members: {
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        AttributeNames: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentHealthAttributes",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeEnvironmentHealthResult": {
      type: "structure",
      members: {
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        HealthStatus: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Status: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentHealth",
        },
        Color: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Causes: {
          target: "com.amazonaws.elasticbeanstalk#Causes",
        },
        ApplicationMetrics: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationMetrics",
        },
        InstancesHealth: {
          target: "com.amazonaws.elasticbeanstalk#InstanceHealthSummary",
        },
        RefreshedAt: {
          target: "com.amazonaws.elasticbeanstalk#RefreshedAt",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeEnvironmentManagedActionHistoryRequest":
      {
        type: "structure",
        members: {
          EnvironmentId: {
            target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
          },
          EnvironmentName: {
            target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
          },
          NextToken: {
            target: "com.amazonaws.elasticbeanstalk#String",
          },
          MaxItems: {
            target:
              "com.amazonaws.elasticbeanstalk#ManagedActionHistoryMaxItems",
          },
        },
      },
    "com.amazonaws.elasticbeanstalk#DescribeEnvironmentManagedActionHistoryResult":
      {
        type: "structure",
        members: {
          ManagedActionHistoryItems: {
            target: "com.amazonaws.elasticbeanstalk#ManagedActionHistoryItems",
          },
          NextToken: {
            target: "com.amazonaws.elasticbeanstalk#String",
          },
        },
      },
    "com.amazonaws.elasticbeanstalk#DescribeEnvironmentManagedActionsRequest": {
      type: "structure",
      members: {
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Status: {
          target: "com.amazonaws.elasticbeanstalk#ActionStatus",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeEnvironmentManagedActionsResult": {
      type: "structure",
      members: {
        ManagedActions: {
          target: "com.amazonaws.elasticbeanstalk#ManagedActions",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeEnvironmentResourcesMessage": {
      type: "structure",
      members: {
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentResourceDescriptionsMessage": {
      type: "structure",
      members: {
        EnvironmentResources: {
          target:
            "com.amazonaws.elasticbeanstalk#EnvironmentResourceDescription",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeEnvironmentsMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabel",
        },
        EnvironmentIds: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentIdList",
        },
        EnvironmentNames: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentNamesList",
        },
        IncludeDeleted: {
          target: "com.amazonaws.elasticbeanstalk#IncludeDeleted",
        },
        IncludedDeletedBackTo: {
          target: "com.amazonaws.elasticbeanstalk#IncludeDeletedBackTo",
        },
        MaxRecords: {
          target: "com.amazonaws.elasticbeanstalk#MaxRecords",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#Token",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeEventsMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabel",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        RequestId: {
          target: "com.amazonaws.elasticbeanstalk#RequestId",
        },
        Severity: {
          target: "com.amazonaws.elasticbeanstalk#EventSeverity",
        },
        StartTime: {
          target: "com.amazonaws.elasticbeanstalk#TimeFilterStart",
        },
        EndTime: {
          target: "com.amazonaws.elasticbeanstalk#TimeFilterEnd",
        },
        MaxRecords: {
          target: "com.amazonaws.elasticbeanstalk#MaxRecords",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#Token",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#EventDescriptionsMessage": {
      type: "structure",
      members: {
        Events: {
          target: "com.amazonaws.elasticbeanstalk#EventDescriptionList",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#Token",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeInstancesHealthRequest": {
      type: "structure",
      members: {
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        AttributeNames: {
          target: "com.amazonaws.elasticbeanstalk#InstancesHealthAttributes",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#NextToken",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribeInstancesHealthResult": {
      type: "structure",
      members: {
        InstanceHealthList: {
          target: "com.amazonaws.elasticbeanstalk#InstanceHealthList",
        },
        RefreshedAt: {
          target: "com.amazonaws.elasticbeanstalk#RefreshedAt",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#NextToken",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribePlatformVersionRequest": {
      type: "structure",
      members: {
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DescribePlatformVersionResult": {
      type: "structure",
      members: {
        PlatformDescription: {
          target: "com.amazonaws.elasticbeanstalk#PlatformDescription",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#DisassociateEnvironmentOperationsRoleMessage":
      {
        type: "structure",
        members: {
          EnvironmentName: {
            target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
          },
        },
      },
    "com.amazonaws.elasticbeanstalk#ListAvailableSolutionStacksResultMessage": {
      type: "structure",
      members: {
        SolutionStacks: {
          target:
            "com.amazonaws.elasticbeanstalk#AvailableSolutionStackNamesList",
        },
        SolutionStackDetails: {
          target:
            "com.amazonaws.elasticbeanstalk#AvailableSolutionStackDetailsList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ListPlatformBranchesRequest": {
      type: "structure",
      members: {
        Filters: {
          target: "com.amazonaws.elasticbeanstalk#SearchFilters",
        },
        MaxRecords: {
          target: "com.amazonaws.elasticbeanstalk#PlatformBranchMaxRecords",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#Token",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ListPlatformBranchesResult": {
      type: "structure",
      members: {
        PlatformBranchSummaryList: {
          target: "com.amazonaws.elasticbeanstalk#PlatformBranchSummaryList",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#Token",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ListPlatformVersionsRequest": {
      type: "structure",
      members: {
        Filters: {
          target: "com.amazonaws.elasticbeanstalk#PlatformFilters",
        },
        MaxRecords: {
          target: "com.amazonaws.elasticbeanstalk#PlatformMaxRecords",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#Token",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ListPlatformVersionsResult": {
      type: "structure",
      members: {
        PlatformSummaryList: {
          target: "com.amazonaws.elasticbeanstalk#PlatformSummaryList",
        },
        NextToken: {
          target: "com.amazonaws.elasticbeanstalk#Token",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ListTagsForResourceMessage": {
      type: "structure",
      members: {
        ResourceArn: {
          target: "com.amazonaws.elasticbeanstalk#ResourceArn",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ResourceTagsDescriptionMessage": {
      type: "structure",
      members: {
        ResourceArn: {
          target: "com.amazonaws.elasticbeanstalk#ResourceArn",
        },
        ResourceTags: {
          target: "com.amazonaws.elasticbeanstalk#TagList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#RebuildEnvironmentMessage": {
      type: "structure",
      members: {
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#RequestEnvironmentInfoMessage": {
      type: "structure",
      members: {
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        InfoType: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentInfoType",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#RestartAppServerMessage": {
      type: "structure",
      members: {
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#RetrieveEnvironmentInfoMessage": {
      type: "structure",
      members: {
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        InfoType: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentInfoType",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#RetrieveEnvironmentInfoResultMessage": {
      type: "structure",
      members: {
        EnvironmentInfo: {
          target:
            "com.amazonaws.elasticbeanstalk#EnvironmentInfoDescriptionList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#SwapEnvironmentCNAMEsMessage": {
      type: "structure",
      members: {
        SourceEnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        SourceEnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        DestinationEnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        DestinationEnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#TerminateEnvironmentMessage": {
      type: "structure",
      members: {
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        TerminateResources: {
          target:
            "com.amazonaws.elasticbeanstalk#TerminateEnvironmentResources",
        },
        ForceTerminate: {
          target: "com.amazonaws.elasticbeanstalk#ForceTerminate",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#UpdateApplicationMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#UpdateApplicationResourceLifecycleMessage":
      {
        type: "structure",
        members: {
          ApplicationName: {
            target: "com.amazonaws.elasticbeanstalk#ApplicationName",
          },
          ResourceLifecycleConfig: {
            target:
              "com.amazonaws.elasticbeanstalk#ApplicationResourceLifecycleConfig",
          },
        },
      },
    "com.amazonaws.elasticbeanstalk#ApplicationResourceLifecycleDescriptionMessage":
      {
        type: "structure",
        members: {
          ApplicationName: {
            target: "com.amazonaws.elasticbeanstalk#ApplicationName",
          },
          ResourceLifecycleConfig: {
            target:
              "com.amazonaws.elasticbeanstalk#ApplicationResourceLifecycleConfig",
          },
        },
      },
    "com.amazonaws.elasticbeanstalk#UpdateApplicationVersionMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabel",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#UpdateConfigurationTemplateMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        OptionSettings: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationOptionSettingsList",
        },
        OptionsToRemove: {
          target: "com.amazonaws.elasticbeanstalk#OptionsSpecifierList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#UpdateEnvironmentMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        EnvironmentId: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        GroupName: {
          target: "com.amazonaws.elasticbeanstalk#GroupName",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        Tier: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentTier",
        },
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabel",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        SolutionStackName: {
          target: "com.amazonaws.elasticbeanstalk#SolutionStackName",
        },
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        OptionSettings: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationOptionSettingsList",
        },
        OptionsToRemove: {
          target: "com.amazonaws.elasticbeanstalk#OptionsSpecifierList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#UpdateTagsForResourceMessage": {
      type: "structure",
      members: {
        ResourceArn: {
          target: "com.amazonaws.elasticbeanstalk#ResourceArn",
        },
        TagsToAdd: {
          target: "com.amazonaws.elasticbeanstalk#TagList",
        },
        TagsToRemove: {
          target: "com.amazonaws.elasticbeanstalk#TagKeyList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ValidateConfigurationSettingsMessage": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        OptionSettings: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationOptionSettingsList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationSettingsValidationMessages": {
      type: "structure",
      members: {
        Messages: {
          target: "com.amazonaws.elasticbeanstalk#ValidationMessagesList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentId": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentName": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#String": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ActionType": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#OperationsRole": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#DNSCnamePrefix": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#CnameAvailability": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#DNSCname": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ApplicationName": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#GroupName": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#VersionLabels": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#VersionLabel",
      },
    },
    "com.amazonaws.elasticbeanstalk#VersionLabel": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentDescriptionsList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#EnvironmentDescription",
      },
    },
    "com.amazonaws.elasticbeanstalk#SolutionStackName": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformArn": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#Description": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#EndpointURL": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#CreationDate": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#UpdateDate": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentStatus": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#AbortableOperationInProgress": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentHealth": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentHealthStatus": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentResourcesDescription": {
      type: "structure",
      members: {
        LoadBalancer: {
          target: "com.amazonaws.elasticbeanstalk#LoadBalancerDescription",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#LoadBalancerDescription": {
      type: "structure",
      members: {
        LoadBalancerName: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Domain: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Listeners: {
          target:
            "com.amazonaws.elasticbeanstalk#LoadBalancerListenersDescription",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#LoadBalancerListenersDescription": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#Listener",
      },
    },
    "com.amazonaws.elasticbeanstalk#Listener": {
      type: "structure",
      members: {
        Protocol: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Port: {
          target: "com.amazonaws.elasticbeanstalk#Integer",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#Integer": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentTier": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Type: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Version: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentLinks": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#EnvironmentLink",
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentLink": {
      type: "structure",
      members: {
        LinkName: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentArn": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#Token": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ApplicationResourceLifecycleConfig": {
      type: "structure",
      members: {
        ServiceRole: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        VersionLifecycleConfig: {
          target:
            "com.amazonaws.elasticbeanstalk#ApplicationVersionLifecycleConfig",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplicationVersionLifecycleConfig": {
      type: "structure",
      members: {
        MaxCountRule: {
          target: "com.amazonaws.elasticbeanstalk#MaxCountRule",
        },
        MaxAgeRule: {
          target: "com.amazonaws.elasticbeanstalk#MaxAgeRule",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#MaxCountRule": {
      type: "structure",
      members: {
        Enabled: {
          target: "com.amazonaws.elasticbeanstalk#BoxedBoolean",
        },
        MaxCount: {
          target: "com.amazonaws.elasticbeanstalk#BoxedInt",
        },
        DeleteSourceFromS3: {
          target: "com.amazonaws.elasticbeanstalk#BoxedBoolean",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#BoxedBoolean": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#BoxedInt": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#MaxAgeRule": {
      type: "structure",
      members: {
        Enabled: {
          target: "com.amazonaws.elasticbeanstalk#BoxedBoolean",
        },
        MaxAgeInDays: {
          target: "com.amazonaws.elasticbeanstalk#BoxedInt",
        },
        DeleteSourceFromS3: {
          target: "com.amazonaws.elasticbeanstalk#BoxedBoolean",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#Tags": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#Tag",
      },
    },
    "com.amazonaws.elasticbeanstalk#Tag": {
      type: "structure",
      members: {
        Key: {
          target: "com.amazonaws.elasticbeanstalk#TagKey",
        },
        Value: {
          target: "com.amazonaws.elasticbeanstalk#TagValue",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#TagKey": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#TagValue": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ApplicationDescription": {
      type: "structure",
      members: {
        ApplicationArn: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationArn",
        },
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        DateCreated: {
          target: "com.amazonaws.elasticbeanstalk#CreationDate",
        },
        DateUpdated: {
          target: "com.amazonaws.elasticbeanstalk#UpdateDate",
        },
        Versions: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabelsList",
        },
        ConfigurationTemplates: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationTemplateNamesList",
        },
        ResourceLifecycleConfig: {
          target:
            "com.amazonaws.elasticbeanstalk#ApplicationResourceLifecycleConfig",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplicationArn": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#VersionLabelsList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#VersionLabel",
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationTemplateNamesList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
      },
    },
    "com.amazonaws.elasticbeanstalk#SourceBuildInformation": {
      type: "structure",
      members: {
        SourceType: {
          target: "com.amazonaws.elasticbeanstalk#SourceType",
        },
        SourceRepository: {
          target: "com.amazonaws.elasticbeanstalk#SourceRepository",
        },
        SourceLocation: {
          target: "com.amazonaws.elasticbeanstalk#SourceLocation",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#SourceType": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#SourceRepository": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#SourceLocation": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#S3Location": {
      type: "structure",
      members: {
        S3Bucket: {
          target: "com.amazonaws.elasticbeanstalk#S3Bucket",
        },
        S3Key: {
          target: "com.amazonaws.elasticbeanstalk#S3Key",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#S3Bucket": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#S3Key": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#BuildConfiguration": {
      type: "structure",
      members: {
        ArtifactName: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        CodeBuildServiceRole: {
          target: "com.amazonaws.elasticbeanstalk#NonEmptyString",
        },
        ComputeType: {
          target: "com.amazonaws.elasticbeanstalk#ComputeType",
        },
        Image: {
          target: "com.amazonaws.elasticbeanstalk#NonEmptyString",
        },
        TimeoutInMinutes: {
          target: "com.amazonaws.elasticbeanstalk#BoxedInt",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#NonEmptyString": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ComputeType": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#AutoCreateApplication": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#ApplicationVersionProccess": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#ApplicationVersionDescription": {
      type: "structure",
      members: {
        ApplicationVersionArn: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationVersionArn",
        },
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabel",
        },
        SourceBuildInformation: {
          target: "com.amazonaws.elasticbeanstalk#SourceBuildInformation",
        },
        BuildArn: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        SourceBundle: {
          target: "com.amazonaws.elasticbeanstalk#S3Location",
        },
        DateCreated: {
          target: "com.amazonaws.elasticbeanstalk#CreationDate",
        },
        DateUpdated: {
          target: "com.amazonaws.elasticbeanstalk#UpdateDate",
        },
        Status: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationVersionStatus",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplicationVersionArn": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ApplicationVersionStatus": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#SourceConfiguration": {
      type: "structure",
      members: {
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionSettingsList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#ConfigurationOptionSetting",
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionSetting": {
      type: "structure",
      members: {
        ResourceName: {
          target: "com.amazonaws.elasticbeanstalk#ResourceName",
        },
        Namespace: {
          target: "com.amazonaws.elasticbeanstalk#OptionNamespace",
        },
        OptionName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationOptionName",
        },
        Value: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationOptionValue",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ResourceName": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#OptionNamespace": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionName": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionValue": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationDeploymentStatus": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#OptionsSpecifierList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#OptionSpecification",
      },
    },
    "com.amazonaws.elasticbeanstalk#OptionSpecification": {
      type: "structure",
      members: {
        ResourceName: {
          target: "com.amazonaws.elasticbeanstalk#ResourceName",
        },
        Namespace: {
          target: "com.amazonaws.elasticbeanstalk#OptionNamespace",
        },
        OptionName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationOptionName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#PlatformName": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformVersion": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformSummary": {
      type: "structure",
      members: {
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        PlatformOwner: {
          target: "com.amazonaws.elasticbeanstalk#PlatformOwner",
        },
        PlatformStatus: {
          target: "com.amazonaws.elasticbeanstalk#PlatformStatus",
        },
        PlatformCategory: {
          target: "com.amazonaws.elasticbeanstalk#PlatformCategory",
        },
        OperatingSystemName: {
          target: "com.amazonaws.elasticbeanstalk#OperatingSystemName",
        },
        OperatingSystemVersion: {
          target: "com.amazonaws.elasticbeanstalk#OperatingSystemVersion",
        },
        SupportedTierList: {
          target: "com.amazonaws.elasticbeanstalk#SupportedTierList",
        },
        SupportedAddonList: {
          target: "com.amazonaws.elasticbeanstalk#SupportedAddonList",
        },
        PlatformLifecycleState: {
          target: "com.amazonaws.elasticbeanstalk#PlatformLifecycleState",
        },
        PlatformVersion: {
          target: "com.amazonaws.elasticbeanstalk#PlatformVersion",
        },
        PlatformBranchName: {
          target: "com.amazonaws.elasticbeanstalk#BranchName",
        },
        PlatformBranchLifecycleState: {
          target: "com.amazonaws.elasticbeanstalk#PlatformBranchLifecycleState",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#PlatformOwner": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformStatus": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#PlatformCategory": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#OperatingSystemName": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#OperatingSystemVersion": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#SupportedTierList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#SupportedTier",
      },
    },
    "com.amazonaws.elasticbeanstalk#SupportedTier": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#SupportedAddonList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#SupportedAddon",
      },
    },
    "com.amazonaws.elasticbeanstalk#SupportedAddon": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformLifecycleState": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#BranchName": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformBranchLifecycleState": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#Builder": {
      type: "structure",
      members: {
        ARN: {
          target: "com.amazonaws.elasticbeanstalk#ARN",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ARN": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#TerminateEnvForce": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#DeleteSourceBundle": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#ResourceQuotas": {
      type: "structure",
      members: {
        ApplicationQuota: {
          target: "com.amazonaws.elasticbeanstalk#ResourceQuota",
        },
        ApplicationVersionQuota: {
          target: "com.amazonaws.elasticbeanstalk#ResourceQuota",
        },
        EnvironmentQuota: {
          target: "com.amazonaws.elasticbeanstalk#ResourceQuota",
        },
        ConfigurationTemplateQuota: {
          target: "com.amazonaws.elasticbeanstalk#ResourceQuota",
        },
        CustomPlatformQuota: {
          target: "com.amazonaws.elasticbeanstalk#ResourceQuota",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ResourceQuota": {
      type: "structure",
      members: {
        Maximum: {
          target: "com.amazonaws.elasticbeanstalk#BoxedInt",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#MaxRecords": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#ApplicationVersionDescriptionList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#ApplicationVersionDescription",
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplicationNamesList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#ApplicationName",
      },
    },
    "com.amazonaws.elasticbeanstalk#ApplicationDescriptionList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#ApplicationDescription",
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionDescriptionsList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#ConfigurationOptionDescription",
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionDescription": {
      type: "structure",
      members: {
        Namespace: {
          target: "com.amazonaws.elasticbeanstalk#OptionNamespace",
        },
        Name: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationOptionName",
        },
        DefaultValue: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationOptionDefaultValue",
        },
        ChangeSeverity: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationOptionSeverity",
        },
        UserDefined: {
          target: "com.amazonaws.elasticbeanstalk#UserDefinedOption",
        },
        ValueType: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationOptionValueType",
        },
        ValueOptions: {
          target:
            "com.amazonaws.elasticbeanstalk#ConfigurationOptionPossibleValues",
        },
        MinValue: {
          target: "com.amazonaws.elasticbeanstalk#OptionRestrictionMinValue",
        },
        MaxValue: {
          target: "com.amazonaws.elasticbeanstalk#OptionRestrictionMaxValue",
        },
        MaxLength: {
          target: "com.amazonaws.elasticbeanstalk#OptionRestrictionMaxLength",
        },
        Regex: {
          target: "com.amazonaws.elasticbeanstalk#OptionRestrictionRegex",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionDefaultValue": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionSeverity": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#UserDefinedOption": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionValueType": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionPossibleValues": {
      type: "list",
      member: {
        target:
          "com.amazonaws.elasticbeanstalk#ConfigurationOptionPossibleValue",
      },
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationOptionPossibleValue": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#OptionRestrictionMinValue": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#OptionRestrictionMaxValue": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#OptionRestrictionMaxLength": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#OptionRestrictionRegex": {
      type: "structure",
      members: {
        Pattern: {
          target: "com.amazonaws.elasticbeanstalk#RegexPattern",
        },
        Label: {
          target: "com.amazonaws.elasticbeanstalk#RegexLabel",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#RegexPattern": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#RegexLabel": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ConfigurationSettingsDescriptionList": {
      type: "list",
      member: {
        target:
          "com.amazonaws.elasticbeanstalk#ConfigurationSettingsDescription",
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentHealthAttributes": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#EnvironmentHealthAttribute",
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentHealthAttribute": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#Causes": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#Cause",
      },
    },
    "com.amazonaws.elasticbeanstalk#Cause": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ApplicationMetrics": {
      type: "structure",
      members: {
        Duration: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        RequestCount: {
          target: "com.amazonaws.elasticbeanstalk#RequestCount",
        },
        StatusCodes: {
          target: "com.amazonaws.elasticbeanstalk#StatusCodes",
        },
        Latency: {
          target: "com.amazonaws.elasticbeanstalk#Latency",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#NullableInteger": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#RequestCount": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#StatusCodes": {
      type: "structure",
      members: {
        Status2xx: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        Status3xx: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        Status4xx: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        Status5xx: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#Latency": {
      type: "structure",
      members: {
        P999: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        P99: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        P95: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        P90: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        P85: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        P75: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        P50: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        P10: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#NullableDouble": {
      type: "double",
    },
    "com.amazonaws.elasticbeanstalk#InstanceHealthSummary": {
      type: "structure",
      members: {
        NoData: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        Unknown: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        Pending: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        Ok: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        Info: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        Warning: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        Degraded: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
        Severe: {
          target: "com.amazonaws.elasticbeanstalk#NullableInteger",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#RefreshedAt": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#ManagedActionHistoryMaxItems": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#ManagedActionHistoryItems": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#ManagedActionHistoryItem",
      },
    },
    "com.amazonaws.elasticbeanstalk#ManagedActionHistoryItem": {
      type: "structure",
      members: {
        ActionId: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        ActionType: {
          target: "com.amazonaws.elasticbeanstalk#ActionType",
        },
        ActionDescription: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        FailureType: {
          target: "com.amazonaws.elasticbeanstalk#FailureType",
        },
        Status: {
          target: "com.amazonaws.elasticbeanstalk#ActionHistoryStatus",
        },
        FailureDescription: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        ExecutedTime: {
          target: "com.amazonaws.elasticbeanstalk#Timestamp",
        },
        FinishedTime: {
          target: "com.amazonaws.elasticbeanstalk#Timestamp",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#FailureType": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#ActionHistoryStatus": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#Timestamp": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#ActionStatus": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#ManagedActions": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#ManagedAction",
      },
    },
    "com.amazonaws.elasticbeanstalk#ManagedAction": {
      type: "structure",
      members: {
        ActionId: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        ActionDescription: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        ActionType: {
          target: "com.amazonaws.elasticbeanstalk#ActionType",
        },
        Status: {
          target: "com.amazonaws.elasticbeanstalk#ActionStatus",
        },
        WindowStartTime: {
          target: "com.amazonaws.elasticbeanstalk#Timestamp",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentResourceDescription": {
      type: "structure",
      members: {
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        AutoScalingGroups: {
          target: "com.amazonaws.elasticbeanstalk#AutoScalingGroupList",
        },
        Instances: {
          target: "com.amazonaws.elasticbeanstalk#InstanceList",
        },
        LaunchConfigurations: {
          target: "com.amazonaws.elasticbeanstalk#LaunchConfigurationList",
        },
        LaunchTemplates: {
          target: "com.amazonaws.elasticbeanstalk#LaunchTemplateList",
        },
        LoadBalancers: {
          target: "com.amazonaws.elasticbeanstalk#LoadBalancerList",
        },
        Triggers: {
          target: "com.amazonaws.elasticbeanstalk#TriggerList",
        },
        Queues: {
          target: "com.amazonaws.elasticbeanstalk#QueueList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#AutoScalingGroupList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#AutoScalingGroup",
      },
    },
    "com.amazonaws.elasticbeanstalk#AutoScalingGroup": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.elasticbeanstalk#ResourceId",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ResourceId": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#InstanceList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#Instance",
      },
    },
    "com.amazonaws.elasticbeanstalk#Instance": {
      type: "structure",
      members: {
        Id: {
          target: "com.amazonaws.elasticbeanstalk#ResourceId",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#LaunchConfigurationList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#LaunchConfiguration",
      },
    },
    "com.amazonaws.elasticbeanstalk#LaunchConfiguration": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.elasticbeanstalk#ResourceId",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#LaunchTemplateList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#LaunchTemplate",
      },
    },
    "com.amazonaws.elasticbeanstalk#LaunchTemplate": {
      type: "structure",
      members: {
        Id: {
          target: "com.amazonaws.elasticbeanstalk#ResourceId",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#LoadBalancerList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#LoadBalancer",
      },
    },
    "com.amazonaws.elasticbeanstalk#LoadBalancer": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.elasticbeanstalk#ResourceId",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#TriggerList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#Trigger",
      },
    },
    "com.amazonaws.elasticbeanstalk#Trigger": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.elasticbeanstalk#ResourceId",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#QueueList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#Queue",
      },
    },
    "com.amazonaws.elasticbeanstalk#Queue": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        URL: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentIdList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#EnvironmentId",
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentNamesList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
      },
    },
    "com.amazonaws.elasticbeanstalk#IncludeDeleted": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#IncludeDeletedBackTo": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#RequestId": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#EventSeverity": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#TimeFilterStart": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#TimeFilterEnd": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#EventDescriptionList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#EventDescription",
      },
    },
    "com.amazonaws.elasticbeanstalk#EventDescription": {
      type: "structure",
      members: {
        EventDate: {
          target: "com.amazonaws.elasticbeanstalk#EventDate",
        },
        Message: {
          target: "com.amazonaws.elasticbeanstalk#EventMessage",
        },
        ApplicationName: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationName",
        },
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#VersionLabel",
        },
        TemplateName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationTemplateName",
        },
        EnvironmentName: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentName",
        },
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        RequestId: {
          target: "com.amazonaws.elasticbeanstalk#RequestId",
        },
        Severity: {
          target: "com.amazonaws.elasticbeanstalk#EventSeverity",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#EventDate": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#EventMessage": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#InstancesHealthAttributes": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#InstancesHealthAttribute",
      },
    },
    "com.amazonaws.elasticbeanstalk#InstancesHealthAttribute": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#NextToken": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#InstanceHealthList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#SingleInstanceHealth",
      },
    },
    "com.amazonaws.elasticbeanstalk#SingleInstanceHealth": {
      type: "structure",
      members: {
        InstanceId: {
          target: "com.amazonaws.elasticbeanstalk#InstanceId",
        },
        HealthStatus: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Color: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Causes: {
          target: "com.amazonaws.elasticbeanstalk#Causes",
        },
        LaunchedAt: {
          target: "com.amazonaws.elasticbeanstalk#LaunchedAt",
        },
        ApplicationMetrics: {
          target: "com.amazonaws.elasticbeanstalk#ApplicationMetrics",
        },
        System: {
          target: "com.amazonaws.elasticbeanstalk#SystemStatus",
        },
        Deployment: {
          target: "com.amazonaws.elasticbeanstalk#Deployment",
        },
        AvailabilityZone: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        InstanceType: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#InstanceId": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#LaunchedAt": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#SystemStatus": {
      type: "structure",
      members: {
        CPUUtilization: {
          target: "com.amazonaws.elasticbeanstalk#CPUUtilization",
        },
        LoadAverage: {
          target: "com.amazonaws.elasticbeanstalk#LoadAverage",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#CPUUtilization": {
      type: "structure",
      members: {
        User: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        Nice: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        System: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        Idle: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        IOWait: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        IRQ: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        SoftIRQ: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
        Privileged: {
          target: "com.amazonaws.elasticbeanstalk#NullableDouble",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#LoadAverage": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#LoadAverageValue",
      },
    },
    "com.amazonaws.elasticbeanstalk#LoadAverageValue": {
      type: "double",
    },
    "com.amazonaws.elasticbeanstalk#Deployment": {
      type: "structure",
      members: {
        VersionLabel: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        DeploymentId: {
          target: "com.amazonaws.elasticbeanstalk#NullableLong",
        },
        Status: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        DeploymentTime: {
          target: "com.amazonaws.elasticbeanstalk#DeploymentTimestamp",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#NullableLong": {
      type: "long",
    },
    "com.amazonaws.elasticbeanstalk#DeploymentTimestamp": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#PlatformDescription": {
      type: "structure",
      members: {
        PlatformArn: {
          target: "com.amazonaws.elasticbeanstalk#PlatformArn",
        },
        PlatformOwner: {
          target: "com.amazonaws.elasticbeanstalk#PlatformOwner",
        },
        PlatformName: {
          target: "com.amazonaws.elasticbeanstalk#PlatformName",
        },
        PlatformVersion: {
          target: "com.amazonaws.elasticbeanstalk#PlatformVersion",
        },
        SolutionStackName: {
          target: "com.amazonaws.elasticbeanstalk#SolutionStackName",
        },
        PlatformStatus: {
          target: "com.amazonaws.elasticbeanstalk#PlatformStatus",
        },
        DateCreated: {
          target: "com.amazonaws.elasticbeanstalk#CreationDate",
        },
        DateUpdated: {
          target: "com.amazonaws.elasticbeanstalk#UpdateDate",
        },
        PlatformCategory: {
          target: "com.amazonaws.elasticbeanstalk#PlatformCategory",
        },
        Description: {
          target: "com.amazonaws.elasticbeanstalk#Description",
        },
        Maintainer: {
          target: "com.amazonaws.elasticbeanstalk#Maintainer",
        },
        OperatingSystemName: {
          target: "com.amazonaws.elasticbeanstalk#OperatingSystemName",
        },
        OperatingSystemVersion: {
          target: "com.amazonaws.elasticbeanstalk#OperatingSystemVersion",
        },
        ProgrammingLanguages: {
          target: "com.amazonaws.elasticbeanstalk#PlatformProgrammingLanguages",
        },
        Frameworks: {
          target: "com.amazonaws.elasticbeanstalk#PlatformFrameworks",
        },
        CustomAmiList: {
          target: "com.amazonaws.elasticbeanstalk#CustomAmiList",
        },
        SupportedTierList: {
          target: "com.amazonaws.elasticbeanstalk#SupportedTierList",
        },
        SupportedAddonList: {
          target: "com.amazonaws.elasticbeanstalk#SupportedAddonList",
        },
        PlatformLifecycleState: {
          target: "com.amazonaws.elasticbeanstalk#PlatformLifecycleState",
        },
        PlatformBranchName: {
          target: "com.amazonaws.elasticbeanstalk#BranchName",
        },
        PlatformBranchLifecycleState: {
          target: "com.amazonaws.elasticbeanstalk#PlatformBranchLifecycleState",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#Maintainer": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformProgrammingLanguages": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#PlatformProgrammingLanguage",
      },
    },
    "com.amazonaws.elasticbeanstalk#PlatformProgrammingLanguage": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Version: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#PlatformFrameworks": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#PlatformFramework",
      },
    },
    "com.amazonaws.elasticbeanstalk#PlatformFramework": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
        Version: {
          target: "com.amazonaws.elasticbeanstalk#String",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#CustomAmiList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#CustomAmi",
      },
    },
    "com.amazonaws.elasticbeanstalk#CustomAmi": {
      type: "structure",
      members: {
        VirtualizationType: {
          target: "com.amazonaws.elasticbeanstalk#VirtualizationType",
        },
        ImageId: {
          target: "com.amazonaws.elasticbeanstalk#ImageId",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#VirtualizationType": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ImageId": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#AvailableSolutionStackNamesList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#SolutionStackName",
      },
    },
    "com.amazonaws.elasticbeanstalk#AvailableSolutionStackDetailsList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#SolutionStackDescription",
      },
    },
    "com.amazonaws.elasticbeanstalk#SolutionStackDescription": {
      type: "structure",
      members: {
        SolutionStackName: {
          target: "com.amazonaws.elasticbeanstalk#SolutionStackName",
        },
        PermittedFileTypes: {
          target: "com.amazonaws.elasticbeanstalk#SolutionStackFileTypeList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#SolutionStackFileTypeList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#FileTypeExtension",
      },
    },
    "com.amazonaws.elasticbeanstalk#FileTypeExtension": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#SearchFilters": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#SearchFilter",
      },
    },
    "com.amazonaws.elasticbeanstalk#SearchFilter": {
      type: "structure",
      members: {
        Attribute: {
          target: "com.amazonaws.elasticbeanstalk#SearchFilterAttribute",
        },
        Operator: {
          target: "com.amazonaws.elasticbeanstalk#SearchFilterOperator",
        },
        Values: {
          target: "com.amazonaws.elasticbeanstalk#SearchFilterValues",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#SearchFilterAttribute": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#SearchFilterOperator": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#SearchFilterValues": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#SearchFilterValue",
      },
    },
    "com.amazonaws.elasticbeanstalk#SearchFilterValue": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformBranchMaxRecords": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#PlatformBranchSummaryList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#PlatformBranchSummary",
      },
    },
    "com.amazonaws.elasticbeanstalk#PlatformBranchSummary": {
      type: "structure",
      members: {
        PlatformName: {
          target: "com.amazonaws.elasticbeanstalk#PlatformName",
        },
        BranchName: {
          target: "com.amazonaws.elasticbeanstalk#BranchName",
        },
        LifecycleState: {
          target: "com.amazonaws.elasticbeanstalk#PlatformBranchLifecycleState",
        },
        BranchOrder: {
          target: "com.amazonaws.elasticbeanstalk#BranchOrder",
        },
        SupportedTierList: {
          target: "com.amazonaws.elasticbeanstalk#SupportedTierList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#BranchOrder": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#PlatformFilters": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#PlatformFilter",
      },
    },
    "com.amazonaws.elasticbeanstalk#PlatformFilter": {
      type: "structure",
      members: {
        Type: {
          target: "com.amazonaws.elasticbeanstalk#PlatformFilterType",
        },
        Operator: {
          target: "com.amazonaws.elasticbeanstalk#PlatformFilterOperator",
        },
        Values: {
          target: "com.amazonaws.elasticbeanstalk#PlatformFilterValueList",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#PlatformFilterType": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformFilterOperator": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformFilterValueList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#PlatformFilterValue",
      },
    },
    "com.amazonaws.elasticbeanstalk#PlatformFilterValue": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#PlatformMaxRecords": {
      type: "integer",
    },
    "com.amazonaws.elasticbeanstalk#PlatformSummaryList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#PlatformSummary",
      },
    },
    "com.amazonaws.elasticbeanstalk#ResourceArn": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#TagList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#Tag",
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentInfoType": {
      type: "enum",
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentInfoDescriptionList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#EnvironmentInfoDescription",
      },
    },
    "com.amazonaws.elasticbeanstalk#EnvironmentInfoDescription": {
      type: "structure",
      members: {
        InfoType: {
          target: "com.amazonaws.elasticbeanstalk#EnvironmentInfoType",
        },
        Ec2InstanceId: {
          target: "com.amazonaws.elasticbeanstalk#Ec2InstanceId",
        },
        SampleTimestamp: {
          target: "com.amazonaws.elasticbeanstalk#SampleTimestamp",
        },
        Message: {
          target: "com.amazonaws.elasticbeanstalk#Message",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#Ec2InstanceId": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#SampleTimestamp": {
      type: "timestamp",
    },
    "com.amazonaws.elasticbeanstalk#Message": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#TerminateEnvironmentResources": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#ForceTerminate": {
      type: "boolean",
    },
    "com.amazonaws.elasticbeanstalk#TagKeyList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#TagKey",
      },
    },
    "com.amazonaws.elasticbeanstalk#ValidationMessagesList": {
      type: "list",
      member: {
        target: "com.amazonaws.elasticbeanstalk#ValidationMessage",
      },
    },
    "com.amazonaws.elasticbeanstalk#ValidationMessage": {
      type: "structure",
      members: {
        Message: {
          target: "com.amazonaws.elasticbeanstalk#ValidationMessageString",
        },
        Severity: {
          target: "com.amazonaws.elasticbeanstalk#ValidationSeverity",
        },
        Namespace: {
          target: "com.amazonaws.elasticbeanstalk#OptionNamespace",
        },
        OptionName: {
          target: "com.amazonaws.elasticbeanstalk#ConfigurationOptionName",
        },
      },
    },
    "com.amazonaws.elasticbeanstalk#ValidationMessageString": {
      type: "string",
    },
    "com.amazonaws.elasticbeanstalk#ValidationSeverity": {
      type: "enum",
    },
  },
} as const;
