// Auto-generated by generate-awsquery-metadata.ts. DO NOT EDIT BY HAND.

export type ShapeKind =
  | "structure"
  | "list"
  | "map"
  | "string"
  | "integer"
  | "boolean"
  | "timestamp"
  | "blob"
  | "enum"
  | "double"
  | "long"
  | "float"
  | "union";

export interface MemberMeta {
  target: string;
  locationName?: string;
  queryName?: string;
  flattened?: boolean;
  timestampFormat?: "iso8601" | "epoch-seconds" | "http-date";
}

export interface ShapeMeta {
  type: ShapeKind;
  xmlName?: string;
  members?: Record<string, MemberMeta>;
  member?: MemberMeta;
  key?: MemberMeta;
  value?: MemberMeta;
  enum?: string[];
  flattened?: boolean;
}

export interface OperationMeta {
  name: string;
  input?: string;
  output?: string;
  responseWrapper?: string;
}

export interface AwsQueryServiceMeta {
  serviceId: string;
  serviceName: string;
  version: string;
  endpointPrefix?: string;
  operations: Record<string, OperationMeta>;
  shapes: Record<string, ShapeMeta>;
}

export const metadata: AwsQueryServiceMeta = {
  serviceId: "SES",
  serviceName: "SES",
  version: "2010-12-01",
  endpointPrefix: "email",
  operations: {
    CloneReceiptRuleSet: {
      name: "CloneReceiptRuleSet",
      input: "com.amazonaws.ses#CloneReceiptRuleSetRequest",
      output: "com.amazonaws.ses#CloneReceiptRuleSetResponse",
      responseWrapper: "CloneReceiptRuleSetResponse",
    },
    CreateConfigurationSet: {
      name: "CreateConfigurationSet",
      input: "com.amazonaws.ses#CreateConfigurationSetRequest",
      output: "com.amazonaws.ses#CreateConfigurationSetResponse",
      responseWrapper: "CreateConfigurationSetResponse",
    },
    CreateConfigurationSetEventDestination: {
      name: "CreateConfigurationSetEventDestination",
      input: "com.amazonaws.ses#CreateConfigurationSetEventDestinationRequest",
      output:
        "com.amazonaws.ses#CreateConfigurationSetEventDestinationResponse",
      responseWrapper: "CreateConfigurationSetEventDestinationResponse",
    },
    CreateConfigurationSetTrackingOptions: {
      name: "CreateConfigurationSetTrackingOptions",
      input: "com.amazonaws.ses#CreateConfigurationSetTrackingOptionsRequest",
      output: "com.amazonaws.ses#CreateConfigurationSetTrackingOptionsResponse",
      responseWrapper: "CreateConfigurationSetTrackingOptionsResponse",
    },
    CreateCustomVerificationEmailTemplate: {
      name: "CreateCustomVerificationEmailTemplate",
      input: "com.amazonaws.ses#CreateCustomVerificationEmailTemplateRequest",
      output: "smithy.api#Unit",
      responseWrapper: "CreateCustomVerificationEmailTemplateResponse",
    },
    CreateReceiptFilter: {
      name: "CreateReceiptFilter",
      input: "com.amazonaws.ses#CreateReceiptFilterRequest",
      output: "com.amazonaws.ses#CreateReceiptFilterResponse",
      responseWrapper: "CreateReceiptFilterResponse",
    },
    CreateReceiptRule: {
      name: "CreateReceiptRule",
      input: "com.amazonaws.ses#CreateReceiptRuleRequest",
      output: "com.amazonaws.ses#CreateReceiptRuleResponse",
      responseWrapper: "CreateReceiptRuleResponse",
    },
    CreateReceiptRuleSet: {
      name: "CreateReceiptRuleSet",
      input: "com.amazonaws.ses#CreateReceiptRuleSetRequest",
      output: "com.amazonaws.ses#CreateReceiptRuleSetResponse",
      responseWrapper: "CreateReceiptRuleSetResponse",
    },
    CreateTemplate: {
      name: "CreateTemplate",
      input: "com.amazonaws.ses#CreateTemplateRequest",
      output: "com.amazonaws.ses#CreateTemplateResponse",
      responseWrapper: "CreateTemplateResponse",
    },
    DeleteConfigurationSet: {
      name: "DeleteConfigurationSet",
      input: "com.amazonaws.ses#DeleteConfigurationSetRequest",
      output: "com.amazonaws.ses#DeleteConfigurationSetResponse",
      responseWrapper: "DeleteConfigurationSetResponse",
    },
    DeleteConfigurationSetEventDestination: {
      name: "DeleteConfigurationSetEventDestination",
      input: "com.amazonaws.ses#DeleteConfigurationSetEventDestinationRequest",
      output:
        "com.amazonaws.ses#DeleteConfigurationSetEventDestinationResponse",
      responseWrapper: "DeleteConfigurationSetEventDestinationResponse",
    },
    DeleteConfigurationSetTrackingOptions: {
      name: "DeleteConfigurationSetTrackingOptions",
      input: "com.amazonaws.ses#DeleteConfigurationSetTrackingOptionsRequest",
      output: "com.amazonaws.ses#DeleteConfigurationSetTrackingOptionsResponse",
      responseWrapper: "DeleteConfigurationSetTrackingOptionsResponse",
    },
    DeleteCustomVerificationEmailTemplate: {
      name: "DeleteCustomVerificationEmailTemplate",
      input: "com.amazonaws.ses#DeleteCustomVerificationEmailTemplateRequest",
      output: "smithy.api#Unit",
      responseWrapper: "DeleteCustomVerificationEmailTemplateResponse",
    },
    DeleteIdentity: {
      name: "DeleteIdentity",
      input: "com.amazonaws.ses#DeleteIdentityRequest",
      output: "com.amazonaws.ses#DeleteIdentityResponse",
      responseWrapper: "DeleteIdentityResponse",
    },
    DeleteIdentityPolicy: {
      name: "DeleteIdentityPolicy",
      input: "com.amazonaws.ses#DeleteIdentityPolicyRequest",
      output: "com.amazonaws.ses#DeleteIdentityPolicyResponse",
      responseWrapper: "DeleteIdentityPolicyResponse",
    },
    DeleteReceiptFilter: {
      name: "DeleteReceiptFilter",
      input: "com.amazonaws.ses#DeleteReceiptFilterRequest",
      output: "com.amazonaws.ses#DeleteReceiptFilterResponse",
      responseWrapper: "DeleteReceiptFilterResponse",
    },
    DeleteReceiptRule: {
      name: "DeleteReceiptRule",
      input: "com.amazonaws.ses#DeleteReceiptRuleRequest",
      output: "com.amazonaws.ses#DeleteReceiptRuleResponse",
      responseWrapper: "DeleteReceiptRuleResponse",
    },
    DeleteReceiptRuleSet: {
      name: "DeleteReceiptRuleSet",
      input: "com.amazonaws.ses#DeleteReceiptRuleSetRequest",
      output: "com.amazonaws.ses#DeleteReceiptRuleSetResponse",
      responseWrapper: "DeleteReceiptRuleSetResponse",
    },
    DeleteTemplate: {
      name: "DeleteTemplate",
      input: "com.amazonaws.ses#DeleteTemplateRequest",
      output: "com.amazonaws.ses#DeleteTemplateResponse",
      responseWrapper: "DeleteTemplateResponse",
    },
    DeleteVerifiedEmailAddress: {
      name: "DeleteVerifiedEmailAddress",
      input: "com.amazonaws.ses#DeleteVerifiedEmailAddressRequest",
      output: "smithy.api#Unit",
      responseWrapper: "DeleteVerifiedEmailAddressResponse",
    },
    DescribeActiveReceiptRuleSet: {
      name: "DescribeActiveReceiptRuleSet",
      input: "com.amazonaws.ses#DescribeActiveReceiptRuleSetRequest",
      output: "com.amazonaws.ses#DescribeActiveReceiptRuleSetResponse",
      responseWrapper: "DescribeActiveReceiptRuleSetResponse",
    },
    DescribeConfigurationSet: {
      name: "DescribeConfigurationSet",
      input: "com.amazonaws.ses#DescribeConfigurationSetRequest",
      output: "com.amazonaws.ses#DescribeConfigurationSetResponse",
      responseWrapper: "DescribeConfigurationSetResponse",
    },
    DescribeReceiptRule: {
      name: "DescribeReceiptRule",
      input: "com.amazonaws.ses#DescribeReceiptRuleRequest",
      output: "com.amazonaws.ses#DescribeReceiptRuleResponse",
      responseWrapper: "DescribeReceiptRuleResponse",
    },
    DescribeReceiptRuleSet: {
      name: "DescribeReceiptRuleSet",
      input: "com.amazonaws.ses#DescribeReceiptRuleSetRequest",
      output: "com.amazonaws.ses#DescribeReceiptRuleSetResponse",
      responseWrapper: "DescribeReceiptRuleSetResponse",
    },
    GetAccountSendingEnabled: {
      name: "GetAccountSendingEnabled",
      input: "smithy.api#Unit",
      output: "com.amazonaws.ses#GetAccountSendingEnabledResponse",
      responseWrapper: "GetAccountSendingEnabledResponse",
    },
    GetCustomVerificationEmailTemplate: {
      name: "GetCustomVerificationEmailTemplate",
      input: "com.amazonaws.ses#GetCustomVerificationEmailTemplateRequest",
      output: "com.amazonaws.ses#GetCustomVerificationEmailTemplateResponse",
      responseWrapper: "GetCustomVerificationEmailTemplateResponse",
    },
    GetIdentityDkimAttributes: {
      name: "GetIdentityDkimAttributes",
      input: "com.amazonaws.ses#GetIdentityDkimAttributesRequest",
      output: "com.amazonaws.ses#GetIdentityDkimAttributesResponse",
      responseWrapper: "GetIdentityDkimAttributesResponse",
    },
    GetIdentityMailFromDomainAttributes: {
      name: "GetIdentityMailFromDomainAttributes",
      input: "com.amazonaws.ses#GetIdentityMailFromDomainAttributesRequest",
      output: "com.amazonaws.ses#GetIdentityMailFromDomainAttributesResponse",
      responseWrapper: "GetIdentityMailFromDomainAttributesResponse",
    },
    GetIdentityNotificationAttributes: {
      name: "GetIdentityNotificationAttributes",
      input: "com.amazonaws.ses#GetIdentityNotificationAttributesRequest",
      output: "com.amazonaws.ses#GetIdentityNotificationAttributesResponse",
      responseWrapper: "GetIdentityNotificationAttributesResponse",
    },
    GetIdentityPolicies: {
      name: "GetIdentityPolicies",
      input: "com.amazonaws.ses#GetIdentityPoliciesRequest",
      output: "com.amazonaws.ses#GetIdentityPoliciesResponse",
      responseWrapper: "GetIdentityPoliciesResponse",
    },
    GetIdentityVerificationAttributes: {
      name: "GetIdentityVerificationAttributes",
      input: "com.amazonaws.ses#GetIdentityVerificationAttributesRequest",
      output: "com.amazonaws.ses#GetIdentityVerificationAttributesResponse",
      responseWrapper: "GetIdentityVerificationAttributesResponse",
    },
    GetSendQuota: {
      name: "GetSendQuota",
      input: "smithy.api#Unit",
      output: "com.amazonaws.ses#GetSendQuotaResponse",
      responseWrapper: "GetSendQuotaResponse",
    },
    GetSendStatistics: {
      name: "GetSendStatistics",
      input: "smithy.api#Unit",
      output: "com.amazonaws.ses#GetSendStatisticsResponse",
      responseWrapper: "GetSendStatisticsResponse",
    },
    GetTemplate: {
      name: "GetTemplate",
      input: "com.amazonaws.ses#GetTemplateRequest",
      output: "com.amazonaws.ses#GetTemplateResponse",
      responseWrapper: "GetTemplateResponse",
    },
    ListConfigurationSets: {
      name: "ListConfigurationSets",
      input: "com.amazonaws.ses#ListConfigurationSetsRequest",
      output: "com.amazonaws.ses#ListConfigurationSetsResponse",
      responseWrapper: "ListConfigurationSetsResponse",
    },
    ListCustomVerificationEmailTemplates: {
      name: "ListCustomVerificationEmailTemplates",
      input: "com.amazonaws.ses#ListCustomVerificationEmailTemplatesRequest",
      output: "com.amazonaws.ses#ListCustomVerificationEmailTemplatesResponse",
      responseWrapper: "ListCustomVerificationEmailTemplatesResponse",
    },
    ListIdentities: {
      name: "ListIdentities",
      input: "com.amazonaws.ses#ListIdentitiesRequest",
      output: "com.amazonaws.ses#ListIdentitiesResponse",
      responseWrapper: "ListIdentitiesResponse",
    },
    ListIdentityPolicies: {
      name: "ListIdentityPolicies",
      input: "com.amazonaws.ses#ListIdentityPoliciesRequest",
      output: "com.amazonaws.ses#ListIdentityPoliciesResponse",
      responseWrapper: "ListIdentityPoliciesResponse",
    },
    ListReceiptFilters: {
      name: "ListReceiptFilters",
      input: "com.amazonaws.ses#ListReceiptFiltersRequest",
      output: "com.amazonaws.ses#ListReceiptFiltersResponse",
      responseWrapper: "ListReceiptFiltersResponse",
    },
    ListReceiptRuleSets: {
      name: "ListReceiptRuleSets",
      input: "com.amazonaws.ses#ListReceiptRuleSetsRequest",
      output: "com.amazonaws.ses#ListReceiptRuleSetsResponse",
      responseWrapper: "ListReceiptRuleSetsResponse",
    },
    ListTemplates: {
      name: "ListTemplates",
      input: "com.amazonaws.ses#ListTemplatesRequest",
      output: "com.amazonaws.ses#ListTemplatesResponse",
      responseWrapper: "ListTemplatesResponse",
    },
    ListVerifiedEmailAddresses: {
      name: "ListVerifiedEmailAddresses",
      input: "smithy.api#Unit",
      output: "com.amazonaws.ses#ListVerifiedEmailAddressesResponse",
      responseWrapper: "ListVerifiedEmailAddressesResponse",
    },
    PutConfigurationSetDeliveryOptions: {
      name: "PutConfigurationSetDeliveryOptions",
      input: "com.amazonaws.ses#PutConfigurationSetDeliveryOptionsRequest",
      output: "com.amazonaws.ses#PutConfigurationSetDeliveryOptionsResponse",
      responseWrapper: "PutConfigurationSetDeliveryOptionsResponse",
    },
    PutIdentityPolicy: {
      name: "PutIdentityPolicy",
      input: "com.amazonaws.ses#PutIdentityPolicyRequest",
      output: "com.amazonaws.ses#PutIdentityPolicyResponse",
      responseWrapper: "PutIdentityPolicyResponse",
    },
    ReorderReceiptRuleSet: {
      name: "ReorderReceiptRuleSet",
      input: "com.amazonaws.ses#ReorderReceiptRuleSetRequest",
      output: "com.amazonaws.ses#ReorderReceiptRuleSetResponse",
      responseWrapper: "ReorderReceiptRuleSetResponse",
    },
    SendBounce: {
      name: "SendBounce",
      input: "com.amazonaws.ses#SendBounceRequest",
      output: "com.amazonaws.ses#SendBounceResponse",
      responseWrapper: "SendBounceResponse",
    },
    SendBulkTemplatedEmail: {
      name: "SendBulkTemplatedEmail",
      input: "com.amazonaws.ses#SendBulkTemplatedEmailRequest",
      output: "com.amazonaws.ses#SendBulkTemplatedEmailResponse",
      responseWrapper: "SendBulkTemplatedEmailResponse",
    },
    SendCustomVerificationEmail: {
      name: "SendCustomVerificationEmail",
      input: "com.amazonaws.ses#SendCustomVerificationEmailRequest",
      output: "com.amazonaws.ses#SendCustomVerificationEmailResponse",
      responseWrapper: "SendCustomVerificationEmailResponse",
    },
    SendEmail: {
      name: "SendEmail",
      input: "com.amazonaws.ses#SendEmailRequest",
      output: "com.amazonaws.ses#SendEmailResponse",
      responseWrapper: "SendEmailResponse",
    },
    SendRawEmail: {
      name: "SendRawEmail",
      input: "com.amazonaws.ses#SendRawEmailRequest",
      output: "com.amazonaws.ses#SendRawEmailResponse",
      responseWrapper: "SendRawEmailResponse",
    },
    SendTemplatedEmail: {
      name: "SendTemplatedEmail",
      input: "com.amazonaws.ses#SendTemplatedEmailRequest",
      output: "com.amazonaws.ses#SendTemplatedEmailResponse",
      responseWrapper: "SendTemplatedEmailResponse",
    },
    SetActiveReceiptRuleSet: {
      name: "SetActiveReceiptRuleSet",
      input: "com.amazonaws.ses#SetActiveReceiptRuleSetRequest",
      output: "com.amazonaws.ses#SetActiveReceiptRuleSetResponse",
      responseWrapper: "SetActiveReceiptRuleSetResponse",
    },
    SetIdentityDkimEnabled: {
      name: "SetIdentityDkimEnabled",
      input: "com.amazonaws.ses#SetIdentityDkimEnabledRequest",
      output: "com.amazonaws.ses#SetIdentityDkimEnabledResponse",
      responseWrapper: "SetIdentityDkimEnabledResponse",
    },
    SetIdentityFeedbackForwardingEnabled: {
      name: "SetIdentityFeedbackForwardingEnabled",
      input: "com.amazonaws.ses#SetIdentityFeedbackForwardingEnabledRequest",
      output: "com.amazonaws.ses#SetIdentityFeedbackForwardingEnabledResponse",
      responseWrapper: "SetIdentityFeedbackForwardingEnabledResponse",
    },
    SetIdentityHeadersInNotificationsEnabled: {
      name: "SetIdentityHeadersInNotificationsEnabled",
      input:
        "com.amazonaws.ses#SetIdentityHeadersInNotificationsEnabledRequest",
      output:
        "com.amazonaws.ses#SetIdentityHeadersInNotificationsEnabledResponse",
      responseWrapper: "SetIdentityHeadersInNotificationsEnabledResponse",
    },
    SetIdentityMailFromDomain: {
      name: "SetIdentityMailFromDomain",
      input: "com.amazonaws.ses#SetIdentityMailFromDomainRequest",
      output: "com.amazonaws.ses#SetIdentityMailFromDomainResponse",
      responseWrapper: "SetIdentityMailFromDomainResponse",
    },
    SetIdentityNotificationTopic: {
      name: "SetIdentityNotificationTopic",
      input: "com.amazonaws.ses#SetIdentityNotificationTopicRequest",
      output: "com.amazonaws.ses#SetIdentityNotificationTopicResponse",
      responseWrapper: "SetIdentityNotificationTopicResponse",
    },
    SetReceiptRulePosition: {
      name: "SetReceiptRulePosition",
      input: "com.amazonaws.ses#SetReceiptRulePositionRequest",
      output: "com.amazonaws.ses#SetReceiptRulePositionResponse",
      responseWrapper: "SetReceiptRulePositionResponse",
    },
    TestRenderTemplate: {
      name: "TestRenderTemplate",
      input: "com.amazonaws.ses#TestRenderTemplateRequest",
      output: "com.amazonaws.ses#TestRenderTemplateResponse",
      responseWrapper: "TestRenderTemplateResponse",
    },
    UpdateAccountSendingEnabled: {
      name: "UpdateAccountSendingEnabled",
      input: "com.amazonaws.ses#UpdateAccountSendingEnabledRequest",
      output: "smithy.api#Unit",
      responseWrapper: "UpdateAccountSendingEnabledResponse",
    },
    UpdateConfigurationSetEventDestination: {
      name: "UpdateConfigurationSetEventDestination",
      input: "com.amazonaws.ses#UpdateConfigurationSetEventDestinationRequest",
      output:
        "com.amazonaws.ses#UpdateConfigurationSetEventDestinationResponse",
      responseWrapper: "UpdateConfigurationSetEventDestinationResponse",
    },
    UpdateConfigurationSetReputationMetricsEnabled: {
      name: "UpdateConfigurationSetReputationMetricsEnabled",
      input:
        "com.amazonaws.ses#UpdateConfigurationSetReputationMetricsEnabledRequest",
      output: "smithy.api#Unit",
      responseWrapper: "UpdateConfigurationSetReputationMetricsEnabledResponse",
    },
    UpdateConfigurationSetSendingEnabled: {
      name: "UpdateConfigurationSetSendingEnabled",
      input: "com.amazonaws.ses#UpdateConfigurationSetSendingEnabledRequest",
      output: "smithy.api#Unit",
      responseWrapper: "UpdateConfigurationSetSendingEnabledResponse",
    },
    UpdateConfigurationSetTrackingOptions: {
      name: "UpdateConfigurationSetTrackingOptions",
      input: "com.amazonaws.ses#UpdateConfigurationSetTrackingOptionsRequest",
      output: "com.amazonaws.ses#UpdateConfigurationSetTrackingOptionsResponse",
      responseWrapper: "UpdateConfigurationSetTrackingOptionsResponse",
    },
    UpdateCustomVerificationEmailTemplate: {
      name: "UpdateCustomVerificationEmailTemplate",
      input: "com.amazonaws.ses#UpdateCustomVerificationEmailTemplateRequest",
      output: "smithy.api#Unit",
      responseWrapper: "UpdateCustomVerificationEmailTemplateResponse",
    },
    UpdateReceiptRule: {
      name: "UpdateReceiptRule",
      input: "com.amazonaws.ses#UpdateReceiptRuleRequest",
      output: "com.amazonaws.ses#UpdateReceiptRuleResponse",
      responseWrapper: "UpdateReceiptRuleResponse",
    },
    UpdateTemplate: {
      name: "UpdateTemplate",
      input: "com.amazonaws.ses#UpdateTemplateRequest",
      output: "com.amazonaws.ses#UpdateTemplateResponse",
      responseWrapper: "UpdateTemplateResponse",
    },
    VerifyDomainDkim: {
      name: "VerifyDomainDkim",
      input: "com.amazonaws.ses#VerifyDomainDkimRequest",
      output: "com.amazonaws.ses#VerifyDomainDkimResponse",
      responseWrapper: "VerifyDomainDkimResponse",
    },
    VerifyDomainIdentity: {
      name: "VerifyDomainIdentity",
      input: "com.amazonaws.ses#VerifyDomainIdentityRequest",
      output: "com.amazonaws.ses#VerifyDomainIdentityResponse",
      responseWrapper: "VerifyDomainIdentityResponse",
    },
    VerifyEmailAddress: {
      name: "VerifyEmailAddress",
      input: "com.amazonaws.ses#VerifyEmailAddressRequest",
      output: "smithy.api#Unit",
      responseWrapper: "VerifyEmailAddressResponse",
    },
    VerifyEmailIdentity: {
      name: "VerifyEmailIdentity",
      input: "com.amazonaws.ses#VerifyEmailIdentityRequest",
      output: "com.amazonaws.ses#VerifyEmailIdentityResponse",
      responseWrapper: "VerifyEmailIdentityResponse",
    },
  },
  shapes: {
    "com.amazonaws.ses#CloneReceiptRuleSetRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
        OriginalRuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
      },
    },
    "com.amazonaws.ses#CloneReceiptRuleSetResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#CreateConfigurationSetRequest": {
      type: "structure",
      members: {
        ConfigurationSet: {
          target: "com.amazonaws.ses#ConfigurationSet",
        },
      },
    },
    "com.amazonaws.ses#CreateConfigurationSetResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#CreateConfigurationSetEventDestinationRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        EventDestination: {
          target: "com.amazonaws.ses#EventDestination",
        },
      },
    },
    "com.amazonaws.ses#CreateConfigurationSetEventDestinationResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#CreateConfigurationSetTrackingOptionsRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        TrackingOptions: {
          target: "com.amazonaws.ses#TrackingOptions",
        },
      },
    },
    "com.amazonaws.ses#CreateConfigurationSetTrackingOptionsResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#CreateCustomVerificationEmailTemplateRequest": {
      type: "structure",
      members: {
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
        FromEmailAddress: {
          target: "com.amazonaws.ses#FromAddress",
        },
        TemplateSubject: {
          target: "com.amazonaws.ses#Subject",
        },
        TemplateContent: {
          target: "com.amazonaws.ses#TemplateContent",
        },
        SuccessRedirectionURL: {
          target: "com.amazonaws.ses#SuccessRedirectionURL",
        },
        FailureRedirectionURL: {
          target: "com.amazonaws.ses#FailureRedirectionURL",
        },
      },
    },
    "com.amazonaws.ses#CreateReceiptFilterRequest": {
      type: "structure",
      members: {
        Filter: {
          target: "com.amazonaws.ses#ReceiptFilter",
        },
      },
    },
    "com.amazonaws.ses#CreateReceiptFilterResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#CreateReceiptRuleRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
        After: {
          target: "com.amazonaws.ses#ReceiptRuleName",
        },
        Rule: {
          target: "com.amazonaws.ses#ReceiptRule",
        },
      },
    },
    "com.amazonaws.ses#CreateReceiptRuleResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#CreateReceiptRuleSetRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
      },
    },
    "com.amazonaws.ses#CreateReceiptRuleSetResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#CreateTemplateRequest": {
      type: "structure",
      members: {
        Template: {
          target: "com.amazonaws.ses#Template",
        },
      },
    },
    "com.amazonaws.ses#CreateTemplateResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DeleteConfigurationSetRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
      },
    },
    "com.amazonaws.ses#DeleteConfigurationSetResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DeleteConfigurationSetEventDestinationRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        EventDestinationName: {
          target: "com.amazonaws.ses#EventDestinationName",
        },
      },
    },
    "com.amazonaws.ses#DeleteConfigurationSetEventDestinationResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DeleteConfigurationSetTrackingOptionsRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
      },
    },
    "com.amazonaws.ses#DeleteConfigurationSetTrackingOptionsResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DeleteCustomVerificationEmailTemplateRequest": {
      type: "structure",
      members: {
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
      },
    },
    "com.amazonaws.ses#DeleteIdentityRequest": {
      type: "structure",
      members: {
        Identity: {
          target: "com.amazonaws.ses#Identity",
        },
      },
    },
    "com.amazonaws.ses#DeleteIdentityResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DeleteIdentityPolicyRequest": {
      type: "structure",
      members: {
        Identity: {
          target: "com.amazonaws.ses#Identity",
        },
        PolicyName: {
          target: "com.amazonaws.ses#PolicyName",
        },
      },
    },
    "com.amazonaws.ses#DeleteIdentityPolicyResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DeleteReceiptFilterRequest": {
      type: "structure",
      members: {
        FilterName: {
          target: "com.amazonaws.ses#ReceiptFilterName",
        },
      },
    },
    "com.amazonaws.ses#DeleteReceiptFilterResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DeleteReceiptRuleRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
        RuleName: {
          target: "com.amazonaws.ses#ReceiptRuleName",
        },
      },
    },
    "com.amazonaws.ses#DeleteReceiptRuleResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DeleteReceiptRuleSetRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
      },
    },
    "com.amazonaws.ses#DeleteReceiptRuleSetResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DeleteTemplateRequest": {
      type: "structure",
      members: {
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
      },
    },
    "com.amazonaws.ses#DeleteTemplateResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DeleteVerifiedEmailAddressRequest": {
      type: "structure",
      members: {
        EmailAddress: {
          target: "com.amazonaws.ses#Address",
        },
      },
    },
    "com.amazonaws.ses#DescribeActiveReceiptRuleSetRequest": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#DescribeActiveReceiptRuleSetResponse": {
      type: "structure",
      members: {
        Metadata: {
          target: "com.amazonaws.ses#ReceiptRuleSetMetadata",
        },
        Rules: {
          target: "com.amazonaws.ses#ReceiptRulesList",
        },
      },
    },
    "com.amazonaws.ses#DescribeConfigurationSetRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        ConfigurationSetAttributeNames: {
          target: "com.amazonaws.ses#ConfigurationSetAttributeList",
        },
      },
    },
    "com.amazonaws.ses#DescribeConfigurationSetResponse": {
      type: "structure",
      members: {
        ConfigurationSet: {
          target: "com.amazonaws.ses#ConfigurationSet",
        },
        EventDestinations: {
          target: "com.amazonaws.ses#EventDestinations",
        },
        TrackingOptions: {
          target: "com.amazonaws.ses#TrackingOptions",
        },
        DeliveryOptions: {
          target: "com.amazonaws.ses#DeliveryOptions",
        },
        ReputationOptions: {
          target: "com.amazonaws.ses#ReputationOptions",
        },
      },
    },
    "com.amazonaws.ses#DescribeReceiptRuleRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
        RuleName: {
          target: "com.amazonaws.ses#ReceiptRuleName",
        },
      },
    },
    "com.amazonaws.ses#DescribeReceiptRuleResponse": {
      type: "structure",
      members: {
        Rule: {
          target: "com.amazonaws.ses#ReceiptRule",
        },
      },
    },
    "com.amazonaws.ses#DescribeReceiptRuleSetRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
      },
    },
    "com.amazonaws.ses#DescribeReceiptRuleSetResponse": {
      type: "structure",
      members: {
        Metadata: {
          target: "com.amazonaws.ses#ReceiptRuleSetMetadata",
        },
        Rules: {
          target: "com.amazonaws.ses#ReceiptRulesList",
        },
      },
    },
    "com.amazonaws.ses#GetAccountSendingEnabledResponse": {
      type: "structure",
      members: {
        Enabled: {
          target: "com.amazonaws.ses#Enabled",
        },
      },
    },
    "com.amazonaws.ses#GetCustomVerificationEmailTemplateRequest": {
      type: "structure",
      members: {
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
      },
    },
    "com.amazonaws.ses#GetCustomVerificationEmailTemplateResponse": {
      type: "structure",
      members: {
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
        FromEmailAddress: {
          target: "com.amazonaws.ses#FromAddress",
        },
        TemplateSubject: {
          target: "com.amazonaws.ses#Subject",
        },
        TemplateContent: {
          target: "com.amazonaws.ses#TemplateContent",
        },
        SuccessRedirectionURL: {
          target: "com.amazonaws.ses#SuccessRedirectionURL",
        },
        FailureRedirectionURL: {
          target: "com.amazonaws.ses#FailureRedirectionURL",
        },
      },
    },
    "com.amazonaws.ses#GetIdentityDkimAttributesRequest": {
      type: "structure",
      members: {
        Identities: {
          target: "com.amazonaws.ses#IdentityList",
        },
      },
    },
    "com.amazonaws.ses#GetIdentityDkimAttributesResponse": {
      type: "structure",
      members: {
        DkimAttributes: {
          target: "com.amazonaws.ses#DkimAttributes",
        },
      },
    },
    "com.amazonaws.ses#GetIdentityMailFromDomainAttributesRequest": {
      type: "structure",
      members: {
        Identities: {
          target: "com.amazonaws.ses#IdentityList",
        },
      },
    },
    "com.amazonaws.ses#GetIdentityMailFromDomainAttributesResponse": {
      type: "structure",
      members: {
        MailFromDomainAttributes: {
          target: "com.amazonaws.ses#MailFromDomainAttributes",
        },
      },
    },
    "com.amazonaws.ses#GetIdentityNotificationAttributesRequest": {
      type: "structure",
      members: {
        Identities: {
          target: "com.amazonaws.ses#IdentityList",
        },
      },
    },
    "com.amazonaws.ses#GetIdentityNotificationAttributesResponse": {
      type: "structure",
      members: {
        NotificationAttributes: {
          target: "com.amazonaws.ses#NotificationAttributes",
        },
      },
    },
    "com.amazonaws.ses#GetIdentityPoliciesRequest": {
      type: "structure",
      members: {
        Identity: {
          target: "com.amazonaws.ses#Identity",
        },
        PolicyNames: {
          target: "com.amazonaws.ses#PolicyNameList",
        },
      },
    },
    "com.amazonaws.ses#GetIdentityPoliciesResponse": {
      type: "structure",
      members: {
        Policies: {
          target: "com.amazonaws.ses#PolicyMap",
        },
      },
    },
    "com.amazonaws.ses#GetIdentityVerificationAttributesRequest": {
      type: "structure",
      members: {
        Identities: {
          target: "com.amazonaws.ses#IdentityList",
        },
      },
    },
    "com.amazonaws.ses#GetIdentityVerificationAttributesResponse": {
      type: "structure",
      members: {
        VerificationAttributes: {
          target: "com.amazonaws.ses#VerificationAttributes",
        },
      },
    },
    "com.amazonaws.ses#GetSendQuotaResponse": {
      type: "structure",
      members: {
        Max24HourSend: {
          target: "com.amazonaws.ses#Max24HourSend",
        },
        MaxSendRate: {
          target: "com.amazonaws.ses#MaxSendRate",
        },
        SentLast24Hours: {
          target: "com.amazonaws.ses#SentLast24Hours",
        },
      },
    },
    "com.amazonaws.ses#GetSendStatisticsResponse": {
      type: "structure",
      members: {
        SendDataPoints: {
          target: "com.amazonaws.ses#SendDataPointList",
        },
      },
    },
    "com.amazonaws.ses#GetTemplateRequest": {
      type: "structure",
      members: {
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
      },
    },
    "com.amazonaws.ses#GetTemplateResponse": {
      type: "structure",
      members: {
        Template: {
          target: "com.amazonaws.ses#Template",
        },
      },
    },
    "com.amazonaws.ses#ListConfigurationSetsRequest": {
      type: "structure",
      members: {
        NextToken: {
          target: "com.amazonaws.ses#NextToken",
        },
        MaxItems: {
          target: "com.amazonaws.ses#MaxItems",
        },
      },
    },
    "com.amazonaws.ses#ListConfigurationSetsResponse": {
      type: "structure",
      members: {
        ConfigurationSets: {
          target: "com.amazonaws.ses#ConfigurationSets",
        },
        NextToken: {
          target: "com.amazonaws.ses#NextToken",
        },
      },
    },
    "com.amazonaws.ses#ListCustomVerificationEmailTemplatesRequest": {
      type: "structure",
      members: {
        NextToken: {
          target: "com.amazonaws.ses#NextToken",
        },
        MaxResults: {
          target: "com.amazonaws.ses#MaxResults",
        },
      },
    },
    "com.amazonaws.ses#ListCustomVerificationEmailTemplatesResponse": {
      type: "structure",
      members: {
        CustomVerificationEmailTemplates: {
          target: "com.amazonaws.ses#CustomVerificationEmailTemplates",
        },
        NextToken: {
          target: "com.amazonaws.ses#NextToken",
        },
      },
    },
    "com.amazonaws.ses#ListIdentitiesRequest": {
      type: "structure",
      members: {
        IdentityType: {
          target: "com.amazonaws.ses#IdentityType",
        },
        NextToken: {
          target: "com.amazonaws.ses#NextToken",
        },
        MaxItems: {
          target: "com.amazonaws.ses#MaxItems",
        },
      },
    },
    "com.amazonaws.ses#ListIdentitiesResponse": {
      type: "structure",
      members: {
        Identities: {
          target: "com.amazonaws.ses#IdentityList",
        },
        NextToken: {
          target: "com.amazonaws.ses#NextToken",
        },
      },
    },
    "com.amazonaws.ses#ListIdentityPoliciesRequest": {
      type: "structure",
      members: {
        Identity: {
          target: "com.amazonaws.ses#Identity",
        },
      },
    },
    "com.amazonaws.ses#ListIdentityPoliciesResponse": {
      type: "structure",
      members: {
        PolicyNames: {
          target: "com.amazonaws.ses#PolicyNameList",
        },
      },
    },
    "com.amazonaws.ses#ListReceiptFiltersRequest": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#ListReceiptFiltersResponse": {
      type: "structure",
      members: {
        Filters: {
          target: "com.amazonaws.ses#ReceiptFilterList",
        },
      },
    },
    "com.amazonaws.ses#ListReceiptRuleSetsRequest": {
      type: "structure",
      members: {
        NextToken: {
          target: "com.amazonaws.ses#NextToken",
        },
      },
    },
    "com.amazonaws.ses#ListReceiptRuleSetsResponse": {
      type: "structure",
      members: {
        RuleSets: {
          target: "com.amazonaws.ses#ReceiptRuleSetsLists",
        },
        NextToken: {
          target: "com.amazonaws.ses#NextToken",
        },
      },
    },
    "com.amazonaws.ses#ListTemplatesRequest": {
      type: "structure",
      members: {
        NextToken: {
          target: "com.amazonaws.ses#NextToken",
        },
        MaxItems: {
          target: "com.amazonaws.ses#MaxItems",
        },
      },
    },
    "com.amazonaws.ses#ListTemplatesResponse": {
      type: "structure",
      members: {
        TemplatesMetadata: {
          target: "com.amazonaws.ses#TemplateMetadataList",
        },
        NextToken: {
          target: "com.amazonaws.ses#NextToken",
        },
      },
    },
    "com.amazonaws.ses#ListVerifiedEmailAddressesResponse": {
      type: "structure",
      members: {
        VerifiedEmailAddresses: {
          target: "com.amazonaws.ses#AddressList",
        },
      },
    },
    "com.amazonaws.ses#PutConfigurationSetDeliveryOptionsRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        DeliveryOptions: {
          target: "com.amazonaws.ses#DeliveryOptions",
        },
      },
    },
    "com.amazonaws.ses#PutConfigurationSetDeliveryOptionsResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#PutIdentityPolicyRequest": {
      type: "structure",
      members: {
        Identity: {
          target: "com.amazonaws.ses#Identity",
        },
        PolicyName: {
          target: "com.amazonaws.ses#PolicyName",
        },
        Policy: {
          target: "com.amazonaws.ses#Policy",
        },
      },
    },
    "com.amazonaws.ses#PutIdentityPolicyResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#ReorderReceiptRuleSetRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
        RuleNames: {
          target: "com.amazonaws.ses#ReceiptRuleNamesList",
        },
      },
    },
    "com.amazonaws.ses#ReorderReceiptRuleSetResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#SendBounceRequest": {
      type: "structure",
      members: {
        OriginalMessageId: {
          target: "com.amazonaws.ses#MessageId",
        },
        BounceSender: {
          target: "com.amazonaws.ses#Address",
        },
        Explanation: {
          target: "com.amazonaws.ses#Explanation",
        },
        MessageDsn: {
          target: "com.amazonaws.ses#MessageDsn",
        },
        BouncedRecipientInfoList: {
          target: "com.amazonaws.ses#BouncedRecipientInfoList",
        },
        BounceSenderArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
      },
    },
    "com.amazonaws.ses#SendBounceResponse": {
      type: "structure",
      members: {
        MessageId: {
          target: "com.amazonaws.ses#MessageId",
        },
      },
    },
    "com.amazonaws.ses#SendBulkTemplatedEmailRequest": {
      type: "structure",
      members: {
        Source: {
          target: "com.amazonaws.ses#Address",
        },
        SourceArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        ReplyToAddresses: {
          target: "com.amazonaws.ses#AddressList",
        },
        ReturnPath: {
          target: "com.amazonaws.ses#Address",
        },
        ReturnPathArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        DefaultTags: {
          target: "com.amazonaws.ses#MessageTagList",
        },
        Template: {
          target: "com.amazonaws.ses#TemplateName",
        },
        TemplateArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        DefaultTemplateData: {
          target: "com.amazonaws.ses#TemplateData",
        },
        Destinations: {
          target: "com.amazonaws.ses#BulkEmailDestinationList",
        },
      },
    },
    "com.amazonaws.ses#SendBulkTemplatedEmailResponse": {
      type: "structure",
      members: {
        Status: {
          target: "com.amazonaws.ses#BulkEmailDestinationStatusList",
        },
      },
    },
    "com.amazonaws.ses#SendCustomVerificationEmailRequest": {
      type: "structure",
      members: {
        EmailAddress: {
          target: "com.amazonaws.ses#Address",
        },
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
      },
    },
    "com.amazonaws.ses#SendCustomVerificationEmailResponse": {
      type: "structure",
      members: {
        MessageId: {
          target: "com.amazonaws.ses#MessageId",
        },
      },
    },
    "com.amazonaws.ses#SendEmailRequest": {
      type: "structure",
      members: {
        Source: {
          target: "com.amazonaws.ses#Address",
        },
        Destination: {
          target: "com.amazonaws.ses#Destination",
        },
        Message: {
          target: "com.amazonaws.ses#Message",
        },
        ReplyToAddresses: {
          target: "com.amazonaws.ses#AddressList",
        },
        ReturnPath: {
          target: "com.amazonaws.ses#Address",
        },
        SourceArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        ReturnPathArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        Tags: {
          target: "com.amazonaws.ses#MessageTagList",
        },
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
      },
    },
    "com.amazonaws.ses#SendEmailResponse": {
      type: "structure",
      members: {
        MessageId: {
          target: "com.amazonaws.ses#MessageId",
        },
      },
    },
    "com.amazonaws.ses#SendRawEmailRequest": {
      type: "structure",
      members: {
        Source: {
          target: "com.amazonaws.ses#Address",
        },
        Destinations: {
          target: "com.amazonaws.ses#AddressList",
        },
        RawMessage: {
          target: "com.amazonaws.ses#RawMessage",
        },
        FromArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        SourceArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        ReturnPathArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        Tags: {
          target: "com.amazonaws.ses#MessageTagList",
        },
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
      },
    },
    "com.amazonaws.ses#SendRawEmailResponse": {
      type: "structure",
      members: {
        MessageId: {
          target: "com.amazonaws.ses#MessageId",
        },
      },
    },
    "com.amazonaws.ses#SendTemplatedEmailRequest": {
      type: "structure",
      members: {
        Source: {
          target: "com.amazonaws.ses#Address",
        },
        Destination: {
          target: "com.amazonaws.ses#Destination",
        },
        ReplyToAddresses: {
          target: "com.amazonaws.ses#AddressList",
        },
        ReturnPath: {
          target: "com.amazonaws.ses#Address",
        },
        SourceArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        ReturnPathArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        Tags: {
          target: "com.amazonaws.ses#MessageTagList",
        },
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        Template: {
          target: "com.amazonaws.ses#TemplateName",
        },
        TemplateArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        TemplateData: {
          target: "com.amazonaws.ses#TemplateData",
        },
      },
    },
    "com.amazonaws.ses#SendTemplatedEmailResponse": {
      type: "structure",
      members: {
        MessageId: {
          target: "com.amazonaws.ses#MessageId",
        },
      },
    },
    "com.amazonaws.ses#SetActiveReceiptRuleSetRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
      },
    },
    "com.amazonaws.ses#SetActiveReceiptRuleSetResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#SetIdentityDkimEnabledRequest": {
      type: "structure",
      members: {
        Identity: {
          target: "com.amazonaws.ses#Identity",
        },
        DkimEnabled: {
          target: "com.amazonaws.ses#Enabled",
        },
      },
    },
    "com.amazonaws.ses#SetIdentityDkimEnabledResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#SetIdentityFeedbackForwardingEnabledRequest": {
      type: "structure",
      members: {
        Identity: {
          target: "com.amazonaws.ses#Identity",
        },
        ForwardingEnabled: {
          target: "com.amazonaws.ses#Enabled",
        },
      },
    },
    "com.amazonaws.ses#SetIdentityFeedbackForwardingEnabledResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#SetIdentityHeadersInNotificationsEnabledRequest": {
      type: "structure",
      members: {
        Identity: {
          target: "com.amazonaws.ses#Identity",
        },
        NotificationType: {
          target: "com.amazonaws.ses#NotificationType",
        },
        Enabled: {
          target: "com.amazonaws.ses#Enabled",
        },
      },
    },
    "com.amazonaws.ses#SetIdentityHeadersInNotificationsEnabledResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#SetIdentityMailFromDomainRequest": {
      type: "structure",
      members: {
        Identity: {
          target: "com.amazonaws.ses#Identity",
        },
        MailFromDomain: {
          target: "com.amazonaws.ses#MailFromDomainName",
        },
        BehaviorOnMXFailure: {
          target: "com.amazonaws.ses#BehaviorOnMXFailure",
        },
      },
    },
    "com.amazonaws.ses#SetIdentityMailFromDomainResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#SetIdentityNotificationTopicRequest": {
      type: "structure",
      members: {
        Identity: {
          target: "com.amazonaws.ses#Identity",
        },
        NotificationType: {
          target: "com.amazonaws.ses#NotificationType",
        },
        SnsTopic: {
          target: "com.amazonaws.ses#NotificationTopic",
        },
      },
    },
    "com.amazonaws.ses#SetIdentityNotificationTopicResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#SetReceiptRulePositionRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
        RuleName: {
          target: "com.amazonaws.ses#ReceiptRuleName",
        },
        After: {
          target: "com.amazonaws.ses#ReceiptRuleName",
        },
      },
    },
    "com.amazonaws.ses#SetReceiptRulePositionResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#TestRenderTemplateRequest": {
      type: "structure",
      members: {
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
        TemplateData: {
          target: "com.amazonaws.ses#TemplateData",
        },
      },
    },
    "com.amazonaws.ses#TestRenderTemplateResponse": {
      type: "structure",
      members: {
        RenderedTemplate: {
          target: "com.amazonaws.ses#RenderedTemplate",
        },
      },
    },
    "com.amazonaws.ses#UpdateAccountSendingEnabledRequest": {
      type: "structure",
      members: {
        Enabled: {
          target: "com.amazonaws.ses#Enabled",
        },
      },
    },
    "com.amazonaws.ses#UpdateConfigurationSetEventDestinationRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        EventDestination: {
          target: "com.amazonaws.ses#EventDestination",
        },
      },
    },
    "com.amazonaws.ses#UpdateConfigurationSetEventDestinationResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#UpdateConfigurationSetReputationMetricsEnabledRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        Enabled: {
          target: "com.amazonaws.ses#Enabled",
        },
      },
    },
    "com.amazonaws.ses#UpdateConfigurationSetSendingEnabledRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        Enabled: {
          target: "com.amazonaws.ses#Enabled",
        },
      },
    },
    "com.amazonaws.ses#UpdateConfigurationSetTrackingOptionsRequest": {
      type: "structure",
      members: {
        ConfigurationSetName: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
        TrackingOptions: {
          target: "com.amazonaws.ses#TrackingOptions",
        },
      },
    },
    "com.amazonaws.ses#UpdateConfigurationSetTrackingOptionsResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#UpdateCustomVerificationEmailTemplateRequest": {
      type: "structure",
      members: {
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
        FromEmailAddress: {
          target: "com.amazonaws.ses#FromAddress",
        },
        TemplateSubject: {
          target: "com.amazonaws.ses#Subject",
        },
        TemplateContent: {
          target: "com.amazonaws.ses#TemplateContent",
        },
        SuccessRedirectionURL: {
          target: "com.amazonaws.ses#SuccessRedirectionURL",
        },
        FailureRedirectionURL: {
          target: "com.amazonaws.ses#FailureRedirectionURL",
        },
      },
    },
    "com.amazonaws.ses#UpdateReceiptRuleRequest": {
      type: "structure",
      members: {
        RuleSetName: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
        Rule: {
          target: "com.amazonaws.ses#ReceiptRule",
        },
      },
    },
    "com.amazonaws.ses#UpdateReceiptRuleResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#UpdateTemplateRequest": {
      type: "structure",
      members: {
        Template: {
          target: "com.amazonaws.ses#Template",
        },
      },
    },
    "com.amazonaws.ses#UpdateTemplateResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#VerifyDomainDkimRequest": {
      type: "structure",
      members: {
        Domain: {
          target: "com.amazonaws.ses#Domain",
        },
      },
    },
    "com.amazonaws.ses#VerifyDomainDkimResponse": {
      type: "structure",
      members: {
        DkimTokens: {
          target: "com.amazonaws.ses#VerificationTokenList",
        },
      },
    },
    "com.amazonaws.ses#VerifyDomainIdentityRequest": {
      type: "structure",
      members: {
        Domain: {
          target: "com.amazonaws.ses#Domain",
        },
      },
    },
    "com.amazonaws.ses#VerifyDomainIdentityResponse": {
      type: "structure",
      members: {
        VerificationToken: {
          target: "com.amazonaws.ses#VerificationToken",
        },
      },
    },
    "com.amazonaws.ses#VerifyEmailAddressRequest": {
      type: "structure",
      members: {
        EmailAddress: {
          target: "com.amazonaws.ses#Address",
        },
      },
    },
    "com.amazonaws.ses#VerifyEmailIdentityRequest": {
      type: "structure",
      members: {
        EmailAddress: {
          target: "com.amazonaws.ses#Address",
        },
      },
    },
    "com.amazonaws.ses#VerifyEmailIdentityResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.ses#ReceiptRuleSetName": {
      type: "string",
    },
    "com.amazonaws.ses#ConfigurationSet": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.ses#ConfigurationSetName",
        },
      },
    },
    "com.amazonaws.ses#ConfigurationSetName": {
      type: "string",
    },
    "com.amazonaws.ses#EventDestination": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.ses#EventDestinationName",
        },
        Enabled: {
          target: "com.amazonaws.ses#Enabled",
        },
        MatchingEventTypes: {
          target: "com.amazonaws.ses#EventTypes",
        },
        KinesisFirehoseDestination: {
          target: "com.amazonaws.ses#KinesisFirehoseDestination",
        },
        CloudWatchDestination: {
          target: "com.amazonaws.ses#CloudWatchDestination",
        },
        SNSDestination: {
          target: "com.amazonaws.ses#SNSDestination",
        },
      },
    },
    "com.amazonaws.ses#EventDestinationName": {
      type: "string",
    },
    "com.amazonaws.ses#Enabled": {
      type: "boolean",
    },
    "com.amazonaws.ses#EventTypes": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#EventType",
      },
    },
    "com.amazonaws.ses#EventType": {
      type: "enum",
    },
    "com.amazonaws.ses#KinesisFirehoseDestination": {
      type: "structure",
      members: {
        IAMRoleARN: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        DeliveryStreamARN: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
      },
    },
    "com.amazonaws.ses#AmazonResourceName": {
      type: "string",
    },
    "com.amazonaws.ses#CloudWatchDestination": {
      type: "structure",
      members: {
        DimensionConfigurations: {
          target: "com.amazonaws.ses#CloudWatchDimensionConfigurations",
        },
      },
    },
    "com.amazonaws.ses#CloudWatchDimensionConfigurations": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#CloudWatchDimensionConfiguration",
      },
    },
    "com.amazonaws.ses#CloudWatchDimensionConfiguration": {
      type: "structure",
      members: {
        DimensionName: {
          target: "com.amazonaws.ses#DimensionName",
        },
        DimensionValueSource: {
          target: "com.amazonaws.ses#DimensionValueSource",
        },
        DefaultDimensionValue: {
          target: "com.amazonaws.ses#DefaultDimensionValue",
        },
      },
    },
    "com.amazonaws.ses#DimensionName": {
      type: "string",
    },
    "com.amazonaws.ses#DimensionValueSource": {
      type: "enum",
    },
    "com.amazonaws.ses#DefaultDimensionValue": {
      type: "string",
    },
    "com.amazonaws.ses#SNSDestination": {
      type: "structure",
      members: {
        TopicARN: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
      },
    },
    "com.amazonaws.ses#TrackingOptions": {
      type: "structure",
      members: {
        CustomRedirectDomain: {
          target: "com.amazonaws.ses#CustomRedirectDomain",
        },
      },
    },
    "com.amazonaws.ses#CustomRedirectDomain": {
      type: "string",
    },
    "com.amazonaws.ses#TemplateName": {
      type: "string",
    },
    "com.amazonaws.ses#FromAddress": {
      type: "string",
    },
    "com.amazonaws.ses#Subject": {
      type: "string",
    },
    "com.amazonaws.ses#TemplateContent": {
      type: "string",
    },
    "com.amazonaws.ses#SuccessRedirectionURL": {
      type: "string",
    },
    "com.amazonaws.ses#FailureRedirectionURL": {
      type: "string",
    },
    "com.amazonaws.ses#ReceiptFilter": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.ses#ReceiptFilterName",
        },
        IpFilter: {
          target: "com.amazonaws.ses#ReceiptIpFilter",
        },
      },
    },
    "com.amazonaws.ses#ReceiptFilterName": {
      type: "string",
    },
    "com.amazonaws.ses#ReceiptIpFilter": {
      type: "structure",
      members: {
        Policy: {
          target: "com.amazonaws.ses#ReceiptFilterPolicy",
        },
        Cidr: {
          target: "com.amazonaws.ses#Cidr",
        },
      },
    },
    "com.amazonaws.ses#ReceiptFilterPolicy": {
      type: "enum",
    },
    "com.amazonaws.ses#Cidr": {
      type: "string",
    },
    "com.amazonaws.ses#ReceiptRuleName": {
      type: "string",
    },
    "com.amazonaws.ses#ReceiptRule": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.ses#ReceiptRuleName",
        },
        Enabled: {
          target: "com.amazonaws.ses#Enabled",
        },
        TlsPolicy: {
          target: "com.amazonaws.ses#TlsPolicy",
        },
        Recipients: {
          target: "com.amazonaws.ses#RecipientsList",
        },
        Actions: {
          target: "com.amazonaws.ses#ReceiptActionsList",
        },
        ScanEnabled: {
          target: "com.amazonaws.ses#Enabled",
        },
      },
    },
    "com.amazonaws.ses#TlsPolicy": {
      type: "enum",
    },
    "com.amazonaws.ses#RecipientsList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#Recipient",
      },
    },
    "com.amazonaws.ses#Recipient": {
      type: "string",
    },
    "com.amazonaws.ses#ReceiptActionsList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#ReceiptAction",
      },
    },
    "com.amazonaws.ses#ReceiptAction": {
      type: "structure",
      members: {
        S3Action: {
          target: "com.amazonaws.ses#S3Action",
        },
        BounceAction: {
          target: "com.amazonaws.ses#BounceAction",
        },
        WorkmailAction: {
          target: "com.amazonaws.ses#WorkmailAction",
        },
        LambdaAction: {
          target: "com.amazonaws.ses#LambdaAction",
        },
        StopAction: {
          target: "com.amazonaws.ses#StopAction",
        },
        AddHeaderAction: {
          target: "com.amazonaws.ses#AddHeaderAction",
        },
        SNSAction: {
          target: "com.amazonaws.ses#SNSAction",
        },
        ConnectAction: {
          target: "com.amazonaws.ses#ConnectAction",
        },
      },
    },
    "com.amazonaws.ses#S3Action": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        BucketName: {
          target: "com.amazonaws.ses#S3BucketName",
        },
        ObjectKeyPrefix: {
          target: "com.amazonaws.ses#S3KeyPrefix",
        },
        KmsKeyArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        IamRoleArn: {
          target: "com.amazonaws.ses#IAMRoleARN",
        },
      },
    },
    "com.amazonaws.ses#S3BucketName": {
      type: "string",
    },
    "com.amazonaws.ses#S3KeyPrefix": {
      type: "string",
    },
    "com.amazonaws.ses#IAMRoleARN": {
      type: "string",
    },
    "com.amazonaws.ses#BounceAction": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        SmtpReplyCode: {
          target: "com.amazonaws.ses#BounceSmtpReplyCode",
        },
        StatusCode: {
          target: "com.amazonaws.ses#BounceStatusCode",
        },
        Message: {
          target: "com.amazonaws.ses#BounceMessage",
        },
        Sender: {
          target: "com.amazonaws.ses#Address",
        },
      },
    },
    "com.amazonaws.ses#BounceSmtpReplyCode": {
      type: "string",
    },
    "com.amazonaws.ses#BounceStatusCode": {
      type: "string",
    },
    "com.amazonaws.ses#BounceMessage": {
      type: "string",
    },
    "com.amazonaws.ses#Address": {
      type: "string",
    },
    "com.amazonaws.ses#WorkmailAction": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        OrganizationArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
      },
    },
    "com.amazonaws.ses#LambdaAction": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        FunctionArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        InvocationType: {
          target: "com.amazonaws.ses#InvocationType",
        },
      },
    },
    "com.amazonaws.ses#InvocationType": {
      type: "enum",
    },
    "com.amazonaws.ses#StopAction": {
      type: "structure",
      members: {
        Scope: {
          target: "com.amazonaws.ses#StopScope",
        },
        TopicArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
      },
    },
    "com.amazonaws.ses#StopScope": {
      type: "enum",
    },
    "com.amazonaws.ses#AddHeaderAction": {
      type: "structure",
      members: {
        HeaderName: {
          target: "com.amazonaws.ses#HeaderName",
        },
        HeaderValue: {
          target: "com.amazonaws.ses#HeaderValue",
        },
      },
    },
    "com.amazonaws.ses#HeaderName": {
      type: "string",
    },
    "com.amazonaws.ses#HeaderValue": {
      type: "string",
    },
    "com.amazonaws.ses#SNSAction": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        Encoding: {
          target: "com.amazonaws.ses#SNSActionEncoding",
        },
      },
    },
    "com.amazonaws.ses#SNSActionEncoding": {
      type: "enum",
    },
    "com.amazonaws.ses#ConnectAction": {
      type: "structure",
      members: {
        InstanceARN: {
          target: "com.amazonaws.ses#ConnectInstanceArn",
        },
        IAMRoleARN: {
          target: "com.amazonaws.ses#IAMRoleARN",
        },
      },
    },
    "com.amazonaws.ses#ConnectInstanceArn": {
      type: "string",
    },
    "com.amazonaws.ses#Template": {
      type: "structure",
      members: {
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
        SubjectPart: {
          target: "com.amazonaws.ses#SubjectPart",
        },
        TextPart: {
          target: "com.amazonaws.ses#TextPart",
        },
        HtmlPart: {
          target: "com.amazonaws.ses#HtmlPart",
        },
      },
    },
    "com.amazonaws.ses#SubjectPart": {
      type: "string",
    },
    "com.amazonaws.ses#TextPart": {
      type: "string",
    },
    "com.amazonaws.ses#HtmlPart": {
      type: "string",
    },
    "com.amazonaws.ses#Identity": {
      type: "string",
    },
    "com.amazonaws.ses#PolicyName": {
      type: "string",
    },
    "com.amazonaws.ses#ReceiptRuleSetMetadata": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.ses#ReceiptRuleSetName",
        },
        CreatedTimestamp: {
          target: "com.amazonaws.ses#Timestamp",
        },
      },
    },
    "com.amazonaws.ses#Timestamp": {
      type: "timestamp",
    },
    "com.amazonaws.ses#ReceiptRulesList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#ReceiptRule",
      },
    },
    "com.amazonaws.ses#ConfigurationSetAttributeList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#ConfigurationSetAttribute",
      },
    },
    "com.amazonaws.ses#ConfigurationSetAttribute": {
      type: "enum",
    },
    "com.amazonaws.ses#EventDestinations": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#EventDestination",
      },
    },
    "com.amazonaws.ses#DeliveryOptions": {
      type: "structure",
      members: {
        TlsPolicy: {
          target: "com.amazonaws.ses#TlsPolicy",
        },
      },
    },
    "com.amazonaws.ses#ReputationOptions": {
      type: "structure",
      members: {
        SendingEnabled: {
          target: "com.amazonaws.ses#Enabled",
        },
        ReputationMetricsEnabled: {
          target: "com.amazonaws.ses#Enabled",
        },
        LastFreshStart: {
          target: "com.amazonaws.ses#LastFreshStart",
        },
      },
    },
    "com.amazonaws.ses#LastFreshStart": {
      type: "timestamp",
    },
    "com.amazonaws.ses#IdentityList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#Identity",
      },
    },
    "com.amazonaws.ses#DkimAttributes": {
      type: "map",
      key: {
        target: "com.amazonaws.ses#Identity",
      },
      value: {
        target: "com.amazonaws.ses#IdentityDkimAttributes",
      },
    },
    "com.amazonaws.ses#IdentityDkimAttributes": {
      type: "structure",
      members: {
        DkimEnabled: {
          target: "com.amazonaws.ses#Enabled",
        },
        DkimVerificationStatus: {
          target: "com.amazonaws.ses#VerificationStatus",
        },
        DkimTokens: {
          target: "com.amazonaws.ses#VerificationTokenList",
        },
      },
    },
    "com.amazonaws.ses#VerificationStatus": {
      type: "enum",
    },
    "com.amazonaws.ses#VerificationTokenList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#VerificationToken",
      },
    },
    "com.amazonaws.ses#VerificationToken": {
      type: "string",
    },
    "com.amazonaws.ses#MailFromDomainAttributes": {
      type: "map",
      key: {
        target: "com.amazonaws.ses#Identity",
      },
      value: {
        target: "com.amazonaws.ses#IdentityMailFromDomainAttributes",
      },
    },
    "com.amazonaws.ses#IdentityMailFromDomainAttributes": {
      type: "structure",
      members: {
        MailFromDomain: {
          target: "com.amazonaws.ses#MailFromDomainName",
        },
        MailFromDomainStatus: {
          target: "com.amazonaws.ses#CustomMailFromStatus",
        },
        BehaviorOnMXFailure: {
          target: "com.amazonaws.ses#BehaviorOnMXFailure",
        },
      },
    },
    "com.amazonaws.ses#MailFromDomainName": {
      type: "string",
    },
    "com.amazonaws.ses#CustomMailFromStatus": {
      type: "enum",
    },
    "com.amazonaws.ses#BehaviorOnMXFailure": {
      type: "enum",
    },
    "com.amazonaws.ses#NotificationAttributes": {
      type: "map",
      key: {
        target: "com.amazonaws.ses#Identity",
      },
      value: {
        target: "com.amazonaws.ses#IdentityNotificationAttributes",
      },
    },
    "com.amazonaws.ses#IdentityNotificationAttributes": {
      type: "structure",
      members: {
        BounceTopic: {
          target: "com.amazonaws.ses#NotificationTopic",
        },
        ComplaintTopic: {
          target: "com.amazonaws.ses#NotificationTopic",
        },
        DeliveryTopic: {
          target: "com.amazonaws.ses#NotificationTopic",
        },
        ForwardingEnabled: {
          target: "com.amazonaws.ses#Enabled",
        },
        HeadersInBounceNotificationsEnabled: {
          target: "com.amazonaws.ses#Enabled",
        },
        HeadersInComplaintNotificationsEnabled: {
          target: "com.amazonaws.ses#Enabled",
        },
        HeadersInDeliveryNotificationsEnabled: {
          target: "com.amazonaws.ses#Enabled",
        },
      },
    },
    "com.amazonaws.ses#NotificationTopic": {
      type: "string",
    },
    "com.amazonaws.ses#PolicyNameList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#PolicyName",
      },
    },
    "com.amazonaws.ses#PolicyMap": {
      type: "map",
      key: {
        target: "com.amazonaws.ses#PolicyName",
      },
      value: {
        target: "com.amazonaws.ses#Policy",
      },
    },
    "com.amazonaws.ses#Policy": {
      type: "string",
    },
    "com.amazonaws.ses#VerificationAttributes": {
      type: "map",
      key: {
        target: "com.amazonaws.ses#Identity",
      },
      value: {
        target: "com.amazonaws.ses#IdentityVerificationAttributes",
      },
    },
    "com.amazonaws.ses#IdentityVerificationAttributes": {
      type: "structure",
      members: {
        VerificationStatus: {
          target: "com.amazonaws.ses#VerificationStatus",
        },
        VerificationToken: {
          target: "com.amazonaws.ses#VerificationToken",
        },
      },
    },
    "com.amazonaws.ses#Max24HourSend": {
      type: "double",
    },
    "com.amazonaws.ses#MaxSendRate": {
      type: "double",
    },
    "com.amazonaws.ses#SentLast24Hours": {
      type: "double",
    },
    "com.amazonaws.ses#SendDataPointList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#SendDataPoint",
      },
    },
    "com.amazonaws.ses#SendDataPoint": {
      type: "structure",
      members: {
        Timestamp: {
          target: "com.amazonaws.ses#Timestamp",
        },
        DeliveryAttempts: {
          target: "com.amazonaws.ses#Counter",
        },
        Bounces: {
          target: "com.amazonaws.ses#Counter",
        },
        Complaints: {
          target: "com.amazonaws.ses#Counter",
        },
        Rejects: {
          target: "com.amazonaws.ses#Counter",
        },
      },
    },
    "com.amazonaws.ses#Counter": {
      type: "long",
    },
    "com.amazonaws.ses#NextToken": {
      type: "string",
    },
    "com.amazonaws.ses#MaxItems": {
      type: "integer",
    },
    "com.amazonaws.ses#ConfigurationSets": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#ConfigurationSet",
      },
    },
    "com.amazonaws.ses#MaxResults": {
      type: "integer",
    },
    "com.amazonaws.ses#CustomVerificationEmailTemplates": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#CustomVerificationEmailTemplate",
      },
    },
    "com.amazonaws.ses#CustomVerificationEmailTemplate": {
      type: "structure",
      members: {
        TemplateName: {
          target: "com.amazonaws.ses#TemplateName",
        },
        FromEmailAddress: {
          target: "com.amazonaws.ses#FromAddress",
        },
        TemplateSubject: {
          target: "com.amazonaws.ses#Subject",
        },
        SuccessRedirectionURL: {
          target: "com.amazonaws.ses#SuccessRedirectionURL",
        },
        FailureRedirectionURL: {
          target: "com.amazonaws.ses#FailureRedirectionURL",
        },
      },
    },
    "com.amazonaws.ses#IdentityType": {
      type: "enum",
    },
    "com.amazonaws.ses#ReceiptFilterList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#ReceiptFilter",
      },
    },
    "com.amazonaws.ses#ReceiptRuleSetsLists": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#ReceiptRuleSetMetadata",
      },
    },
    "com.amazonaws.ses#TemplateMetadataList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#TemplateMetadata",
      },
    },
    "com.amazonaws.ses#TemplateMetadata": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.ses#TemplateName",
        },
        CreatedTimestamp: {
          target: "com.amazonaws.ses#Timestamp",
        },
      },
    },
    "com.amazonaws.ses#AddressList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#Address",
      },
    },
    "com.amazonaws.ses#ReceiptRuleNamesList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#ReceiptRuleName",
      },
    },
    "com.amazonaws.ses#MessageId": {
      type: "string",
    },
    "com.amazonaws.ses#Explanation": {
      type: "string",
    },
    "com.amazonaws.ses#MessageDsn": {
      type: "structure",
      members: {
        ReportingMta: {
          target: "com.amazonaws.ses#ReportingMta",
        },
        ArrivalDate: {
          target: "com.amazonaws.ses#ArrivalDate",
        },
        ExtensionFields: {
          target: "com.amazonaws.ses#ExtensionFieldList",
        },
      },
    },
    "com.amazonaws.ses#ReportingMta": {
      type: "string",
    },
    "com.amazonaws.ses#ArrivalDate": {
      type: "timestamp",
    },
    "com.amazonaws.ses#ExtensionFieldList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#ExtensionField",
      },
    },
    "com.amazonaws.ses#ExtensionField": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.ses#ExtensionFieldName",
        },
        Value: {
          target: "com.amazonaws.ses#ExtensionFieldValue",
        },
      },
    },
    "com.amazonaws.ses#ExtensionFieldName": {
      type: "string",
    },
    "com.amazonaws.ses#ExtensionFieldValue": {
      type: "string",
    },
    "com.amazonaws.ses#BouncedRecipientInfoList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#BouncedRecipientInfo",
      },
    },
    "com.amazonaws.ses#BouncedRecipientInfo": {
      type: "structure",
      members: {
        Recipient: {
          target: "com.amazonaws.ses#Address",
        },
        RecipientArn: {
          target: "com.amazonaws.ses#AmazonResourceName",
        },
        BounceType: {
          target: "com.amazonaws.ses#BounceType",
        },
        RecipientDsnFields: {
          target: "com.amazonaws.ses#RecipientDsnFields",
        },
      },
    },
    "com.amazonaws.ses#BounceType": {
      type: "enum",
    },
    "com.amazonaws.ses#RecipientDsnFields": {
      type: "structure",
      members: {
        FinalRecipient: {
          target: "com.amazonaws.ses#Address",
        },
        Action: {
          target: "com.amazonaws.ses#DsnAction",
        },
        RemoteMta: {
          target: "com.amazonaws.ses#RemoteMta",
        },
        Status: {
          target: "com.amazonaws.ses#DsnStatus",
        },
        DiagnosticCode: {
          target: "com.amazonaws.ses#DiagnosticCode",
        },
        LastAttemptDate: {
          target: "com.amazonaws.ses#LastAttemptDate",
        },
        ExtensionFields: {
          target: "com.amazonaws.ses#ExtensionFieldList",
        },
      },
    },
    "com.amazonaws.ses#DsnAction": {
      type: "enum",
    },
    "com.amazonaws.ses#RemoteMta": {
      type: "string",
    },
    "com.amazonaws.ses#DsnStatus": {
      type: "string",
    },
    "com.amazonaws.ses#DiagnosticCode": {
      type: "string",
    },
    "com.amazonaws.ses#LastAttemptDate": {
      type: "timestamp",
    },
    "com.amazonaws.ses#MessageTagList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#MessageTag",
      },
    },
    "com.amazonaws.ses#MessageTag": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.ses#MessageTagName",
        },
        Value: {
          target: "com.amazonaws.ses#MessageTagValue",
        },
      },
    },
    "com.amazonaws.ses#MessageTagName": {
      type: "string",
    },
    "com.amazonaws.ses#MessageTagValue": {
      type: "string",
    },
    "com.amazonaws.ses#TemplateData": {
      type: "string",
    },
    "com.amazonaws.ses#BulkEmailDestinationList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#BulkEmailDestination",
      },
    },
    "com.amazonaws.ses#BulkEmailDestination": {
      type: "structure",
      members: {
        Destination: {
          target: "com.amazonaws.ses#Destination",
        },
        ReplacementTags: {
          target: "com.amazonaws.ses#MessageTagList",
        },
        ReplacementTemplateData: {
          target: "com.amazonaws.ses#TemplateData",
        },
      },
    },
    "com.amazonaws.ses#Destination": {
      type: "structure",
      members: {
        ToAddresses: {
          target: "com.amazonaws.ses#AddressList",
        },
        CcAddresses: {
          target: "com.amazonaws.ses#AddressList",
        },
        BccAddresses: {
          target: "com.amazonaws.ses#AddressList",
        },
      },
    },
    "com.amazonaws.ses#BulkEmailDestinationStatusList": {
      type: "list",
      member: {
        target: "com.amazonaws.ses#BulkEmailDestinationStatus",
      },
    },
    "com.amazonaws.ses#BulkEmailDestinationStatus": {
      type: "structure",
      members: {
        Status: {
          target: "com.amazonaws.ses#BulkEmailStatus",
        },
        Error: {
          target: "com.amazonaws.ses#Error",
        },
        MessageId: {
          target: "com.amazonaws.ses#MessageId",
        },
      },
    },
    "com.amazonaws.ses#BulkEmailStatus": {
      type: "enum",
    },
    "com.amazonaws.ses#Error": {
      type: "string",
    },
    "com.amazonaws.ses#Message": {
      type: "structure",
      members: {
        Subject: {
          target: "com.amazonaws.ses#Content",
        },
        Body: {
          target: "com.amazonaws.ses#Body",
        },
      },
    },
    "com.amazonaws.ses#Content": {
      type: "structure",
      members: {
        Data: {
          target: "com.amazonaws.ses#MessageData",
        },
        Charset: {
          target: "com.amazonaws.ses#Charset",
        },
      },
    },
    "com.amazonaws.ses#MessageData": {
      type: "string",
    },
    "com.amazonaws.ses#Charset": {
      type: "string",
    },
    "com.amazonaws.ses#Body": {
      type: "structure",
      members: {
        Text: {
          target: "com.amazonaws.ses#Content",
        },
        Html: {
          target: "com.amazonaws.ses#Content",
        },
      },
    },
    "com.amazonaws.ses#RawMessage": {
      type: "structure",
      members: {
        Data: {
          target: "com.amazonaws.ses#RawMessageData",
        },
      },
    },
    "com.amazonaws.ses#RawMessageData": {
      type: "blob",
    },
    "com.amazonaws.ses#NotificationType": {
      type: "enum",
    },
    "com.amazonaws.ses#RenderedTemplate": {
      type: "string",
    },
    "com.amazonaws.ses#Domain": {
      type: "string",
    },
  },
} as const;
