// Auto-generated by generate-awsquery-metadata.ts. DO NOT EDIT BY HAND.

export type ShapeKind =
  | "structure"
  | "list"
  | "map"
  | "string"
  | "integer"
  | "boolean"
  | "timestamp"
  | "blob"
  | "enum"
  | "double"
  | "long"
  | "float"
  | "union";

export interface MemberMeta {
  target: string;
  locationName?: string;
  queryName?: string;
  flattened?: boolean;
  timestampFormat?: "iso8601" | "epoch-seconds" | "http-date";
}

export interface ShapeMeta {
  type: ShapeKind;
  xmlName?: string;
  members?: Record<string, MemberMeta>;
  member?: MemberMeta;
  key?: MemberMeta;
  value?: MemberMeta;
  enum?: string[];
  flattened?: boolean;
}

export interface OperationMeta {
  name: string;
  input?: string;
  output?: string;
  responseWrapper?: string;
}

export interface AwsQueryServiceMeta {
  serviceId: string;
  serviceName: string;
  version: string;
  endpointPrefix?: string;
  operations: Record<string, OperationMeta>;
  shapes: Record<string, ShapeMeta>;
}

export const metadata: AwsQueryServiceMeta = {
  serviceId: "SNS",
  serviceName: "SNS",
  version: "2010-03-31",
  endpointPrefix: "sns",
  operations: {
    AddPermission: {
      name: "AddPermission",
      input: "com.amazonaws.sns#AddPermissionInput",
      output: "smithy.api#Unit",
      responseWrapper: "AddPermissionResponse",
    },
    CheckIfPhoneNumberIsOptedOut: {
      name: "CheckIfPhoneNumberIsOptedOut",
      input: "com.amazonaws.sns#CheckIfPhoneNumberIsOptedOutInput",
      output: "com.amazonaws.sns#CheckIfPhoneNumberIsOptedOutResponse",
      responseWrapper: "CheckIfPhoneNumberIsOptedOutResponse",
    },
    ConfirmSubscription: {
      name: "ConfirmSubscription",
      input: "com.amazonaws.sns#ConfirmSubscriptionInput",
      output: "com.amazonaws.sns#ConfirmSubscriptionResponse",
      responseWrapper: "ConfirmSubscriptionResponse",
    },
    CreatePlatformApplication: {
      name: "CreatePlatformApplication",
      input: "com.amazonaws.sns#CreatePlatformApplicationInput",
      output: "com.amazonaws.sns#CreatePlatformApplicationResponse",
      responseWrapper: "CreatePlatformApplicationResponse",
    },
    CreatePlatformEndpoint: {
      name: "CreatePlatformEndpoint",
      input: "com.amazonaws.sns#CreatePlatformEndpointInput",
      output: "com.amazonaws.sns#CreateEndpointResponse",
      responseWrapper: "CreatePlatformEndpointResponse",
    },
    CreateSMSSandboxPhoneNumber: {
      name: "CreateSMSSandboxPhoneNumber",
      input: "com.amazonaws.sns#CreateSMSSandboxPhoneNumberInput",
      output: "com.amazonaws.sns#CreateSMSSandboxPhoneNumberResult",
      responseWrapper: "CreateSMSSandboxPhoneNumberResponse",
    },
    CreateTopic: {
      name: "CreateTopic",
      input: "com.amazonaws.sns#CreateTopicInput",
      output: "com.amazonaws.sns#CreateTopicResponse",
      responseWrapper: "CreateTopicResponse",
    },
    DeleteEndpoint: {
      name: "DeleteEndpoint",
      input: "com.amazonaws.sns#DeleteEndpointInput",
      output: "smithy.api#Unit",
      responseWrapper: "DeleteEndpointResponse",
    },
    DeletePlatformApplication: {
      name: "DeletePlatformApplication",
      input: "com.amazonaws.sns#DeletePlatformApplicationInput",
      output: "smithy.api#Unit",
      responseWrapper: "DeletePlatformApplicationResponse",
    },
    DeleteSMSSandboxPhoneNumber: {
      name: "DeleteSMSSandboxPhoneNumber",
      input: "com.amazonaws.sns#DeleteSMSSandboxPhoneNumberInput",
      output: "com.amazonaws.sns#DeleteSMSSandboxPhoneNumberResult",
      responseWrapper: "DeleteSMSSandboxPhoneNumberResponse",
    },
    DeleteTopic: {
      name: "DeleteTopic",
      input: "com.amazonaws.sns#DeleteTopicInput",
      output: "smithy.api#Unit",
      responseWrapper: "DeleteTopicResponse",
    },
    GetDataProtectionPolicy: {
      name: "GetDataProtectionPolicy",
      input: "com.amazonaws.sns#GetDataProtectionPolicyInput",
      output: "com.amazonaws.sns#GetDataProtectionPolicyResponse",
      responseWrapper: "GetDataProtectionPolicyResponse",
    },
    GetEndpointAttributes: {
      name: "GetEndpointAttributes",
      input: "com.amazonaws.sns#GetEndpointAttributesInput",
      output: "com.amazonaws.sns#GetEndpointAttributesResponse",
      responseWrapper: "GetEndpointAttributesResponse",
    },
    GetPlatformApplicationAttributes: {
      name: "GetPlatformApplicationAttributes",
      input: "com.amazonaws.sns#GetPlatformApplicationAttributesInput",
      output: "com.amazonaws.sns#GetPlatformApplicationAttributesResponse",
      responseWrapper: "GetPlatformApplicationAttributesResponse",
    },
    GetSMSAttributes: {
      name: "GetSMSAttributes",
      input: "com.amazonaws.sns#GetSMSAttributesInput",
      output: "com.amazonaws.sns#GetSMSAttributesResponse",
      responseWrapper: "GetSMSAttributesResponse",
    },
    GetSMSSandboxAccountStatus: {
      name: "GetSMSSandboxAccountStatus",
      input: "com.amazonaws.sns#GetSMSSandboxAccountStatusInput",
      output: "com.amazonaws.sns#GetSMSSandboxAccountStatusResult",
      responseWrapper: "GetSMSSandboxAccountStatusResponse",
    },
    GetSubscriptionAttributes: {
      name: "GetSubscriptionAttributes",
      input: "com.amazonaws.sns#GetSubscriptionAttributesInput",
      output: "com.amazonaws.sns#GetSubscriptionAttributesResponse",
      responseWrapper: "GetSubscriptionAttributesResponse",
    },
    GetTopicAttributes: {
      name: "GetTopicAttributes",
      input: "com.amazonaws.sns#GetTopicAttributesInput",
      output: "com.amazonaws.sns#GetTopicAttributesResponse",
      responseWrapper: "GetTopicAttributesResponse",
    },
    ListEndpointsByPlatformApplication: {
      name: "ListEndpointsByPlatformApplication",
      input: "com.amazonaws.sns#ListEndpointsByPlatformApplicationInput",
      output: "com.amazonaws.sns#ListEndpointsByPlatformApplicationResponse",
      responseWrapper: "ListEndpointsByPlatformApplicationResponse",
    },
    ListOriginationNumbers: {
      name: "ListOriginationNumbers",
      input: "com.amazonaws.sns#ListOriginationNumbersRequest",
      output: "com.amazonaws.sns#ListOriginationNumbersResult",
      responseWrapper: "ListOriginationNumbersResponse",
    },
    ListPhoneNumbersOptedOut: {
      name: "ListPhoneNumbersOptedOut",
      input: "com.amazonaws.sns#ListPhoneNumbersOptedOutInput",
      output: "com.amazonaws.sns#ListPhoneNumbersOptedOutResponse",
      responseWrapper: "ListPhoneNumbersOptedOutResponse",
    },
    ListPlatformApplications: {
      name: "ListPlatformApplications",
      input: "com.amazonaws.sns#ListPlatformApplicationsInput",
      output: "com.amazonaws.sns#ListPlatformApplicationsResponse",
      responseWrapper: "ListPlatformApplicationsResponse",
    },
    ListSMSSandboxPhoneNumbers: {
      name: "ListSMSSandboxPhoneNumbers",
      input: "com.amazonaws.sns#ListSMSSandboxPhoneNumbersInput",
      output: "com.amazonaws.sns#ListSMSSandboxPhoneNumbersResult",
      responseWrapper: "ListSMSSandboxPhoneNumbersResponse",
    },
    ListSubscriptions: {
      name: "ListSubscriptions",
      input: "com.amazonaws.sns#ListSubscriptionsInput",
      output: "com.amazonaws.sns#ListSubscriptionsResponse",
      responseWrapper: "ListSubscriptionsResponse",
    },
    ListSubscriptionsByTopic: {
      name: "ListSubscriptionsByTopic",
      input: "com.amazonaws.sns#ListSubscriptionsByTopicInput",
      output: "com.amazonaws.sns#ListSubscriptionsByTopicResponse",
      responseWrapper: "ListSubscriptionsByTopicResponse",
    },
    ListTagsForResource: {
      name: "ListTagsForResource",
      input: "com.amazonaws.sns#ListTagsForResourceRequest",
      output: "com.amazonaws.sns#ListTagsForResourceResponse",
      responseWrapper: "ListTagsForResourceResponse",
    },
    ListTopics: {
      name: "ListTopics",
      input: "com.amazonaws.sns#ListTopicsInput",
      output: "com.amazonaws.sns#ListTopicsResponse",
      responseWrapper: "ListTopicsResponse",
    },
    OptInPhoneNumber: {
      name: "OptInPhoneNumber",
      input: "com.amazonaws.sns#OptInPhoneNumberInput",
      output: "com.amazonaws.sns#OptInPhoneNumberResponse",
      responseWrapper: "OptInPhoneNumberResponse",
    },
    Publish: {
      name: "Publish",
      input: "com.amazonaws.sns#PublishInput",
      output: "com.amazonaws.sns#PublishResponse",
      responseWrapper: "PublishResponse",
    },
    PublishBatch: {
      name: "PublishBatch",
      input: "com.amazonaws.sns#PublishBatchInput",
      output: "com.amazonaws.sns#PublishBatchResponse",
      responseWrapper: "PublishBatchResponse",
    },
    PutDataProtectionPolicy: {
      name: "PutDataProtectionPolicy",
      input: "com.amazonaws.sns#PutDataProtectionPolicyInput",
      output: "smithy.api#Unit",
      responseWrapper: "PutDataProtectionPolicyResponse",
    },
    RemovePermission: {
      name: "RemovePermission",
      input: "com.amazonaws.sns#RemovePermissionInput",
      output: "smithy.api#Unit",
      responseWrapper: "RemovePermissionResponse",
    },
    SetEndpointAttributes: {
      name: "SetEndpointAttributes",
      input: "com.amazonaws.sns#SetEndpointAttributesInput",
      output: "smithy.api#Unit",
      responseWrapper: "SetEndpointAttributesResponse",
    },
    SetPlatformApplicationAttributes: {
      name: "SetPlatformApplicationAttributes",
      input: "com.amazonaws.sns#SetPlatformApplicationAttributesInput",
      output: "smithy.api#Unit",
      responseWrapper: "SetPlatformApplicationAttributesResponse",
    },
    SetSMSAttributes: {
      name: "SetSMSAttributes",
      input: "com.amazonaws.sns#SetSMSAttributesInput",
      output: "com.amazonaws.sns#SetSMSAttributesResponse",
      responseWrapper: "SetSMSAttributesResponse",
    },
    SetSubscriptionAttributes: {
      name: "SetSubscriptionAttributes",
      input: "com.amazonaws.sns#SetSubscriptionAttributesInput",
      output: "smithy.api#Unit",
      responseWrapper: "SetSubscriptionAttributesResponse",
    },
    SetTopicAttributes: {
      name: "SetTopicAttributes",
      input: "com.amazonaws.sns#SetTopicAttributesInput",
      output: "smithy.api#Unit",
      responseWrapper: "SetTopicAttributesResponse",
    },
    Subscribe: {
      name: "Subscribe",
      input: "com.amazonaws.sns#SubscribeInput",
      output: "com.amazonaws.sns#SubscribeResponse",
      responseWrapper: "SubscribeResponse",
    },
    TagResource: {
      name: "TagResource",
      input: "com.amazonaws.sns#TagResourceRequest",
      output: "com.amazonaws.sns#TagResourceResponse",
      responseWrapper: "TagResourceResponse",
    },
    Unsubscribe: {
      name: "Unsubscribe",
      input: "com.amazonaws.sns#UnsubscribeInput",
      output: "smithy.api#Unit",
      responseWrapper: "UnsubscribeResponse",
    },
    UntagResource: {
      name: "UntagResource",
      input: "com.amazonaws.sns#UntagResourceRequest",
      output: "com.amazonaws.sns#UntagResourceResponse",
      responseWrapper: "UntagResourceResponse",
    },
    VerifySMSSandboxPhoneNumber: {
      name: "VerifySMSSandboxPhoneNumber",
      input: "com.amazonaws.sns#VerifySMSSandboxPhoneNumberInput",
      output: "com.amazonaws.sns#VerifySMSSandboxPhoneNumberResult",
      responseWrapper: "VerifySMSSandboxPhoneNumberResponse",
    },
  },
  shapes: {
    "com.amazonaws.sns#AddPermissionInput": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
        Label: {
          target: "com.amazonaws.sns#label",
        },
        AWSAccountId: {
          target: "com.amazonaws.sns#DelegatesList",
        },
        ActionName: {
          target: "com.amazonaws.sns#ActionsList",
        },
      },
    },
    "com.amazonaws.sns#CheckIfPhoneNumberIsOptedOutInput": {
      type: "structure",
      members: {
        phoneNumber: {
          target: "com.amazonaws.sns#PhoneNumber",
        },
      },
    },
    "com.amazonaws.sns#CheckIfPhoneNumberIsOptedOutResponse": {
      type: "structure",
      members: {
        isOptedOut: {
          target: "com.amazonaws.sns#boolean",
        },
      },
    },
    "com.amazonaws.sns#ConfirmSubscriptionInput": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
        Token: {
          target: "com.amazonaws.sns#token",
        },
        AuthenticateOnUnsubscribe: {
          target: "com.amazonaws.sns#authenticateOnUnsubscribe",
        },
      },
    },
    "com.amazonaws.sns#ConfirmSubscriptionResponse": {
      type: "structure",
      members: {
        SubscriptionArn: {
          target: "com.amazonaws.sns#subscriptionARN",
        },
      },
    },
    "com.amazonaws.sns#CreatePlatformApplicationInput": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.sns#String",
        },
        Platform: {
          target: "com.amazonaws.sns#String",
        },
        Attributes: {
          target: "com.amazonaws.sns#MapStringToString",
        },
      },
    },
    "com.amazonaws.sns#CreatePlatformApplicationResponse": {
      type: "structure",
      members: {
        PlatformApplicationArn: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#CreatePlatformEndpointInput": {
      type: "structure",
      members: {
        PlatformApplicationArn: {
          target: "com.amazonaws.sns#String",
        },
        Token: {
          target: "com.amazonaws.sns#String",
        },
        CustomUserData: {
          target: "com.amazonaws.sns#String",
        },
        Attributes: {
          target: "com.amazonaws.sns#MapStringToString",
        },
      },
    },
    "com.amazonaws.sns#CreateEndpointResponse": {
      type: "structure",
      members: {
        EndpointArn: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#CreateSMSSandboxPhoneNumberInput": {
      type: "structure",
      members: {
        PhoneNumber: {
          target: "com.amazonaws.sns#PhoneNumberString",
        },
        LanguageCode: {
          target: "com.amazonaws.sns#LanguageCodeString",
        },
      },
    },
    "com.amazonaws.sns#CreateSMSSandboxPhoneNumberResult": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.sns#CreateTopicInput": {
      type: "structure",
      members: {
        Name: {
          target: "com.amazonaws.sns#topicName",
        },
        Attributes: {
          target: "com.amazonaws.sns#TopicAttributesMap",
        },
        Tags: {
          target: "com.amazonaws.sns#TagList",
        },
        DataProtectionPolicy: {
          target: "com.amazonaws.sns#attributeValue",
        },
      },
    },
    "com.amazonaws.sns#CreateTopicResponse": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
      },
    },
    "com.amazonaws.sns#DeleteEndpointInput": {
      type: "structure",
      members: {
        EndpointArn: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#DeletePlatformApplicationInput": {
      type: "structure",
      members: {
        PlatformApplicationArn: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#DeleteSMSSandboxPhoneNumberInput": {
      type: "structure",
      members: {
        PhoneNumber: {
          target: "com.amazonaws.sns#PhoneNumberString",
        },
      },
    },
    "com.amazonaws.sns#DeleteSMSSandboxPhoneNumberResult": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.sns#DeleteTopicInput": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
      },
    },
    "com.amazonaws.sns#GetDataProtectionPolicyInput": {
      type: "structure",
      members: {
        ResourceArn: {
          target: "com.amazonaws.sns#topicARN",
        },
      },
    },
    "com.amazonaws.sns#GetDataProtectionPolicyResponse": {
      type: "structure",
      members: {
        DataProtectionPolicy: {
          target: "com.amazonaws.sns#attributeValue",
        },
      },
    },
    "com.amazonaws.sns#GetEndpointAttributesInput": {
      type: "structure",
      members: {
        EndpointArn: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#GetEndpointAttributesResponse": {
      type: "structure",
      members: {
        Attributes: {
          target: "com.amazonaws.sns#MapStringToString",
        },
      },
    },
    "com.amazonaws.sns#GetPlatformApplicationAttributesInput": {
      type: "structure",
      members: {
        PlatformApplicationArn: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#GetPlatformApplicationAttributesResponse": {
      type: "structure",
      members: {
        Attributes: {
          target: "com.amazonaws.sns#MapStringToString",
        },
      },
    },
    "com.amazonaws.sns#GetSMSAttributesInput": {
      type: "structure",
      members: {
        attributes: {
          target: "com.amazonaws.sns#ListString",
        },
      },
    },
    "com.amazonaws.sns#GetSMSAttributesResponse": {
      type: "structure",
      members: {
        attributes: {
          target: "com.amazonaws.sns#MapStringToString",
        },
      },
    },
    "com.amazonaws.sns#GetSMSSandboxAccountStatusInput": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.sns#GetSMSSandboxAccountStatusResult": {
      type: "structure",
      members: {
        IsInSandbox: {
          target: "com.amazonaws.sns#boolean",
        },
      },
    },
    "com.amazonaws.sns#GetSubscriptionAttributesInput": {
      type: "structure",
      members: {
        SubscriptionArn: {
          target: "com.amazonaws.sns#subscriptionARN",
        },
      },
    },
    "com.amazonaws.sns#GetSubscriptionAttributesResponse": {
      type: "structure",
      members: {
        Attributes: {
          target: "com.amazonaws.sns#SubscriptionAttributesMap",
        },
      },
    },
    "com.amazonaws.sns#GetTopicAttributesInput": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
      },
    },
    "com.amazonaws.sns#GetTopicAttributesResponse": {
      type: "structure",
      members: {
        Attributes: {
          target: "com.amazonaws.sns#TopicAttributesMap",
        },
      },
    },
    "com.amazonaws.sns#ListEndpointsByPlatformApplicationInput": {
      type: "structure",
      members: {
        PlatformApplicationArn: {
          target: "com.amazonaws.sns#String",
        },
        NextToken: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#ListEndpointsByPlatformApplicationResponse": {
      type: "structure",
      members: {
        Endpoints: {
          target: "com.amazonaws.sns#ListOfEndpoints",
        },
        NextToken: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#ListOriginationNumbersRequest": {
      type: "structure",
      members: {
        NextToken: {
          target: "com.amazonaws.sns#nextToken",
        },
        MaxResults: {
          target: "com.amazonaws.sns#MaxItemsListOriginationNumbers",
        },
      },
    },
    "com.amazonaws.sns#ListOriginationNumbersResult": {
      type: "structure",
      members: {
        NextToken: {
          target: "com.amazonaws.sns#nextToken",
        },
        PhoneNumbers: {
          target: "com.amazonaws.sns#PhoneNumberInformationList",
        },
      },
    },
    "com.amazonaws.sns#ListPhoneNumbersOptedOutInput": {
      type: "structure",
      members: {
        nextToken: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#ListPhoneNumbersOptedOutResponse": {
      type: "structure",
      members: {
        phoneNumbers: {
          target: "com.amazonaws.sns#PhoneNumberList",
        },
        nextToken: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#ListPlatformApplicationsInput": {
      type: "structure",
      members: {
        NextToken: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#ListPlatformApplicationsResponse": {
      type: "structure",
      members: {
        PlatformApplications: {
          target: "com.amazonaws.sns#ListOfPlatformApplications",
        },
        NextToken: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#ListSMSSandboxPhoneNumbersInput": {
      type: "structure",
      members: {
        NextToken: {
          target: "com.amazonaws.sns#nextToken",
        },
        MaxResults: {
          target: "com.amazonaws.sns#MaxItems",
        },
      },
    },
    "com.amazonaws.sns#ListSMSSandboxPhoneNumbersResult": {
      type: "structure",
      members: {
        PhoneNumbers: {
          target: "com.amazonaws.sns#SMSSandboxPhoneNumberList",
        },
        NextToken: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#ListSubscriptionsInput": {
      type: "structure",
      members: {
        NextToken: {
          target: "com.amazonaws.sns#nextToken",
        },
      },
    },
    "com.amazonaws.sns#ListSubscriptionsResponse": {
      type: "structure",
      members: {
        Subscriptions: {
          target: "com.amazonaws.sns#SubscriptionsList",
        },
        NextToken: {
          target: "com.amazonaws.sns#nextToken",
        },
      },
    },
    "com.amazonaws.sns#ListSubscriptionsByTopicInput": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
        NextToken: {
          target: "com.amazonaws.sns#nextToken",
        },
      },
    },
    "com.amazonaws.sns#ListSubscriptionsByTopicResponse": {
      type: "structure",
      members: {
        Subscriptions: {
          target: "com.amazonaws.sns#SubscriptionsList",
        },
        NextToken: {
          target: "com.amazonaws.sns#nextToken",
        },
      },
    },
    "com.amazonaws.sns#ListTagsForResourceRequest": {
      type: "structure",
      members: {
        ResourceArn: {
          target: "com.amazonaws.sns#AmazonResourceName",
        },
      },
    },
    "com.amazonaws.sns#ListTagsForResourceResponse": {
      type: "structure",
      members: {
        Tags: {
          target: "com.amazonaws.sns#TagList",
        },
      },
    },
    "com.amazonaws.sns#ListTopicsInput": {
      type: "structure",
      members: {
        NextToken: {
          target: "com.amazonaws.sns#nextToken",
        },
      },
    },
    "com.amazonaws.sns#ListTopicsResponse": {
      type: "structure",
      members: {
        Topics: {
          target: "com.amazonaws.sns#TopicsList",
        },
        NextToken: {
          target: "com.amazonaws.sns#nextToken",
        },
      },
    },
    "com.amazonaws.sns#OptInPhoneNumberInput": {
      type: "structure",
      members: {
        phoneNumber: {
          target: "com.amazonaws.sns#PhoneNumber",
        },
      },
    },
    "com.amazonaws.sns#OptInPhoneNumberResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.sns#PublishInput": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
        TargetArn: {
          target: "com.amazonaws.sns#String",
        },
        PhoneNumber: {
          target: "com.amazonaws.sns#PhoneNumber",
        },
        Message: {
          target: "com.amazonaws.sns#message",
        },
        Subject: {
          target: "com.amazonaws.sns#subject",
        },
        MessageStructure: {
          target: "com.amazonaws.sns#messageStructure",
        },
        MessageAttributes: {
          target: "com.amazonaws.sns#MessageAttributeMap",
        },
        MessageDeduplicationId: {
          target: "com.amazonaws.sns#String",
        },
        MessageGroupId: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#PublishResponse": {
      type: "structure",
      members: {
        MessageId: {
          target: "com.amazonaws.sns#messageId",
        },
        SequenceNumber: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#PublishBatchInput": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
        PublishBatchRequestEntries: {
          target: "com.amazonaws.sns#PublishBatchRequestEntryList",
        },
      },
    },
    "com.amazonaws.sns#PublishBatchResponse": {
      type: "structure",
      members: {
        Successful: {
          target: "com.amazonaws.sns#PublishBatchResultEntryList",
        },
        Failed: {
          target: "com.amazonaws.sns#BatchResultErrorEntryList",
        },
      },
    },
    "com.amazonaws.sns#PutDataProtectionPolicyInput": {
      type: "structure",
      members: {
        ResourceArn: {
          target: "com.amazonaws.sns#topicARN",
        },
        DataProtectionPolicy: {
          target: "com.amazonaws.sns#attributeValue",
        },
      },
    },
    "com.amazonaws.sns#RemovePermissionInput": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
        Label: {
          target: "com.amazonaws.sns#label",
        },
      },
    },
    "com.amazonaws.sns#SetEndpointAttributesInput": {
      type: "structure",
      members: {
        EndpointArn: {
          target: "com.amazonaws.sns#String",
        },
        Attributes: {
          target: "com.amazonaws.sns#MapStringToString",
        },
      },
    },
    "com.amazonaws.sns#SetPlatformApplicationAttributesInput": {
      type: "structure",
      members: {
        PlatformApplicationArn: {
          target: "com.amazonaws.sns#String",
        },
        Attributes: {
          target: "com.amazonaws.sns#MapStringToString",
        },
      },
    },
    "com.amazonaws.sns#SetSMSAttributesInput": {
      type: "structure",
      members: {
        attributes: {
          target: "com.amazonaws.sns#MapStringToString",
        },
      },
    },
    "com.amazonaws.sns#SetSMSAttributesResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.sns#SetSubscriptionAttributesInput": {
      type: "structure",
      members: {
        SubscriptionArn: {
          target: "com.amazonaws.sns#subscriptionARN",
        },
        AttributeName: {
          target: "com.amazonaws.sns#attributeName",
        },
        AttributeValue: {
          target: "com.amazonaws.sns#attributeValue",
        },
      },
    },
    "com.amazonaws.sns#SetTopicAttributesInput": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
        AttributeName: {
          target: "com.amazonaws.sns#attributeName",
        },
        AttributeValue: {
          target: "com.amazonaws.sns#attributeValue",
        },
      },
    },
    "com.amazonaws.sns#SubscribeInput": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
        Protocol: {
          target: "com.amazonaws.sns#protocol",
        },
        Endpoint: {
          target: "com.amazonaws.sns#Endpoint2",
        },
        Attributes: {
          target: "com.amazonaws.sns#SubscriptionAttributesMap",
        },
        ReturnSubscriptionArn: {
          target: "com.amazonaws.sns#boolean",
        },
      },
    },
    "com.amazonaws.sns#SubscribeResponse": {
      type: "structure",
      members: {
        SubscriptionArn: {
          target: "com.amazonaws.sns#subscriptionARN",
        },
      },
    },
    "com.amazonaws.sns#TagResourceRequest": {
      type: "structure",
      members: {
        ResourceArn: {
          target: "com.amazonaws.sns#AmazonResourceName",
        },
        Tags: {
          target: "com.amazonaws.sns#TagList",
        },
      },
    },
    "com.amazonaws.sns#TagResourceResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.sns#UnsubscribeInput": {
      type: "structure",
      members: {
        SubscriptionArn: {
          target: "com.amazonaws.sns#subscriptionARN",
        },
      },
    },
    "com.amazonaws.sns#UntagResourceRequest": {
      type: "structure",
      members: {
        ResourceArn: {
          target: "com.amazonaws.sns#AmazonResourceName",
        },
        TagKeys: {
          target: "com.amazonaws.sns#TagKeyList",
        },
      },
    },
    "com.amazonaws.sns#UntagResourceResponse": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.sns#VerifySMSSandboxPhoneNumberInput": {
      type: "structure",
      members: {
        PhoneNumber: {
          target: "com.amazonaws.sns#PhoneNumberString",
        },
        OneTimePassword: {
          target: "com.amazonaws.sns#OTPCode",
        },
      },
    },
    "com.amazonaws.sns#VerifySMSSandboxPhoneNumberResult": {
      type: "structure",
      members: {},
    },
    "com.amazonaws.sns#topicARN": {
      type: "string",
    },
    "com.amazonaws.sns#label": {
      type: "string",
    },
    "com.amazonaws.sns#DelegatesList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#delegate",
      },
    },
    "com.amazonaws.sns#delegate": {
      type: "string",
    },
    "com.amazonaws.sns#ActionsList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#action",
      },
    },
    "com.amazonaws.sns#action": {
      type: "string",
    },
    "com.amazonaws.sns#PhoneNumber": {
      type: "string",
    },
    "com.amazonaws.sns#boolean": {
      type: "boolean",
    },
    "com.amazonaws.sns#token": {
      type: "string",
    },
    "com.amazonaws.sns#authenticateOnUnsubscribe": {
      type: "string",
    },
    "com.amazonaws.sns#subscriptionARN": {
      type: "string",
    },
    "com.amazonaws.sns#String": {
      type: "string",
    },
    "com.amazonaws.sns#MapStringToString": {
      type: "map",
      key: {
        target: "com.amazonaws.sns#String",
      },
      value: {
        target: "com.amazonaws.sns#String",
      },
    },
    "com.amazonaws.sns#PhoneNumberString": {
      type: "string",
    },
    "com.amazonaws.sns#LanguageCodeString": {
      type: "enum",
    },
    "com.amazonaws.sns#topicName": {
      type: "string",
    },
    "com.amazonaws.sns#TopicAttributesMap": {
      type: "map",
      key: {
        target: "com.amazonaws.sns#attributeName",
      },
      value: {
        target: "com.amazonaws.sns#attributeValue",
      },
    },
    "com.amazonaws.sns#attributeName": {
      type: "string",
    },
    "com.amazonaws.sns#attributeValue": {
      type: "string",
    },
    "com.amazonaws.sns#TagList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#Tag",
      },
    },
    "com.amazonaws.sns#Tag": {
      type: "structure",
      members: {
        Key: {
          target: "com.amazonaws.sns#TagKey",
        },
        Value: {
          target: "com.amazonaws.sns#TagValue",
        },
      },
    },
    "com.amazonaws.sns#TagKey": {
      type: "string",
    },
    "com.amazonaws.sns#TagValue": {
      type: "string",
    },
    "com.amazonaws.sns#ListString": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#String",
      },
    },
    "com.amazonaws.sns#SubscriptionAttributesMap": {
      type: "map",
      key: {
        target: "com.amazonaws.sns#attributeName",
      },
      value: {
        target: "com.amazonaws.sns#attributeValue",
      },
    },
    "com.amazonaws.sns#ListOfEndpoints": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#Endpoint",
      },
    },
    "com.amazonaws.sns#Endpoint": {
      type: "structure",
      members: {
        EndpointArn: {
          target: "com.amazonaws.sns#String",
        },
        Attributes: {
          target: "com.amazonaws.sns#MapStringToString",
        },
      },
    },
    "com.amazonaws.sns#nextToken": {
      type: "string",
    },
    "com.amazonaws.sns#MaxItemsListOriginationNumbers": {
      type: "integer",
    },
    "com.amazonaws.sns#PhoneNumberInformationList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#PhoneNumberInformation",
      },
    },
    "com.amazonaws.sns#PhoneNumberInformation": {
      type: "structure",
      members: {
        CreatedAt: {
          target: "com.amazonaws.sns#Timestamp",
        },
        PhoneNumber: {
          target: "com.amazonaws.sns#PhoneNumber",
        },
        Status: {
          target: "com.amazonaws.sns#String",
        },
        Iso2CountryCode: {
          target: "com.amazonaws.sns#Iso2CountryCode",
        },
        RouteType: {
          target: "com.amazonaws.sns#RouteType",
        },
        NumberCapabilities: {
          target: "com.amazonaws.sns#NumberCapabilityList",
        },
      },
    },
    "com.amazonaws.sns#Timestamp": {
      type: "timestamp",
    },
    "com.amazonaws.sns#Iso2CountryCode": {
      type: "string",
    },
    "com.amazonaws.sns#RouteType": {
      type: "enum",
    },
    "com.amazonaws.sns#NumberCapabilityList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#NumberCapability",
      },
    },
    "com.amazonaws.sns#NumberCapability": {
      type: "enum",
    },
    "com.amazonaws.sns#PhoneNumberList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#PhoneNumber",
      },
    },
    "com.amazonaws.sns#ListOfPlatformApplications": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#PlatformApplication",
      },
    },
    "com.amazonaws.sns#PlatformApplication": {
      type: "structure",
      members: {
        PlatformApplicationArn: {
          target: "com.amazonaws.sns#String",
        },
        Attributes: {
          target: "com.amazonaws.sns#MapStringToString",
        },
      },
    },
    "com.amazonaws.sns#MaxItems": {
      type: "integer",
    },
    "com.amazonaws.sns#SMSSandboxPhoneNumberList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#SMSSandboxPhoneNumber",
      },
    },
    "com.amazonaws.sns#SMSSandboxPhoneNumber": {
      type: "structure",
      members: {
        PhoneNumber: {
          target: "com.amazonaws.sns#PhoneNumberString",
        },
        Status: {
          target: "com.amazonaws.sns#SMSSandboxPhoneNumberVerificationStatus",
        },
      },
    },
    "com.amazonaws.sns#SMSSandboxPhoneNumberVerificationStatus": {
      type: "enum",
    },
    "com.amazonaws.sns#SubscriptionsList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#Subscription",
      },
    },
    "com.amazonaws.sns#Subscription": {
      type: "structure",
      members: {
        SubscriptionArn: {
          target: "com.amazonaws.sns#subscriptionARN",
        },
        Owner: {
          target: "com.amazonaws.sns#account",
        },
        Protocol: {
          target: "com.amazonaws.sns#protocol",
        },
        Endpoint: {
          target: "com.amazonaws.sns#Endpoint2",
        },
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
      },
    },
    "com.amazonaws.sns#account": {
      type: "string",
    },
    "com.amazonaws.sns#protocol": {
      type: "string",
    },
    "com.amazonaws.sns#Endpoint2": {
      type: "string",
    },
    "com.amazonaws.sns#AmazonResourceName": {
      type: "string",
    },
    "com.amazonaws.sns#TopicsList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#Topic",
      },
    },
    "com.amazonaws.sns#Topic": {
      type: "structure",
      members: {
        TopicArn: {
          target: "com.amazonaws.sns#topicARN",
        },
      },
    },
    "com.amazonaws.sns#message": {
      type: "string",
    },
    "com.amazonaws.sns#subject": {
      type: "string",
    },
    "com.amazonaws.sns#messageStructure": {
      type: "string",
    },
    "com.amazonaws.sns#MessageAttributeMap": {
      type: "map",
      key: {
        target: "com.amazonaws.sns#String",
      },
      value: {
        target: "com.amazonaws.sns#MessageAttributeValue",
      },
    },
    "com.amazonaws.sns#MessageAttributeValue": {
      type: "structure",
      members: {
        DataType: {
          target: "com.amazonaws.sns#String",
        },
        StringValue: {
          target: "com.amazonaws.sns#String",
        },
        BinaryValue: {
          target: "com.amazonaws.sns#Binary",
        },
      },
    },
    "com.amazonaws.sns#Binary": {
      type: "blob",
    },
    "com.amazonaws.sns#messageId": {
      type: "string",
    },
    "com.amazonaws.sns#PublishBatchRequestEntryList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#PublishBatchRequestEntry",
      },
    },
    "com.amazonaws.sns#PublishBatchRequestEntry": {
      type: "structure",
      members: {
        Id: {
          target: "com.amazonaws.sns#String",
        },
        Message: {
          target: "com.amazonaws.sns#message",
        },
        Subject: {
          target: "com.amazonaws.sns#subject",
        },
        MessageStructure: {
          target: "com.amazonaws.sns#messageStructure",
        },
        MessageAttributes: {
          target: "com.amazonaws.sns#MessageAttributeMap",
        },
        MessageDeduplicationId: {
          target: "com.amazonaws.sns#String",
        },
        MessageGroupId: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#PublishBatchResultEntryList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#PublishBatchResultEntry",
      },
    },
    "com.amazonaws.sns#PublishBatchResultEntry": {
      type: "structure",
      members: {
        Id: {
          target: "com.amazonaws.sns#String",
        },
        MessageId: {
          target: "com.amazonaws.sns#messageId",
        },
        SequenceNumber: {
          target: "com.amazonaws.sns#String",
        },
      },
    },
    "com.amazonaws.sns#BatchResultErrorEntryList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#BatchResultErrorEntry",
      },
    },
    "com.amazonaws.sns#BatchResultErrorEntry": {
      type: "structure",
      members: {
        Id: {
          target: "com.amazonaws.sns#String",
        },
        Code: {
          target: "com.amazonaws.sns#String",
        },
        Message: {
          target: "com.amazonaws.sns#String",
        },
        SenderFault: {
          target: "com.amazonaws.sns#boolean",
        },
      },
    },
    "com.amazonaws.sns#TagKeyList": {
      type: "list",
      member: {
        target: "com.amazonaws.sns#TagKey",
      },
    },
    "com.amazonaws.sns#OTPCode": {
      type: "string",
    },
  },
} as const;
