import baseConfig from "./base.config.mjs";

export default {
  ...baseConfig,
  plugins: ["typescript", "import", "oxc", "eslint", "node"],
  categories: {
    correctness: "off",
  },
  rules: {
    ...baseConfig.rules,
    "typescript/consistent-type-imports": [
      "error",
      {
        fixStyle: "separate-type-imports",
      },
    ],
    "typescript/no-import-type-side-effects": "error",
    "import/no-duplicates": "error",
    "import/no-self-import": "error",
    "import/no-empty-named-blocks": "error",
    "typescript/no-unnecessary-type-assertion": "warn",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-useless-empty-export": "error",
    "eslint/no-console": "off",
    "eslint/no-var": "error",
    "eslint/no-shadow": "off",
    "eslint/no-underscore-dangle": "off",
    "eslint/no-useless-constructor": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "eslint/no-unneeded-ternary": "error",
    "eslint/no-useless-concat": "error",
    "oxc/misrefactored-assign-op": "error",
    "unicorn/prefer-array-flat-map": "error",
    "unicorn/no-accessor-recursion": "error",
    "oxc/no-map-spread": "off",
    "eslint/no-unused-vars": "off",
    "eslint/require-yield": "off",
    "eslint/no-fallthrough": "off",
    "eslint/no-await-in-loop": "off",
    "unicorn/no-new-array": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-array-reverse": "off",
    "unicorn/require-post-message-target-origin": "off",
    "unicorn/prefer-add-event-listener": "off",
    "unicorn/prefer-set-has": "off",
    "typescript/no-explicit-any": "off",
    "typescript/no-empty-interface": "off",
    "typescript/ban-ts-comment": "off",
    "typescript/no-namespace": "off",
    "typescript/no-non-null-assertion": "off",
    "typescript/no-dynamic-delete": "off",
    "typescript/no-invalid-void-type": "off",
    "typescript/no-unsafe-function-type": "off",
    "typescript/unified-signatures": "off",
    "typescript/no-empty-object-type": "off",
    "typescript/no-confusing-non-null-assertion": "off",
    "typescript/array-type": [
      "error",
      {
        default: "generic",
        readonly: "generic",
      },
    ],
    "typescript/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
  },
  ignorePatterns: [
    ...(baseConfig.ignorePatterns ?? []),
    "**/routeTree.gen.ts",
    "**/__snapshots__/**",
  ],
};
