/**
 * Wrangler baseline bundler adapter.
 *
 * Shells out to `wrangler deploy --dry-run --outdir=<tmpdir>` to produce
 * a baseline bundle that we can compare distilled-bundler's output against.
 */
import * as Effect from "effect/Effect";
import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { hash } from "../../src/hash.js";
import { Module, type ModuleType } from "../../src/index.js";
import { BundleError } from "./bundle-error.js";
import type { BundleConfig, BundleResult } from "./types.js";

/**
 * Convenience function to bundle a fixture with wrangler without going
 * through the Effect service layer.
 */
export function bundleWithWrangler(config: BundleConfig): Effect.Effect<BundleResult, BundleError> {
  return Effect.try({
    try: () => {
      // Create a temp directory for the output
      const outdir = fs.mkdtempSync(path.join(os.tmpdir(), "distilled-bundler-wrangler-"));

      // Build the wrangler command
      // wrangler deploy --dry-run --outdir=<outdir>
      // Run from the fixture's project root so wrangler finds the config
      const args = [
        "deploy",
        "--dry-run",
        `--outdir=${outdir}`,
        `--config=${config.projectRoot}/wrangler.json`,
      ];
      if (config.minify) args.push("--minify");
      // Wrangler 4 `deploy --dry-run` does not expose a keep-names CLI flag.

      const cmd = `bun wrangler ${args.join(" ")}`;

      execSync(cmd, {
        cwd: config.projectRoot,
        stdio: "pipe",
        env: {
          ...process.env,
          // Suppress wrangler metrics/update prompts
          WRANGLER_SEND_METRICS: "false",
          // Ensure consistent NODE_ENV for define replacement
          NODE_ENV: "production",
        },
        timeout: 30_000,
      });

      // Parse the output directory into a BundleResult
      return parseOutputDir(outdir);
    },
    catch: (error) =>
      new BundleError({
        message: `Wrangler build failed: ${error instanceof Error ? error.message : String(error)}`,
        cause: error,
      }),
  });
}

/**
 * Parses a wrangler --outdir output directory into a BundleResult.
 *
 * The directory typically contains:
 * - index.js (or similar) — the main bundled entry point
 * - index.js.map — source map
 * - README.md — auto-generated by wrangler
 * - *.wasm, *.txt, *.bin — additional modules (possibly with hash prefixes)
 */
function parseOutputDir(outdir: string): BundleResult {
  const files = listFilesRecursive(outdir);

  // Find the entry point (the main .js file that isn't a module)
  // It's the JavaScript file that is NOT a hash-prefixed additional module
  let entryPoint: string | null = null;
  const modules: Array<Module> = [];

  for (const filePath of files) {
    const name = path.relative(outdir, filePath);
    const ext = path.extname(filePath);

    // Skip non-output files
    if (name === "README.md") continue;

    const content = fs.readFileSync(filePath);
    const mod = new Module({
      name: name,
      content: fs.readFileSync(filePath),
      hash: hash(content),
      type: moduleTypeFromExtension(ext),
    });

    if (isEntryPoint(name, ext)) {
      entryPoint = name;
      modules.unshift(mod);
    } else {
      modules.push(mod);
    }
  }

  if (!entryPoint) {
    throw new Error(
      `No entry point found in wrangler output: ${outdir}\nFiles: ${files.map((f) => path.relative(outdir, f)).join(", ")}`,
    );
  }

  return {
    main: entryPoint,
    modules,
    outDir: outdir,
    warnings: [],
  };
}

/**
 * Determines whether a file is the main entry point or an additional module.
 *
 * Heuristic: entry points are .js files without a content hash prefix.
 * Wrangler names additional modules as `<hash>-<originalName>.<ext>`.
 */
function isEntryPoint(relative: string, ext: string): boolean {
  if (ext !== ".js" && ext !== ".mjs") return false;
  const basename = path.basename(relative);
  // Hash-prefixed modules have a 40-char hex prefix followed by a dash
  return !/^[0-9a-f]{40}-/.test(basename);
}

/**
 * Recursively lists all files in a directory.
 */
function listFilesRecursive(dir: string): Array<string> {
  const results: Array<string> = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...listFilesRecursive(fullPath));
    } else {
      results.push(fullPath);
    }
  }
  return results;
}

/**
 * Maps file extensions to ModuleType for parsing wrangler output.
 */
function moduleTypeFromExtension(ext: string): ModuleType {
  switch (ext) {
    case ".wasm":
      return "CompiledWasm";
    case ".txt":
    case ".html":
    case ".sql":
    case ".custom":
      return "Text";
    case ".bin":
      return "Data";
    case ".mjs":
    case ".js":
      return "ESModule";
    case ".cjs":
      return "CommonJS";
    case ".map":
      return "SourceMap";
    default:
      throw new Error(`Unknown extension: ${ext}`);
  }
}
