/**
 * Hoists an `alchemy` launcher into every `node_modules/.bin/` in the
 * workspace so `bun run deploy` / `alchemy ...` works from any workspace
 * member during dev.
 *
 * The hoisted shim is NOT the same as the launchers shipped in
 * `@alchemy.run/cli-posix` / `@alchemy.run/cli-win32`:
 *
 *   • The published platform launchers always exec the built
 *     `bin/alchemy.js`, because npm/bun consumers install the tarball and
 *     don't have the TypeScript source.
 *   • The dev shim execs `bin/alchemy.ts` directly under bun, skipping the
 *     build step entirely; it only falls back to `bin/alchemy.js` when bun
 *     isn't available and we have to use node.
 *
 * This matters because `bun pm pack` on the main alchemy package bundles the
 * build output, and a stale `bin/alchemy.js` during dev would silently
 * diverge from source. Running the .ts file directly means dev iteration is
 * edit → reload, with no rebuild step.
 *
 * Why this script exists at all: bun workspaces do not hoist bins from a
 * workspace package's `optionalDependencies`, so the platform launchers never
 * reach consumer workspaces. Published installs are unaffected — npm/bun
 * flatten optional deps and hoist their bins normally. This script runs only
 * on `bun install` inside the monorepo because it's registered as the root
 * `package.json`'s postinstall, and that root is `"private": true` — it's
 * never installed as a dependency by anyone.
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

const repoRoot = process.cwd();
const isWin = process.platform === "win32";

// Use forward slashes in paths embedded in the shim text. Bun and Windows
// both accept forward slashes, and avoiding backslashes in shim args sidesteps
// any chance of `\c`, `\p` etc. being mis-handled as escape sequences.
const toShimPath = (p: string) => p.replace(/\\/g, "/");

const tsEntry = toShimPath(
  resolve(repoRoot, "packages", "alchemy", "bin", "alchemy.ts"),
);
const jsEntry = toShimPath(
  resolve(repoRoot, "packages", "alchemy", "bin", "alchemy.js"),
);
const tsconfigPath = resolve(repoRoot, "packages", "alchemy", "tsconfig.json");
// Pin bun's tsconfig to the alchemy package, not whatever happens to be in
// the invoking workspace's cwd. Bun's default is `$cwd/tsconfig.json`,
// which means invoking `alchemy` from e.g. `examples/cloudflare-solidstart`
// would transpile alchemy's own .tsx files with that example's JSX settings
// (jsx: "preserve", jsxImportSource: "solid-js"), breaking React files
// inside the alchemy CLI.
//
// The path is computed per-shim as relative-from-the-shim's-dir, anchored
// at runtime with `%~dp0` (cmd) or `$(dirname "$0")` (sh) so it survives
// the repo being checked out at different absolute paths.

if (!existsSync(tsEntry)) {
  console.warn(`[hoist-alchemy-bin] entry not found at ${tsEntry}; skipping`);
  process.exit(0);
}

// Stale shim variants that previous installs may have left behind. Old
// alchemy releases registered `bin/alchemy.sh`, which bun translated into
// `.bunx` / `.exe` wrappers hardcoding `/bin/sh` as the interpreter. If we
// don't clear them, they can win the PATH lookup before our replacement and
// reproduce the "interpreter executable /bin/sh not found" error on Windows.
const staleNames = [
  "alchemy",
  "alchemy.cmd",
  "alchemy.bunx",
  "alchemy.exe",
  "alchemy.ps1",
  "alchemy.sh",
];

// On POSIX the shim picks bun when either the invoking package manager is
// bun ($npm_execpath contains "bun") or bun is on PATH, otherwise falls back
// to node. On Windows we do the same with cmd-syntax equivalents.
const posixShim = `#!/bin/sh
# Auto-generated by scripts/hoist-alchemy-bin.ts. Do not edit.
# Dev-only shim: runs alchemy.ts under bun, falls back to alchemy.js under node.
RUNTIME=node
case "$npm_execpath" in
  *bun*) RUNTIME=bun ;;
esac
if [ "$RUNTIME" = "node" ] && command -v bun >/dev/null 2>&1; then
  RUNTIME=bun
fi
if [ "$RUNTIME" = "bun" ]; then
  exec bun --tsconfig-override="$(dirname "$0")/__TSCONFIG_REL__" "${tsEntry}" "$@"
else
  exec node "${jsEntry}" "$@"
fi
`;

const windowsShim = `@echo off
rem Auto-generated by scripts/hoist-alchemy-bin.ts. Do not edit.
rem Dev-only shim: runs alchemy.ts under bun, falls back to alchemy.js under node.
setlocal enabledelayedexpansion
set "RUNTIME=node"
if defined npm_execpath (
  echo %npm_execpath% | findstr /I "bun" >nul && set "RUNTIME=bun"
)
if "!RUNTIME!"=="node" (
  where bun >nul 2>nul && set "RUNTIME=bun"
)
if "!RUNTIME!"=="bun" (
  bun --tsconfig-override="%~dp0__TSCONFIG_REL__" "${tsEntry}" %*
) else (
  node "${jsEntry}" %*
)
exit /b %ERRORLEVEL%
`;

function writeShim(binDir: string) {
  mkdirSync(binDir, { recursive: true });
  for (const name of staleNames) {
    const p = join(binDir, name);
    if (existsSync(p)) {
      try {
        rmSync(p, { force: true });
      } catch {
        // Best-effort cleanup; keep going.
      }
    }
  }

  // Relative path from this shim's dir to the tsconfig, resolved at runtime
  // via `%~dp0` / `$(dirname "$0")`.
  const tsconfigRel = toShimPath(relative(binDir, tsconfigPath));

  if (isWin) {
    writeFileSync(
      join(binDir, "alchemy.cmd"),
      windowsShim.replace("__TSCONFIG_REL__", tsconfigRel),
    );
  } else {
    const shimPath = join(binDir, "alchemy");
    writeFileSync(
      shimPath,
      posixShim.replace("__TSCONFIG_REL__", tsconfigRel),
      {
        mode: 0o755,
      },
    );
  }
}

/**
 * Find every workspace member's node_modules/.bin directory (plus the root).
 * `bun run` walks PATH from the cwd up through ancestor node_modules/.bin
 * dirs, so in principle we only need the root. In practice leftover stale
 * shims in per-workspace .bin dirs can still win the lookup, so we install
 * the real shim in each.
 */
function workspaceDirs(): string[] {
  const rootPkg = JSON.parse(
    readFileSync(join(repoRoot, "package.json"), "utf-8"),
  ) as { workspaces?: string[] | { packages?: string[] } };
  const globs: string[] = Array.isArray(rootPkg.workspaces)
    ? rootPkg.workspaces
    : (rootPkg.workspaces?.packages ?? []);

  const dirs = new Set<string>([repoRoot]);
  for (const pattern of globs) {
    // Support only the `parent/*` form actually used in this repo.
    if (pattern.endsWith("/*")) {
      const parent = pattern.slice(0, -2);
      const parentPath = join(repoRoot, parent);
      if (!existsSync(parentPath)) continue;
      for (const entry of readdirSync(parentPath, { withFileTypes: true })) {
        if (!entry.isDirectory()) continue;
        const candidate = join(parentPath, entry.name);
        if (existsSync(join(candidate, "package.json"))) {
          dirs.add(candidate);
        }
      }
    } else {
      const candidate = join(repoRoot, pattern);
      if (existsSync(join(candidate, "package.json"))) {
        dirs.add(candidate);
      }
    }
  }
  return [...dirs];
}

let touched = 0;
for (const dir of workspaceDirs()) {
  const binDir = join(dir, "node_modules", ".bin");
  // Only install in workspaces that have been bun-installed (have a
  // node_modules). Skip ones that haven't — they don't need the shim.
  if (!existsSync(dirname(binDir))) continue;
  try {
    writeShim(binDir);
    touched++;
  } catch (err) {
    // Non-fatal: don't let a write failure in one workspace block install.
    console.warn(
      `[hoist-alchemy-bin] failed to write shim in ${binDir}: ${err}`,
    );
  }
}

console.log(
  `[hoist-alchemy-bin] installed alchemy shim in ${touched} .bin dir(s)`,
);
