#!/bin/sh
set -e

NX_PRODUCTION_EXCLUDE="${NX_PRODUCTION_EXCLUDE:-@oddlynew/alchemy-website,@oddlynew/alchemy-example-*,@oddlynew/cloudflare-tools-fixture-*}"
GOMAXPROCS="${GOMAXPROCS:-4}"
NX_DAEMON="${NX_DAEMON:-false}"

export NX_PRODUCTION_EXCLUDE
export GOMAXPROCS
export NX_DAEMON

bun oxfmt . --check
bun nx affected -t lint --parallel=3 --exclude="$NX_PRODUCTION_EXCLUDE"
bun nx affected -t typecheck --parallel=3 --exclude="$NX_PRODUCTION_EXCLUDE"
bun nx affected -t test --parallel=3 --exclude="$NX_PRODUCTION_EXCLUDE" -- --run
